### ISSUE TITLE
Как установить на FreeBSD?

### ISSUE THREAD

**Issue by RueMagicien** [YouROK/TorrServer#101]
Скачал файл TorrServer-freebsd-amd64, но как его установить? `pkg add` и `make install` неработают, пишет `"Failed to install the following 1 package(s): TorrServer-freebsd-amd64"`   и сам файл незапускаеться.

**Comment by tsynik** [comment]
> Скачал файл TorrServer-freebsd-amd64, но как его установить? `pkg add` и `make install` неработают, пишет `"Failed to install the following 1 package(s): TorrServer-freebsd-amd64"` и сам файл незапускаеться.

скрипт авто-запуска пишется самостоятельно, сервер запускается установкой иполняемого бита и выполнением: chmod 755 TorrServer-freebsd-amd64; ./TorrServer-freebsd-amd64
