### ISSUE TITLE
КЕШ

### ISSUE THREAD

**Issue by Joy096** [YouROK/TorrServer#103]
Если без добавления воспроизводить торрент фильм через сервер, то после - кеш не очищается, как если бы я фильм добавил через контекстное меню, просмотрел, а потом удалил. Версия Torrserver 104. В настройках стоит место хранения кеша - ПЗУ/ накопитель.
![image_2021-08-29_19-15-47](https://user-images.githubusercontent.com/44851817/131257539-60b95794-1c51-4713-b737-13e3da383bb0.png)

**Comment by tsynik** [comment]
> Если без добавления воспроизводить торрент фильм через сервер, то после - кеш не очищается, как если бы я фильм добавил через контекстное меню, просмотрел, а потом удалил. Версия Torrserver 104. В настройках стоит место хранения кеша - ПЗУ/ накопитель.

Для очистки кеша при отключении торрента нужно включить соотвествующую опцию в настройках - Очищать кеш при отключении торрента
