### ISSUE TITLE
Ошибка при просмотре через DLNA 

### ISSUE THREAD

**Issue by afonasiev** [YouROK/TorrServer#104]
Сервер(v.105) на macOS.
Телевизор LG UM7100.
При просмотре торрента через DLNA в котором несколько частей, для примера сериал какой либо, с высокой вероятностью отрубается сервер.
<img width="663" alt="Снимок экрана 2021-09-02 в 19 01 28" src="https://user-images.githubusercontent.com/11653034/132076498-4d8cd6f8-0f35-4869-846d-23d844cdd52a.png">
<img width="1030" alt="Снимок экрана 2021-09-02 в 18 58 02" src="https://user-images.githubusercontent.com/11653034/132076499-0c282e00-089e-4a78-bdcd-e4f214d227d3.png">

**Comment by YouROK** [comment]
На новой версии как?
