### ISSUE TITLE
Windows go sleep

### ISSUE THREAD

**Issue by Anton111111** [YouROK/TorrServer#105]
While i view video windows go sleep. I think will be good if server will prevent sleep while torrent is active.
I made small research and how i see it's possible. For example: https://stackoverflow.com/questions/45436158/how-to-to-stop-a-machine-from-sleeping-hibernating-for-execution-period

**Comment by YouROK** [comment]
https://github.com/YouROK/TorrServer/commit/6d499aa655409301b1e05885b0a47dfd829c5e94
