### ISSUE TITLE
Рандомные зависания

### ISSUE THREAD

**Issue by ivanich** [YouROK/TorrServer#11]
Периодически на Raspberry Pi4 поток останавливается, в логах появляется это
```янв 01 22:18:01 raspberrypi TorrServer-linux-arm7[18186]: Close cache for: f7274c113cb10b92c652583c20c2986a89ac50c7
янв 01 22:34:17 raspberrypi TorrServer-linux-arm7[18186]: 2020-01-01 22:34:17 torrent.go:1519: piece failed hash: 3 connections contributed, [{*torrent.Client [0x21cc1c0]} {*torrent.Piece [d93d8e85d9f58965b2b72eea3e317e095fb41326/819]} >
янв 01 22:35:59 raspberrypi TorrServer-linux-arm7[18186]: 2020/01/01 22:35:59 error reading torrent d93d8e85d9f58965b2b72eea3e317e095fb41326 piece 817 offset 0, 6776 bytes: unexpected EOF
янв 01 22:36:01 raspberrypi TorrServer-linux-arm7[18186]: 2020/01/01 22:36:01 error reading torrent d93d8e85d9f58965b2b72eea3e317e095fb41326 piece 818 offset 0, 6776 bytes: unexpected EOF
янв 01 22:36:40 raspberrypi TorrServer-linux-arm7[18186]: Play: map[file:[0] link:[magnet:?xt=urn:btih:d93d8e85d9f58965b2b72eea3e317e095fb41326&dn=The.Moodys.US.s01e06.WEBDL.1080p.NewStudio.TV.mkv&tr=http://newstudio.tv:2710/ffffffff59e>
янв 01 22:36:40 raspberrypi TorrServer-linux-arm7[18186]: 2020/01/01 22:36:40 Connect client
янв 01 22:36:40 raspberrypi TorrServer-linux-arm7[18186]: 2020/01/01 22:36:40 Connect client
янв 01 22:36:40 raspberrypi TorrServer-linux-arm7[18186]: 2020/01/01 22:36:40 error reading torrent d93d8e85d9f58965b2b72eea3e317e095fb41326 piece 822 offset 665836, 13815 bytes: unexpected EOF
```
Помогает только рестарт, до тех пор открыть именно этот торрент невозможно.
Так же предположительно есть проблемы в работе с памятью, а именно не освобождается процессом даже в простое, может дойти до 3-х гигабайт и не освобождаться сутками, при том что torrserver все это время не используется.

EDIT: На linux amd64 такие же проблемы, так что отредактировал subject

**Comment by wpresident** [comment]
мне на arm (odroid hc2) помогли такие настройки, до этого такие же были ошибки
кеш 200, откл utp, макс соед. 50, dht 500

**Comment by yozik04** [comment]
У меня тоже зависания, но прослеживиется какая-то логика. Пока кэш не полный все проигрывается красиво и без тормозов. Кеш поставил 4 Гб. Так как на сервере 16Гб оперативки. Смотрю видос с открытыми логами и слежу за заполнением кеша в веб интерфейсе. Когда кэш заполняется Torserve начинает подчищать предыдущие блоки. Тогда через некоторое время начинают выпадать сообщения вида:
```
Jan 10 22:34:17 server torrserver[19893]: 2020/01/10 22:34:17 error reading torrent 386f9304a57a2b2f6b2f6cd23a0b55d5021f1777 piece 40 offset 0, 123 bytes: unexpected EOF
```
В этот момент в кэше уже нет 40вого блока. Оттуда и ошибка.

Я так понимаю что плеер пытается запросить блок который только что был почищен. Оттуда наверное и зависания.

Я использую linux amd64 версию. Тестирую 4К видео на 40+Гб.

Еще у меня в логах при больших файлах плеер часто реконнектится. Может это тоже влияет.
```
Jan 10 22:19:23 server torrserver[19893]: 2020/01/10 22:19:23 Connect client
Jan 10 22:19:25 server torrserver[19893]: 2020/01/10 22:19:25 Disconnect client
Jan 10 22:19:25 server torrserver[19893]: 2020/01/10 22:19:25 Connect client
Jan 10 22:19:25 server torrserver[19893]: 2020/01/10 22:19:25 Disconnect client
Jan 10 22:19:25 server torrserver[19893]: 2020/01/10 22:19:25 Connect client
Jan 10 22:19:27 server torrserver[19893]: 2020/01/10 22:19:27 Disconnect client
Jan 10 22:19:27 server torrserver[19893]: 2020/01/10 22:19:27 Connect client
Jan 10 22:19:27 server torrserver[19893]: 2020/01/10 22:19:27 Disconnect client
Jan 10 22:19:27 server torrserver[19893]: 2020/01/10 22:19:27 Connect client
```

Пробовал разные плееры: VLC, MX Player, родной от Sony. Наиболее стабильно работает родной но все равно через какое-то время начинает затыкаться.

Могу помочь дебажить ибо сам девелопер.

**Comment by yozik04** [comment]
Забыл сказать. Пробовал в VLC проигрывать с компа. Результат тот же.

**Comment by YouROK** [comment]
А зачем так много, это не совсем кэш
То что он пытается запросить удалённый кусок, это скорее ошибка движка или так нужно для него, это запрос от других пиров на сколько я понял, при кэше 200 этого почти не происходит. Советую сделать кэш 200 а в плеере уже увеличивать кэш для фильма

**Comment by yozik04** [comment]
Про ошибку какого движка речь?

Попробую.
А цвета блоков кэша что означают? Синий это то что скачивается в данный момент?

**Comment by yozik04** [comment]
@YouROK Я вроде врубился как TorrServer работает. Медиаплеер запрашивает кусок (кусок загорается голубым). TorrServer его скачивает и отдает медиаплееру. Никакого скачивания вперед не ведется. В кэше хранятся только предыдущие куски? Я прав? Тогда тут играть только буффером медиа плеера.

**Comment by wpresident** [comment]
еслиб кеша вперед не было, не было бы идеально плавного воспроизведения на 70ГБ ремуксах :)
оставте кеш 200МБ для обычных устройств, не больше, и 80-100МБ для совсем слабых с 1.5гб оперативки. Этого вполне достаточно.
После намеренного убивания сервера кино будет еще секунд 7-10 проигрываться из последних кусков в кеше, этого более чем достаточно.
У меня во время эксперементов 400-800МБ кеше ничего стабильно не работало - через 30-60мин, но обязательно кино зависнет, хотя казалось бы что должно быть наоборот. Но при таких объемах в движке что-то идет не так, и куски начинают прыгать местами или удаляться. Дефолтные 200МБ показали себя лучше всего, за 2.5ч фильмы не падают и проматываются за 2 секунды.
~
вообще с промоткой фильмов лучше не увлекаться. я заметил, что в определенных сценариях, если промотать вперед на 2 мин, потом обратно назад чуть раньше чем было (2.5мин), то проигрывание остановится после того самого предыдущего куска, а так как торрент до этого уже был скачан на несколько кусков вперед, то движок сходит с ума и уже не хочет качать снова какой-то недавних прошлых. Кароче лучше юзать паузу, и проматывать не более 1 раза :)

**Comment by yozik04** [comment]
А по плееру на андроид тв рекомендации есть? У большинства нет настроек буфера.

**Comment by wpresident** [comment]
Я периодически пытаюсь слезть с Kodi, как плеера,на что-то другое. Нет, не удаётся. Самый правильный процесс проигрывания разных кодеков и файлов.. В общем на нем и сижу. 
Там можно настроить его собственный кеш: https://kodi.wiki/view/HOW-TO:Modify_the_video_cache
Есть плагин, который сам исходя из параметров девайса сделает эти настройки как надо, можно пользоваться спокойно. 
http://areswizard.co.uk/script.areswizard-0.0.69.zip запустить, перейти в раздел Tweaks, запустить мастер установки параметров, и можно прокликать вперед до применения.
