### ISSUE TITLE
9080 port in use

### ISSUE THREAD

**Issue by asd2003ru** [YouROK/TorrServer#110]
Debian.
Запускаю torrerver без config.db с параметрами torrserver --port 8090 --path /opt/torrserver --httpauth
Все нормально запускается, висит на нужном порту.
Захожу в настройки через web и стоит включить DNLA и сохранить как программа вываливается. Как показали логи она начинает игнорировать --port и вешаться на 9080 (у меня он уже занят). Сношу конфиг и все работает.
И если возможно, добавить опцию на какой IP биндится. А то на машине есть докер и как я понял программа пытается на все 172. ip вешаться.

**Comment by YouROK** [comment]
9080 это порт для длна сервера, для ответов длна. Как будет доделан сервер, запросы перенесу на основной сервер
