### ISSUE TITLE
A delay while saving settings

### ISSUE THREAD

**Issue by skunkie** [YouROK/TorrServer#115]
Make a change in the settings, click the save button, then reopen the settings dialog, it will show the previous state.

**Comment by tsynik** [comment]
> Make a change in the settings, click the save button, then reopen the settings dialog, it will show the previous state.

Can't reproduce: I see new settings after reopen settings dialog (as they readed from server again on each open). Your issue can be because settings not saved when you save them (what's in server's log on save?)

**Comment by skunkie** [comment]
There is a delay between the saving and reading the settings. So if I reopen the settings dialog immediately, it shows the old values. If I wait a bit, it shows the correct values.

**Comment by tsynik** [comment]
> There is a delay between the saving and reading the settings. So if I reopen the settings dialog immediately, it shows the old values. If I wait a bit, it shows the correct values.

yes, it's okay. settings not saved immediately. an it shows you actual values on the moment of opening

**Comment by skunkie** [comment]
Is it fixable?

**Comment by tsynik** [comment]
> Is it fixable?

I don't see what to fix here. Delay is for dropping all torrents before apply new settings (which also restarts whole server and it even not exists about a second on apply. When you open Settings dialog - it reads from torrserver and show you current values.

**Comment by skunkie** [comment]
Could [handleClose()](https://github.com/YouROK/TorrServer/blob/MatriX.106/web/src/components/Settings/SettingsDialog.jsx#L40) be called last?

**Comment by tsynik** [comment]
> Could [handleClose()](https://github.com/YouROK/TorrServer/blob/MatriX.106/web/src/components/Settings/SettingsDialog.jsx#L40) be called last?

probably there will be no any difference with it's called last.

**Comment by skunkie** [comment]
It is not related to the frontend, it is the backend, that should be changed. I will make a PR.

**Comment by skunkie** [comment]
Please link https://github.com/YouROK/TorrServer/pull/116 to this issue.

**Comment by tsynik** [comment]
> Please link #116 to this issue.

relocating save code in apihelper is not a correct way to "fix" your "issue". You need to implement and serve server's reply on settings save and use i as a flag to close dialog which actually close window on save or shows error.
