### ISSUE TITLE
how to install TorrServer on Raspberry Pi

### ISSUE THREAD

**Issue by arashtotti88** [YouROK/TorrServer#119]
Hi I have an issue with installing TorrServer on Raspberry Pi

I don't know how to install it.

Basically, there is no step by step tutorial for this

is there anyone to make a step by step tutorial for everyone

thank you so much

**Comment by juspaz** [comment]
The way I've done it on Raspberry PI 4:

1. Go to [releases](https://github.com/YouROK/TorrServer/releases/tag/MatriX.106) and copy link for ARM v7
2. SSH to your raspberry
3. `wget <url>` for example: `wget https://github.com/YouROK/TorrServer/releases/download/MatriX.106/TorrServer-linux-arm7`
4. Add executable flag `chmod +x TorrServer-linux-arm7`
5. Run `./TorrServer-linux-arm7 &`

Readme also says 
`On linux systems you need to set the environment variable before run 
export GODEBUG=madvdontneed=1
`

I missed this and it worked either way, but you might want to set that up.

Also, when you restart raspberry you will have to run it manually again. [This](https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/) has some ideas how to make it start automatically after each reboot.

**Comment by arashtotti88** [comment]
cheers mate, great tutorial and it worked perfectly .

thanks again

**Comment by YouROK** [comment]
https://telegra.ph/Torrserve-01-21
Use translator if not speak Russian
