### ISSUE TITLE
network is unreachable

### ISSUE THREAD

**Issue by rodin-ia** [YouROK/TorrServer#12]
При старте, в лог пишутся такие сообщения:
`Check dns [] lookup www.themoviedb.org on 127.0.0.53:53: server misbehaving
Check new dns [] lookup www.themoviedb.org on 127.0.0.53:53: dial udp 1.1.1.1:53: connect: network is unreachable
Start web server, version: 1.1.76`
Через nslookup адрес www.themoviedb.org резолвится нормально, как через локальный dns так и через 1.1.1.1
Сам torrserver запускается и работает нормально, смущают только эти сообщения.
torrserver x64 на ubuntu

**Comment by YouROK** [comment]
Надо убрать, это замена днс в серваке
