### ISSUE TITLE
Extract settings from the config.db to a separate settings file.

### ISSUE THREAD

**Issue by sprilukin** [YouROK/TorrServer#121]
Currently, settings are stored as a part of `config.db` database which has a binary format, so the only way to change these settings is via using REST API, however, i want to preconfigure my TorrServer instance before the first run. 

So i think it would be natural to have a separate file where all settings are stored in a human-readable format.

**Comment by z8512** [comment]
I also want this

**Comment by z8512** [comment]
Please..

**Comment by z8512** [comment]
@YouROK

**Comment by z8512** [comment]
@YouROK config file..
