### ISSUE TITLE
Linux server update.sh file

### ISSUE THREAD

**Issue by TheMasterDan** [YouROK/TorrServer#122]
#!/bin/bash
lastver=$(cat version)
currver=$(curl -s https://github.com/YouROK/TorrServer/releases/latest | grep "MatriX.*" | cut -d '"' -f 2  | cut -d '/' -f 8)

if [[ "$currver" == "$lastver" ]]
then
  echo "No need to update"
else
    echo "Version not equal"
    /usr/bin/supervisorctl stop Torrserver
    mv ./TorrServer-linux-amd64 ./TorrServer-linux-amd64.$lastver
    path="https://github.com/YouROK/TorrServer/releases/download/"$currver"/TorrServer-linux-amd64"
    echo "Download "$path....
    wget $path
    echo $currver > version....
    chmod +x ./TorrServer-linux-amd64
    /usr/bin/supervisorctl start Torrserver
    exit
fi

**Comment by YouROK** [comment]
Можно положить в гит рядом со сборкой, если будет реквест добавлю
