### ISSUE TITLE
Не запускается с медленной флешки

### ISSUE THREAD

**Issue by minimize135** [YouROK/TorrServer#123]
Роутер Newifi 3 D2, OpenWrt 21.02

Из /tmp(ram) стартует нормально, а после переноса в /root(flash) не стартует - пишет:
Error open db: /root/config.db

Помогает только такой костыль:
/root/torrserver --path /tmp

настроил и потом делаю
cp /tmp/config.db /root

и в автозагрузку добавил
cp /root/config.db /tmp
/root/torrserver --path /tmp

P.S. проверял на 109 и 106

**Comment by YouROK** [comment]
Доступ есть в папку /root?
