### ISSUE TITLE
DLNA в версии 110

### ISSUE THREAD

**Issue by serge73** [YouROK/TorrServer#129]
После перехода с 109 на 110 сервер пропал DLNA запущенный на debian linux amd64.
Телевизоры и компьютер DLNA не видят, при этом веб интерфейс  работает.

root@xxx:/opt/torrserver# ./TorrServer-linux-amd64
=========== START ===========
TorrServer MatriX.110, go1.17.5
CPU Num: 8
2021/12/14 07:50:13 Check dns OK [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx] <nil>
2021/12/14 07:50:13 Check web port 8090
2021/12/14 07:50:13 Start TorrServer
2021/12/14 07:50:13 IP: [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
2021/12/14 07:50:13 Check upnp port 32000
2021/12/14 07:50:13 Set upnp port 32000
2021/12/14 07:50:13 Client config: {"CacheSize":100663296,"ReaderReadAHead":95,"PreloadCache":0,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":true,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":true,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":23,"PeersListenPort":0}
2021/12/14 07:50:13 Check dlna port 9080
2021/12/14 07:50:13 Set dlna port 9080
2021/12/14 07:50:13 HTTP srv on [::]:9080
2021/12/14 07:50:13 Start web server at port 8090
2021/12/14 07:50:13 started SSDP on enp7s1
2021/12/14 07:50:13 started SSDP on ppp0
2021/12/14 07:50:13 started SSDP on eno1
2021-12-14T07:50:15+0500 INFO  portfwd.go:24: UPnP device at 192.168.1.100: mapping internal UDP port 32000: success: external port 32000
2021-12-14T07:50:16+0500 INFO  portfwd.go:24: UPnP device at 192.168.1.100: mapping internal TCP port 32000: success: external port 32000
2021-12-14T07:50:40+0500 NONE  client.go:326: dht server on 0.0.0.0:32000 (node id 0edd98f524157951bf7f7adb572c9eb490f88ef1) completed bootstrap ({61 21})
^C

**Comment by tsynik** [comment]
возможно дело в интрфейсах для ssdp анонса (enp7s1 ppp0 eno1) - воспроизвести не удалось

**Comment by tsynik** [comment]
hm looks like this is issued by this commit in DMS: https://github.com/tsynik/dms/commit/351b3569fbe2111dba19945bfdd6d463bb0862fc - reverted in TorrServer master

**Comment by serge73** [comment]
`возможно дело в интрфейсах для ssdp анонса (enp7s1 ppp0 eno1) - воспроизвести не удалось`
маловероятно, в 109 все прекрасно работало, я только файлы TorrServer-linux-amd64 поменял и сервис перезагрузил.

В логе где xxxxxxx....   все айпишники стоят как надо.

**Comment by serge73** [comment]
Похоже на то, что DLNA не запускается на компьютерах с несколькими поднятыми сетевыми интерфейсами.
Точно есть проблема на Windows 10, но скорее всего и на linux. На другой линуксовой машине с одним интерфейсом все заработало сразу.
PS на винде включал и отключал Hyper-V Virtual Ethernet Adapter, думаю можно на любой современной  машине с windows включить и смоделировать ситуацию.

**Comment by tsynik** [comment]
must be fixed in https://github.com/YouROK/TorrServer/releases/tag/MatriX.111
reopen if not
