### ISSUE TITLE
DLNA не показывает содержимое на Tizen (samsung)

### ISSUE THREAD

**Issue by serge73** [YouROK/TorrServer#130]
Проблема, я так понимаю, старая. Планируется ли доработка функциональности для Tizen?
DLNA открывается, но содержимое полностью отсутствует.
Проверил используя телефон android с сервером версии 109 и 110 и версию linux amd64 v109.

**Comment by YouROK** [comment]
Пока кто-нибудь знающий протокол dlna по таймеру не поправит, будет так. Мы не можем определить почему так

**Comment by serge73** [comment]
Я правильно понимаю, что проблема у всех кто использует  https://github.com/anacrolix/dms, который не работает с samsung и править нужно там?

**Comment by tsynik** [comment]
> Я правильно понимаю, что проблема у всех кто использует https://github.com/anacrolix/dms, который не работает с samsung и править нужно там?

правильно

**Comment by serge73** [comment]
В качестве обхода проблемы могу предложить использовать меню Торренты в приложении LAMPA, там все торренты, которые вы накидали  через браузер. Попробовал на Samsung Smart TV и Tizen. Скорее всего на всех устройствах будет работать, если Lampa сможете поставить.
Проблему #130, думаю закрывать не надо, информация очень поможет в поиске решения для новичков в TorrentServer и LAMPA.
