### ISSUE TITLE
bad URL request "200"

### ISSUE THREAD

**Issue by MrKsey** [YouROK/TorrServer#131]
В докер-контейнере (ubuntu:latest) с версией TorrServer 110 в логах стали постоянно сыпаться сообщения вида:
**bad URL request "200"**

Лог загрузки:
`
TorrServer MatriX.110, go1.17.5
CPU Num: 4
2021/12/14 08:55:28 Use HTTP Auth file /TS/db//accs.db
2021/12/14 08:55:28 Check dns OK [173.194.73.147 173.194.73.106 173.194.73.104 173.194.73.99 173.194.73.103 173.194.73.105 2a00:1450:4010:c07::69 2a00:1450:4010:c07::68 2a00:1450:4010:c07::93 2a00:1450:4010:c07::63] <nil>
2021/12/14 08:55:28 Check web port 8090
2021/12/14 08:55:28 Start TorrServer
2021/12/14 08:55:28 IP: [192.168.1.252 fe80::20c:29ff:fec3:8343 172.17.0.1 fe80::42:ebff:fe27:855e fe80::a0ab:9fff:fe14:8d49]
2021/12/14 08:55:28 Set listen port 50500
2021/12/14 08:55:28 Client config: {"CacheSize":524288000,"ReaderReadAHead":95,"PreloadCache":7,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":true,"RetrackersMode":1,"TorrentDisconnectTimeout":90,"EnableDebug":false,"EnableDLNA":true,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":11000,"UploadRateLimit":4000,"ConnectionsLimit":64,"PeersListenPort":50500}
2021/12/14 08:55:28 Check dlna port 9080
2021/12/14 08:55:28 Set dlna port 9080
2021/12/14 08:55:28 HTTP srv on [::]:9080
2021/12/14 08:55:28 Start web server at port 8090
2021/12/14 08:55:28 started SSDP on vethc8045ad
2021/12/14 08:55:28 started SSDP on eth0
2021/12/14 08:55:28 started SSDP on docker0
2021-12-14T08:55:30+0300 WARN  portfwd.go:17: UPnP device at 192.168.1.252: mapping internal UDP port 50500: error: AddPortMapping: 500 Internal Server Error
2021-12-14T08:55:30+0300 WARN  portfwd.go:17: UPnP device at 192.168.1.252: mapping internal TCP port 50500: error: AddPortMapping: 500 Internal Server Error
2021/12/14 08:55:32 ffprobe and avprobe not found in $PATH
2021/12/14 08:55:32 ffprobe and avprobe not found in $PATH
 
2021/12/14 08:55:39 bad URL request "200"
2021/12/14 08:55:39 bad URL request "200"
2021/12/14 08:55:39 bad URL request "200"
2021/12/14 08:55:50 bad URL request "200"
2021/12/14 08:55:50 bad URL request "200"
2021/12/14 08:55:50 bad URL request "200"
`

**Comment by tsynik** [comment]
по идее исправлено в 4fa474f0

**Comment by svlukas** [comment]
Этот коммит попал в версию 110?

Проблема всё еще наблюдается на 110 версии:

TorrServer MatriX.110, go1.17.5
CPU Num: 4
2021/12/29 02:24:41 Check dns OK [74.125.131.106 74.125.131.147 74.125.131.99 74.125.131.103 74.125.131.104 74.125.131.105 2a00:1450:4010:c0e::63 2a00:1450:4010:c0e::67 2a00:1450:4010:c0e::69 2a00:1450:4010:c0e::6a] <nil>
2021/12/29 02:24:41 Check web port 8090
2021/12/29 02:24:41 Start TorrServer
2021/12/29 02:24:41 IP: [192.168.1.2 fe80::78d2:4cbe:da9:6f4a 172.28.0.1 fe80::42:c1ff:fe40:df55 172.21.0.1 fe80::42:1fff:fe50:9054 172.18.0.1 172.17.0.1 fe80::42:a4ff:fe01:ef48 10.8.0.1 fe80::d03e:11ac:7051:7f4f fe80::ec04:95ff:fee0:4ca0 fe80::7444:c4ff:fe08:c005 fe80::948c:25ff:fea4:5542 fe80::e8c2:49ff:fe6f:4972 fe80::ac2f:7ff:fec5:9112]
2021/12/29 02:24:41 Check upnp port 32000
2021/12/29 02:24:41 Set upnp port 32000
2021/12/29 02:24:41 Client config: {"CacheSize":134217728,"ReaderReadAHead":95,"PreloadCache":24,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":true,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2021/12/29 02:24:41 Check dlna port 9080
2021/12/29 02:24:41 Set dlna port 9080
2021/12/29 02:24:41 HTTP srv on [::]:9080
2021/12/29 02:24:41 Start web server at port 8090
2021/12/29 02:24:41 started SSDP on vethe707b5a
2021/12/29 02:24:41 started SSDP on veth8f34f93
2021/12/29 02:24:41 started SSDP on docker0
2021/12/29 02:24:41 started SSDP on vetha23113b
2021/12/29 02:24:41 started SSDP on veth05c8b6f
2021/12/29 02:24:41 started SSDP on br-2fb94a64683c
2021/12/29 02:24:41 started SSDP on eno1
2021/12/29 02:24:41 started SSDP on tun0
2021/12/29 02:24:41 started SSDP on br-6aa6628847b3
2021/12/29 02:24:41 started SSDP on vethb7c46c8
2021/12/29 02:24:41 started SSDP on br-a8ddd49a6f5e
2021-12-29T02:24:43+0300 INFO  portfwd.go:24: UPnP device at 192.168.1.2: mapping internal TCP port 32000: success: external port 32000
2021-12-29T02:24:43+0300 INFO  portfwd.go:24: UPnP device at 192.168.1.2: mapping internal UDP port 32000: success: external port 32000
 
2021/12/29 02:24:53 bad URL request "200"
2021/12/29 02:24:53 bad URL request "200"
2021/12/29 02:24:53 bad URL request "200"
2021/12/29 02:24:53 bad URL request "200"
2021/12/29 02:24:53 bad URL request "200"
2021/12/29 02:24:53 bad URL request "200"
