### ISSUE TITLE
TorrServer в LG WebOS

### ISSUE THREAD

**Issue by vyalekseev** [YouROK/TorrServer#133]
Привет! А вы можете добавить TorrServer в официальный магазин LG WebOS? Чтобы можно было сразу оттуда устанавливать.

**Comment by serge73** [comment]
И LAMPA еще. Очень надо. :)))

Вас почти пиратский функционал приложения ни на какие мысли не наводит?

**Comment by YouROK** [comment]
Вебос и тайзаном не занимаюсь. Тем более на этих операционках обычно слабый проц
