### ISSUE TITLE
Проблема с просмотром видео 4K

### ISSUE THREAD

**Issue by grannymaster** [YouROK/TorrServer#135]
На мой домашний сервер установлен Xcp-ng, а мой TorrServe работает как виртуальная машина на Lubuntu.
Процессор (i7-8700k) и оперативная память (DDR4):
https://i.imgur.com/YqlqLk6.png

Скорость интернета на виртуальной машине: 
https://i.imgur.com/jUR6ZyF.png
и вся моя домашняя сеть - 1G.

Настройки Torrserve(TorrServer MatriX.111):
https://i.imgur.com/JvTQvv7.png
https://i.imgur.com/T8vybOl.png

Я смотрю на Nvidia Shield TV Pro. Все обновлено.

Проблема в том, что когда я пытаюсь воспроизвести видео 4K HDR/SDR приличного размера, что-то около 20-50 ГБ. Воспроизведение начинает заикаться, а затем просто останавливается.

Есть идеи, что делать?

**Comment by YouROK** [comment]
Без понятия. Может быть что сеть хренова настроена или пиров нет на таких торрентов
