### ISSUE TITLE
Проблема с проверкой целостности MatriX.111 на Manjaro

### ISSUE THREAD

**Issue by ProkhachAlexey** [YouROK/TorrServer#136]
➜  ~ pamac install torrserver-bin
Внимание: torrserver-bin доступен только из AUR
Подготовка...
Клонирование сборочных файлов torrserver-bin...
Генерация информации о torrserver-bin...
Проверка зависимостей для torrserver-bin...
Разрешение зависимостей...
Проверка на взаимные конфликты...

К сборке (1):
  torrserver-bin  MatriX.111-1    AUR

Править сборочные файлы : [п] 
Применить транзакцию ? [п/д/Н] y

Сборка torrserver-bin...
==> Сборка пакета torrserver-bin MatriX.111-1 (Ср 05 янв 2022 14:15:03)
==> Проверка зависимостей для запуска...
==> Проверка зависимостей для сборки...
==> Получение исходных файлов...
  -> Найден torrserver.service
  -> Найден systemd.patch
  -> Найден TorrServer-linux-amd64
==> Проверка файлов source с использованием b2sums...
    torrserver.service ... Готово
    systemd.patch ... Готово
==> Проверка файлов source_x86_64 с использованием b2sums...
    TorrServer-linux-amd64 ... СБОЙ
==> ОШИБКА: Исходные файлы не прошли проверку целостности!
Ошибка: Не удалось собрать torrserver-bin

**Comment by YouROK** [comment]
Обращайся к маинтейнерам, при чем тут исходники
