### ISSUE TITLE
Files are not displayed on Infuse DLNA (iOS)

### ISSUE THREAD

**Issue by cowabunga1** [YouROK/TorrServer#137]
![image](https://user-images.githubusercontent.com/5441527/148547745-0e262803-85df-466d-be7c-9b4c1710da66.png)

![image](https://user-images.githubusercontent.com/5441527/148547798-a6d95aaa-e431-4e09-b830-c4363f0eba3d.png)

**Comment by ANTPro** [comment]
On Matrix.111 version in VLC player on IPad Air it works (files show)

**Comment by YouROK** [comment]
Dlns добавлялась как тестовая функция, не на всех устройствах этот протокол работает, так как каждый производитель делает по своей спецификации
