### ISSUE TITLE
[Feature] Decoded audio stream

### ISSUE THREAD

**Issue by Illarius** [YouROK/TorrServer#138]
Integration with ffmpeg to stream the torrent with decoded audio stream on demand.
Many audiotracks are DTS which is not supported by modern TVs. 
Would be great to have an option to decode it to ac3 on the go.

**Comment by YouROK** [comment]
ffmpeg is written in C, and cross-compilation with it is not so easy to do

**Comment by TopperBG** [comment]
Why need of cross compile, could be as simple as
`ffmpeg -i file.mkv -map 0 -vcodec copy -scodec copy -acodec ac3 -b:a 640k file_AC3.mkv`
or packaged in transport stream

**Comment by Illarius** [comment]
> ffmpeg is written in C, and cross-compilation with it is not so easy to do

What if user gets ffmpeg on his own (compiles or gets precompiled binary for his architecture) and torrserver uses this existing binary? Is it possible?

**Comment by YouROK** [comment]
If you're talking about ffmpeg not a library, try converting the stream and output it somehow to the network via http

**Comment by SerhiyRomanov** [comment]
Relevant project to explore https://github.com/m1k1o/go-transcode
