### ISSUE TITLE
Get debug info

### ISSUE THREAD

**Issue by petrium** [YouROK/TorrServer#14]
Как можно выяснить детали и разобраться со следующей проблемой.
Некоторые торренты через Forkplayer и Torrserver проигрываются, а некоторые нет. При этом иногда это зависит от вида Forkplayer. 
Например торрент:  magnet:?xt=urn:btih:595d2ea49d9e9647164d9a476482520485001369
1. нормально качается через aForkPlayer (с телефона)
2. не качается через Forkplayer (Tizen SmartTV)
3. не качается через эмулятор и http://obovse.ru/ForkPlayer2.5/index.html

В качестве сервера во всех случаях используется TorrServer-windows-amd64 (версия 1.1.76). Ссылку открываю напрямую с playlist-а этого TorrServer через http://torrserver:8090/torrent/playlist.m3u

1. Рабочий вариант: Через aForkPlayer в лог пишется:
Create cache for: Scorpions-Rock.in.Rio.2019.XviD.HDTVRip-Лумина.avi
Play: map[file:[0] link:[magnet:?xt=urn:btih:595d2ea49d9e9647164d9a476482520485001369&dn=Scorpions-Rock.in.Rio.2019.XviD.HDTVRip-%D0%9B%D1%83%D0%BC%D0%B8%D0%BD%D0%B0.avi&tr=http%3A%2F%2F87.248.186.252%3A8080%2Fannounce&tr=http%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=http%3A%2F%2F210.244.71.25%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.filetracker.pl%3A8089%2Fannounce&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&tr=udp%3A%2F%2F46.148.18.250%3A2710&tr=http%3A%2F%2Ftracker2.wasabii.com.tw%3A6969%2Fannounce&tr=udp%3A%2F%2F%5B2001%3A67c%3A28f8%3A92%3A%3A1111%3A1%5D%3A2710&tr=http%3A%2F%2Fretracker.mgts.by%3A80%2Fannounce&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=http%3A%2F%2F46.4.109.148%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.grepler.com%3A6969%2Fannounce&tr=http%3A%2F%2F125.227.35.196%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.city9x.com%3A2710%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=http%3A%2F%2Fbt.svao-ix.ru%2Fannounce&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Fipv6.leechers-paradise.org%3A6969&tr=http%3A%2F%2Fretracker.local%2Fannounce&tr=http%3A%2F%2Ftracker.electro-torrent.pl%3A80%2Fannounce&tr=http%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker2.itzmx.com%3A6961%2Fannounce]]
2020/03/05 22:03:33 Preload: 595d2ea49d9e9647164d9a476482520485001369 0 / 100.00MB Speed: 0 Peers:[ 5 ] 5 / 34
Create 203 buffers
2020/03/05 22:03:34 Preload: 595d2ea49d9e9647164d9a476482520485001369 368.00KB / 100.00MB Speed: 368.22KB Peers:[ 7 ] 7 / 34
2020/03/05 22:03:35 Preload: 595d2ea49d9e9647164d9a476482520485001369 1.44MB / 100.00MB Speed: 1.08MB Peers:[ 5 ] 6 / 34
2020/03/05 22:03:36 Preload: 595d2ea49d9e9647164d9a476482520485001369 3.62MB / 100.00MB Speed: 2.16MB Peers:[ 6 ] 6 / 33
2020/03/05 22:03:37 Preload: 595d2ea49d9e9647164d9a476482520485001369 7.03MB / 100.00MB Speed: 3.44MB Peers:[ 6 ] 6 / 33
...

2. Нерабочий вариант: Через Forkplayer (Tizen SmartTV) в лог пишется по несколько раз:
Play: map[appid:[remote] box_client:[lg] box_hardware:[QRQQQ] box_mac:[b8bc5bb1a000] box_server:[13] cors:[tizen] country:[RU] f:[5] fname:[Scorpions-Rock.in.Rio.2019.XviD.HDTVRip-Лумина.avi.m3u] hw:[1.6] initial:[tForkPlayer2.57m|b8bc5bb1a000|QRQQQ|VNSKDCFCCAZVQ|MTU4MzQyNjEwOQQ=E2555|9642EB31A9E6D6D|tizenapi|0] link:[magnet:?xt=urn:btih:595d2ea49d9e9647164d9a476482520485001369&dn=Scorpions-Rock.in.Rio.2019.XviD.HDTVRip-%D0%9B%D1%83%D0%BC%D0%B8%D0%BD%D0%B0.avi&tr=http%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=http%3A%2F%2F46.4.109.148%3A6969%2Fannounce&tr=udp%3A%2F%2F46.148.18.250%3A2710&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=http%3A%2F%2Ftracker2.wasabii.com.tw%3A6969%2Fannounce&tr=http%3A%2F%2F87.248.186.252%3A8080%2Fannounce&tr=udp%3A%2F%2F%5B2001%3A67c%3A28f8%3A92%3A%3A1111%3A1%5D%3A2710&tr=udp%3A%2F%2Fipv6.leechers-paradise.org%3A6969&tr=http%3A%2F%2Fretracker.local%2Fannounce&tr=http%3A%2F%2Ftracker.grepler.com%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=http%3A%2F%2F125.227.35.196%3A6969%2Fannounce&tr=http%3A%2F%2F210.244.71.25%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.filetracker.pl%3A8089%2Fannounce] m3u:[true] platform:[tizen] third:[2] tvp:[0] vr:[1.38] w_lang:[ru]]
Play: map[file:[0] link:[magnet:?xt=urn:btih:595d2ea49d9e9647164d9a476482520485001369&dn=Scorpions-Rock.in.Rio.2019.XviD.HDTVRip-%D0%9B%D1%83%D0%BC%D0%B8%D0%BD%D0%B0.avi&tr=http%3A%2F%2F46.4.109.148%3A6969%2Fannounce&tr=http%3A%2F%2F125.227.35.196%3A6969%2Fannounce&tr=http%3A%2F%2F87.248.186.252%3A8080%2Fannounce&tr=udp%3A%2F%2Fipv6.leechers-paradise.org%3A6969&tr=http%3A%2F%2Ftracker.dler.org%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.filetracker.pl%3A8089%2Fannounce&tr=udp%3A%2F%2Fpublic.popcorn-tracker.org%3A6969%2Fannounce&tr=udp%3A%2F%2F46.148.18.250%3A2710&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=http%3A%2F%2Ftracker2.wasabii.com.tw%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.grepler.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.city9x.com%3A2710%2Fannounce&tr=http%3A%2F%2Ftracker.electro-torrent.pl%3A80%2Fannounce&tr=udp%3A%2F%2Fopentor.org%3A2710&tr=http%3A%2F%2Ftracker.tiny-vps.com%3A6969%2Fannounce&tr=udp%3A%2F%2F%5B2001%3A67c%3A28f8%3A92%3A%3A1111%3A1%5D%3A2710&tr=http%3A%2F%2Fretracker.local%2Fannounce&tr=http%3A%2F%2Fbt.svao-ix.ru%2Fannounce&tr=http%3A%2F%2Ftracker.internetwarriors.net%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker2.itzmx.com%3A6961%2Fannounce&tr=http%3A%2F%2F210.244.71.25%3A6969%2Fannounce&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&tr=http%3A%2F%2Fretracker.mgts.by%3A80%2Fannounce]]
2020/03/05 22:08:45 Connect client
2020/03/05 22:08:45 Disconnect client

3. Нерабочий вариант: Через Chrome и расширение эмулятор (http://obovse.ru/ForkPlayer2.5/index.html) сразу выходит ошибка:
2020/03/05 22:11:16 Web server error: code=405, message=Method Not Allowed, internal=<nil> /torrent/play?link=magnet%3A%3Fxt%3Durn%3Abtih%3A595d2ea49d9e9647164d9a476482520485001369%26dn%3DScorpions-Rock.in.Rio.2019.XviD.HDTVRip-%25D0%259B%25D1%2583%25D0%25BC%25D0%25B8%25D0%25BD%25D0%25B0.avi%26tr%3Dhttp%253A%252F%252Ftracker.tiny-vps.com%253A6969%252Fannounce%26tr%3Dhttp%253A%252F%252F46.4.109.148%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252F46.148.18.250%253A2710%26tr%3Dudp%253A%252F%252Ftracker.openbittorrent.com%253A80%252Fannounce%26tr%3Dhttp%253A%252F%252Ftracker2.wasabii.com.tw%253A6969%252Fannounce%26tr%3Dhttp%253A%252F%252F87.248.186.252%253A8080%252Fannounce%26tr%3Dudp%253A%252F%252F%255B2001%253A67c%253A28f8%253A92%253A%253A1111%253A1%255D%253A2710%26tr%3Dudp%253A%252F%252Fipv6.leechers-paradise.org%253A6969%26tr%3Dhttp%253A%252F%252Fretracker.local%252Fannounce%26tr%3Dhttp%253A%252F%252Ftracker.grepler.com%253A6969%252Fannounce%26tr%3Dhttp%253A%252F%252Ftracker.dler.org%253A6969%252Fannounce%26tr%3Dhttp%253A%252F%252F125.227.35.196%253A6969%252Fannounce%26tr%3Dhttp%253A%252F%252F210.244.71.25%253A6969%252Fannounce%26tr%3Dudp%253A%252F%252Ftracker.opentrackr.org%253A1337%252Fannounce%26tr%3Dhttp%253A%252F%252Ftracker.filetracker.pl%253A8089%252Fannounce&m3u=true&fname=Scorpions-Rock.in.Rio.2019.XviD.HDTVRip-%D0%9B%D1%83%D0%BC%D0%B8%D0%BD%D0%B0.avi.m3u&w_lang=ru&box_client=lg&box_mac=pc0784304880&box_hardware=spark&initial=ForkPlayer%202.5|pc0784304880|spark|pc0784304880|MTU4MzQyMDE0MQR=E4722|1CFF595F2587CCF|none|1&vr=0&platform=spark&country=RU&box_server=6&tvp=0&third=0&f=5&hw=1.6&box_user=petr%40mail.ru

**Comment by YouROK** [comment]
Проблема в больших ссылках, решена в последней версии
