### ISSUE TITLE
Неудовлетворительная работа ipv6

### ISSUE THREAD

**Issue by avengermsoft** [YouROK/TorrServer#140]
Добрый день!

Обмен по ipv6 в TorrServer идет очень плохо. В других torrent-клиентах все отлично по ipv6. 
Описание проблемы здесь https://github.com/anacrolix/torrent/issues/713#issuecomment-1015049373

Чего хотелось-бы:
1. При запуске TorrServer, чтобы явно можно было задать поле ClientConfig.PublicIp6, например через параметр -ipv6
2. Что бы при запуске TorrServer, если не задан параметр -ipv6, поле ClientConfig.PublicIp6 заполнялось адресом ipv6 из доступного списка, за исключением ipv6-локальных адресов.
Мой список ip:
[192.168.97.98 
2a05:3880:d90b:f300:3457:4dff:feb5:6cc0 
2a05:3880:d90b:f300::98 
fe80::3457:4dff:feb5:6cc0]
Локальные - это ^::|^fc..:|^fd..:|^fe..:
Т.е. подойдет любой адрес из 2a05:3880:d90b:f300:3457:4dff:feb5:6cc0  и 2a05:3880:d90b:f300::98
3. Выводить в лог старта ip-адреса из полей ClientConfig.PublicIp6 и ClientConfig.PublicIp4

Спасибо.

**Comment by tsynik** [comment]
added

**Comment by avengermsoft** [comment]
Спасибо!

Но есть проблема, не могу задать адрес для ipv6. Для ipv4 задается без проблем.

D:\34535>TorrServer-windows-amd64.exe --ipv6 2a05:3560:d90b:f300:e133:c4f:c842:c984 -ipv4 188.130.241.1                                                                                                            2022/01/21 00:26:48 ffprobe and avprobe not found in $PATH
=========== START ===========
TorrServer MatriX.111.OE, go1.17.6, CPU Num: 8
2022/01/21 00:26:48 Check dns OK [2a00:1450:401b:804::2004 142.250.203.132] <nil>
2022/01/21 00:26:48 Check web port 8090
2022/01/21 00:26:48 Start TorrServer
2022/01/21 00:26:48 IPs: [192.168.97.123 2a05:3560:d90b:f300:750c:5672:7785:7a94 2a05:3560:d90b:f300:e133:c4f:c842:c984 fe80::750c:5672:7785:7a94]
2022/01/21 00:26:48 Check upnp port 32000
2022/01/21 00:26:48 Set upnp port 32000
2022/01/21 00:26:48 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2022/01/21 00:26:48 PublicIp4: 188.130.241.1
2022/01/21 00:26:48 PublicIp6: 2a05:3560:d90b:f300:750c:5672:7785:7a94
2022/01/21 00:26:48 Start web server at port 8090

Посмотрите, пожалуйста.

**Comment by avengermsoft** [comment]
@tsynik Поправи пожалуйста багу с
```		
if ip4 := net.ParseIP(settings.PubIPv4); ip4.To4 != nil && !isPrivateIP(ip4)
if ip6 := net.ParseIP(settings.PubIPv6); ip6.To16 != nil && ip6.To4 == nil && !isPrivateIP(ip6)
```
на
```	
if ip4 := net.ParseIP(settings.PubIPv4); ip4.To4() != nil && !isPrivateIP(ip4)
if ip6 := net.ParseIP(settings.PubIPv6); ip6.To16() != nil && ip6.To4() == nil && !isPrivateIP(ip6)
```
