### ISSUE TITLE
Docker install failed.

### ISSUE THREAD

**Issue by aston314** [YouROK/TorrServer#141]
Unable to find image 'ghcr.io/yourok/torrserver:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/yourok/torrserver/manifests/latest": denied.

**Comment by tsynik** [comment]
> Unable to find image 'ghcr.io/yourok/torrserver:latest' locally docker: Error response from daemon: Head "https://ghcr.io/v2/yourok/torrserver/manifests/latest": denied.

Maybe it's because no release was done yet after this pr merge - https://github.com/YouROK/TorrServer/pull/132. Anyway, better report this to Alexey https://github.com/kricha

**Comment by aston314** [comment]
🔢

**Comment by mcgr0g** [comment]
Извините, что на русском. 
Похоже не создался артефакт. Это объясняет что нет манифеста к артефакту и с ним ничего нельзя сделать. 
Смотри[те]: в экшэнах нет никакого лога https://github.com/YouROK/TorrServer/actions/workflows/github-actions-docker.yml

Если немного погуглить ошибку, можно найти похожие проблемы в других репозиториях, например: https://github.com/hadolint/hadolint/issues/518
Парень поправил и у него экшены начали что то делать: https://github.com/hadolint/hadolint/actions/workflows/docker.yml
Немного пошерстив по его репозитарию можно найти сценарий экшена https://github.com/hadolint/hadolint/blob/master/.github/workflows/docker.yml
Если сравнить местным сценарием https://github.com/YouROK/TorrServer/blob/master/.github/workflows/github-actions-docker.yml, то в глаза бросается порванная лишними переносами yaml разметка.
