### ISSUE TITLE
error

### ISSUE THREAD

**Issue by terentev** [YouROK/TorrServer#147]
rutor info 851711

2022/02/13 19:54:23 [Recovery] 2022/02/13 - 19:54:23 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:221 (0x450986)
/usr/local/go/src/runtime/signal_unix.go:735 (0x450956)
/usr/src/torr/server/torr/torrent.go:268 (0xdb7e1e)
/usr/src/torr/server/web/api/upload.go:73 (0xdc560c)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x916dc1)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x916dac)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0xdc836c)
/usr/src/torr/server/web/blocker/blocker.go:21 (0xdc8359)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x92015d)
/usr/src/torr/server/log/log.go:80 (0x91fdbb)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x915c90)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x9158f8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x915431)
/usr/local/go/src/net/http/server.go:2879 (0x6c84da)
/usr/local/go/src/net/http/server.go:1930 (0x6c3b87)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0x46dd60)

**Comment by YouROK** [comment]
Тестируй на новой версии, там двигатель обновлен
