### ISSUE TITLE
External Trackers Lists

### ISSUE THREAD

**Issue by PureOcean** [YouROK/TorrServer#152]
Firstly, thank you for this project.

Could you add the external mirror trackers list support to be added to existing trackers in a Torrent?
(Like the "_Automatically update trackers list:_ ..." refetch feature in QBitTorrent.)

For example, using lists of [ngosang tracker list](https://github.com/ngosang/trackerslist) and [Trackerlist.com](https://trackerslist.com):

`TorrServer-windows-amd64.exe --ExtraTrackerList "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt"`

Or for multi list:

`TorrServer-windows-amd64.exe --ExtraTrackerList "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt" --ExtraTrackerList "https://trackerslist.com/best.txt"`

**Comment by YouROK** [comment]
tracker list released in this file, may by this help you https://github.com/YouROK/TorrServer/blob/master/server/torr/utils/torrent.go
