### ISSUE TITLE
Хотелки по работе с пользователями.

### ISSUE THREAD

**Issue by ssersh** [YouROK/TorrServer#154]
Просьба реализовать инфу по пользователям в интерфейсе. А то как то странно, пользователей с паролями можно создать кучу, а инфа по пользователем не видна нигде... Ну было бы не плохо иметь возможность, например авто отчистки базы отдельного пользователя или иметь вкладки торрентов по пользователю. Второе более актуально, чтобы не была вся инфа по всем в кучу.

**Comment by YouROK** [comment]
Слишко много переделывать, может быть будет когда нибудь
