### ISSUE TITLE
Не скармливаются некоторые хэши

### ISSUE THREAD

**Issue by Mutronics** [YouROK/TorrServer#155]
Кормлю программе исключительно хэши и за довольно большой период использования заметил, что некоторые хэши торрсервер не кушает.
Хэш добавляется и через секунду пропадает.
Если нужно, хэши могу скинуть.

**Comment by tsynik** [comment]
> Хэш добавляется и через секунду пропадает.
> Если нужно, хэши могу скинуть.

без них и говорить не о чем. торренты не добавляются при невозможности получить метаданные торрента от трекера (если заблокирован доступ к трекеру:  как пример rutor из РФ), с хешами - вопрос.

**Comment by Mutronics** [comment]
0FA99676ED485749D0B3D3289B266F6229C06291

**Comment by Mutronics** [comment]
Хотя тот же deluge его кушает хорошо

**Comment by tsynik** [comment]
> 0FA99676ED485749D0B3D3289B266F6229C06291

Не удается воспроизвести:

=========== START ===========
TorrServer MatriX.112, go1.17.7, CPU Num: 4
2022/03/13 07:31:01 UTC0 TLOG  Check dns OK [...] <nil>
2022/03/13 07:31:01 UTC0 TLOG  Check web port 8090
2022/03/13 07:31:01 UTC0 TLOG  Start TorrServer
2022/03/13 07:31:01 UTC0 TLOG  IPs: [192.168.77.102 fe80::6feb:313f:a5d6:9409 fe80::a0bb:e9ff:fe8c:487e]
2022/03/13 07:31:01 UTC0 TLOG  Check upnp port 32000
2022/03/13 07:31:01 UTC0 TLOG  Set upnp port 32000
2022/03/13 07:31:01 UTC0 TLOG  Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2022/03/13 07:31:01 UTC0 TLOG  Start web server at port 8090
2022/03/13 07:31:09 UTC0 TLOG  add torrent 0FA99676ED485749D0B3D3289B266F6229C06291
2022/03/13 07:31:17 UTC0 TLOG  Create cache for: The.Adam.Project.2022.WEB-DL.1080p.HDR.seleZen.mkv 0fa99676ed485749d0b3d3289b266f6229c06291
2022/03/13 07:31:17 UTC0 TLOG  save to db: 0fa99676ed485749d0b3d3289b266f6229c06291
2022-03-13T07:31:24+0000 unset [github.com/anacrolix/torrent.(*Client).NewAnacrolixDhtServer.func2:406]: dht server on 0.0.0.0:32000 (node id ea1ac7a346d7b35e3f6bfbede95f4918807d7de7) completed bootstrap ({NumAddrsTried:61 NumResponses:27})
```

**Comment by Mutronics** [comment]
> > 0FA99676ED485749D0B3D3289B266F6229C06291
> 
> Не удается воспроизвести:

Ну да, а deluge с этим справляется прекрасно

**Comment by Mutronics** [comment]
Ну да, а deluge с этим справляется прекрасно

**Comment by tsynik** [comment]
> Ну да, а deluge с этим справляется прекрасно

лог выше из TorrServer MatriX.112 - хеш добавлен и в вебе получены метаданные (название / размер etc)  и идет загрузка. Из БД не пропадает.
 p.s. лог из Android / arm7. Какая архитектура / ОС используется?

**Comment by Mutronics** [comment]
Windows, TorrServer x64, скину свой лог

**Comment by Mutronics** [comment]
2022/03/13 12:39:16 add torrent XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
panic: read udp4 0.0.0.0:63236: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

goroutine 434 [running]:
github.com/anacrolix/torrent/tracker/udp.(*ConnClient).reader(0xc000d5a420)
        /Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.41.0/tracker/udp/conn-client.go:42 +0x295
created by github.com/anacrolix/torrent/tracker/udp.NewConnClient
        /Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.41.0/tracker/udp/conn-client.go:102 +0x248

**Comment by tsynik** [comment]
> panic: read udp4 0.0.0.0:63236: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

похоже ошибка в windows с udp протоколом - надо б переправить в апстрим к https://github.com/anacrolix/torrent, при отключнии uTP в настройках TorrServer ошибка та же?

**Comment by Mutronics** [comment]
Крашится, у меня она службой с перезапуском после сбоя работает, поэтому я этого не замечал.

**Comment by Mutronics** [comment]
При отключенном uTP та же ошибка

**Comment by tsynik** [comment]
> При отключенном uTP та же ошибка

Может быть связано с этими issue - https://github.com/anacrolix/torrent/issues/712 https://github.com/YouROK/TorrServer/issues/153

**Comment by Mutronics** [comment]
Ну если будет время, посмотрите, я это использую в связке с kodi лежа на диване, в эти моменты приходится вставать и включать компьютер.
И еще странная особенность, это обычно происходит на одном и том же фильме с разными качествами. т.е. все или почти все качества одного фильма не воспроизводятся.

**Comment by SanteR1** [comment]
Windows 10, при запуске TorrServer спустя пару секунд, не включая никакие торренты.
=========== START ===========
TorrServer MatriX.112, go1.17.7, CPU Num: 4
2022/03/13 14:09:59 Check dns OK [142.250.74.196] <nil> 
2022/03/13 14:09:59 Check web port 8090 
2022/03/13 14:09:59 Start TorrServer 
2022/03/13 14:09:59 IPs: [192.168.1.73 fe80::48fe:c8a8:b50b:fb37] 
2022/03/13 14:09:59 Check upnp port 32000 
2022/03/13 14:09:59 Set upnp port 32000 
2022/03/13 14:09:59 Client config:  {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2022/03/13 14:09:59 Start web server at port 8090 
2022-03-13T14:10:22+0600 unset [github.com/anacrolix/torrent.(*Client).NewAnacrolixDhtServer.func2:406]: dht server on 0.0.0.0:32000 (node id fef45002de788caa0405080c13a683468d95eb08) completed bootstrap ({NumAddrsTried:55 NumResponses:25})

**Comment by tsynik** [comment]
> Windows 10, при запуске TorrServer спустя пару секунд, не включая никакие торренты.

в этом логе ошибок нет

**Comment by tsynik** [comment]
> Ну если будет время, посмотрите, я это использую в связке с kodi лежа на диване, в эти моменты приходится вставать и включать компьютер.
> И еще странная особенность, это обычно происходит на одном и том же фильме с разными качествами. т.е. все или почти все качества одного фильма не воспроизводятся.

Проверьте работу этой сборки сервера
[TorrServer-windows-amd64.exe.zip](https://github.com/YouROK/TorrServer/files/8245095/TorrServer-windows-amd64.exe.zip) - тут отменен коммит https://github.com/anacrolix/torrent/commit/aaec4dbd80100702f8a230b0a21309726caeaadb#diff-c50a2bc1fe6acbf03d37a550b2daa8d04c384e42cf9072a8d392fd9cffb35558 что не отменяет ошибки udp но паниковать сервер не будет.

**Comment by SanteR1** [comment]
@tsynik Добрый вечер, вот например магнет magnet:?xt=urn:btih:7AC1DB2B7C9670DFF9A25864158E9CE1A4374C55 ну или просто хэш из нее, добавляя через веб-интерфейс или api, консоль с TorrServer просто закрывается. Посмотрел в журнале Windows тоже ошибок не нашел. Windows 10x64, TorrServer MatriX.112, go1.17.7, CPU Num: 4
Попробовал версию из вашего поста выше, отрабатывает без ошибки

**Comment by Mutronics** [comment]
> > Ну если будет время, посмотрите, я это использую в связке с kodi лежа на диване, в эти моменты приходится вставать и включать компьютер.
> > И еще странная особенность, это обычно происходит на одном и том же фильме с разными качествами. т.е. все или почти все качества одного фильма не воспроизводятся.
> 
> Проверьте работу этой сборки сервера [TorrServer-windows-amd64.exe.zip](https://github.com/YouROK/TorrServer/files/8245095/TorrServer-windows-amd64.exe.zip) - тут отменен коммит [anacrolix/torrent@aaec4db#diff-c50a2bc1fe6acbf03d37a550b2daa8d04c384e42cf9072a8d392fd9cffb35558](https://github.com/anacrolix/torrent/commit/aaec4dbd80100702f8a230b0a21309726caeaadb#diff-c50a2bc1fe6acbf03d37a550b2daa8d04c384e42cf9072a8d392fd9cffb35558) что не отменяет ошибки udp но паниковать сервер не будет.

Спасибо, все заработало.
