### ISSUE TITLE
Argument "--torrentsdir" is not working on windows

### ISSUE THREAD

**Issue by depler** [YouROK/TorrServer#156]
Test case:
1. Create empty folder: "c:\Downloads\"
2. Run: TorrServer-windows-amd64.exe --torrentsdir "c:\Downloads\"
3. Open url "http://127.0.0.1:8090/", ensure TorrServer is working
4. Add any torrent file into "c:\Downloads\" folder

Result - empty torrent list, nothing added

**Comment by z8512** [comment]
Not working in latest ubuntu x64 docker image also

**Comment by z8512** [comment]
My guess its using ram by default. We have to select disk from web-ui settings

**Comment by tsynik** [comment]
> My guess its using ram by default. We have to select disk from web-ui settings
--torrentsdir used for adding torrents to server not to store it's data, so storage location doesn't matter.

**Comment by z8512** [comment]
Ok

**Comment by fuefbre55gr** [comment]
Still not work on windows. Or I miss something. Any idea, what may i do to get this feature working on win 10

**Comment by YouROK** [comment]
Added logs to watcher. On macOS and linux working fine
Please send logs

**Comment by tsynik** [comment]
Must be fixed with MatriX.128 release. Reopen if still an issue.
