### ISSUE TITLE
http://127.0.0.1:8090/stream/ не рабоатет API

### ISSUE THREAD

**Issue by NikDevx** [YouROK/TorrServer#158]
Здравствуйте 
Версия MatriX.112

Не работает api 
http://127.0.0.1:8090/stream

http://127.0.0.1:8090/stream/fname?link=http://127.0.0.1:9117/dl/anilibria/?jackett_apikey=sujgj60e9x1pylmvqn0d2880vb07elak&path=Q2ZESjhPdjFqTUYwQXdkQ3FFQXZOYmFONzdYVS00anRmQ3h0cTRYMTkyMWFQd0dUdjNETk9XLVZEV1BqVTFTMndQWEpMd2hhY1dRM3hRWjdSLTJXZDhGb0RLUHZnc2NrVTRHYVAtTVRHUVdPeVVXNlhobXhPei04UDVKVC1sczdOZG1mQ0Fkcnp4UURyNlJsd1VLR040Z01uRGFoSElEbE16aTFqYi14RTE0QWZfeVJsN0thR240NHMzNWJ2QXo0bmVTQzhB&file=Арифурэта%3A+Сильнейший+ремесленник+в+мире+2+_+Arifureta+Shokugyou+de+Sekai+Saikyou+2nd+Season+%5BWEBRip+1080p+HEVC%5D+-+1-12&save&title=Test

Получаю 
This page isn’t working
127.0.0.1 is currently unable to handle this request.
HTTP ERROR 500

**Comment by tommiv** [comment]
@NikDevx это у вас Jackett на 127.0.0.1:9117 же? Как решили проблему? Столкнулся с тем же самым. (Уточню на всякий: я пробовал urlencode на адресе торрента из Jackett, но это не помогло)
