### ISSUE TITLE
is it possible to group torrents or adding multiple torrent at once?

### ISSUE THREAD

**Issue by kirgizmustafa17** [YouROK/TorrServer#160]
I want to add all episodes of a tv series as a group or folder. But serie is still airing so there is season pack for it. And if you add the torrents one by one, we'll see it as if it's different series. I hope you understand what I mean.

https://i.imgur.com/HnEsHuW.png

**Comment by YouROK** [comment]
This is not problem of Torrserve, use program with group of episodes and etc
