### ISSUE TITLE
DLNA Server & Home Assistant

### ISSUE THREAD

**Issue by avbor** [YouROK/TorrServer#162]
С недавних пор у системы управления умным домом Home Assistant появилась интеграция с DLNA серверами, что достаточно удобно - она позволяет запускать медиа из DLNA как из интерфейса HA так и с помощью автоматизаций на поддерживаемых проигрывателях (всякие хромкасты и прочее, их множество).
Но к сожалению, с TorrServer'ом она не работает, в issue компонента автор отписался что не может поправить это со своей стороны.
Есть ли шанс исправить проблему со стороны TorrServer'а?
Ссылка на ишью - https://github.com/home-assistant/core/issues/69803#issuecomment-1103911579

**Comment by tsynik** [comment]
TorrServer использует библиотеку [anacrolix/dms](https://github.com/anacrolix/dms) для DLNA. Проверьте работу Home Assistant с ней и адресуйте запрос туда, если поведние аналогично.

**Comment by pbannykh** [comment]
Тоже возникает такая ошибка, чуть-чуть посмотрел.

Кажется не в библиотечке дело. Вот ошибка, которая возникает в HA:
`Server failure: UpnpActionResponseError('Error during async_call(), status: 500, upnp error: 501 (meta not found)')`
 
 Глянул по коду, вот она
 https://github.com/YouROK/TorrServer/blob/master/server/dlna/dlna.go#L136
 
 Ну и связана кажется с тем что тут
 https://github.com/YouROK/TorrServer/blob/master/server/dlna/list.go#L93
 выше не нашелся torr и вернули nil
 
 Дальше не смотрел.

**Comment by eboboshka** [comment]
@tsynik откроете issue?
