### ISSUE TITLE
MSX Plugin

### ISSUE THREAD

**Issue by damiva** [YouROK/TorrServer#163]
I'm writing MSX plugin for the TorrServer, it's pluses:
1. You do not need msx api into ypur program (it uses ypur core API "/torrents" & "/viewed"), just embed the html file into your service.
2. It uses the most powerful video player and features, depending on the TV platform.
3. It has two interface languages: English & Russian.
4. and some additional useful features...

Is it interesting for you to use it?

**Comment by tsynik** [comment]
> Is it interesting for you to use it?

TorrServer already have MSX support bundled - https://github.com/YouROK/TorrServer/tree/master/server/web/msx. Feel free to improve it.

**Comment by damiva** [comment]
2 qustions:
1. As I've got, you would like to embed all MSX tools instead of using it from the internet, right?
2. How to change the code, you could include it in the next release? I'm new on github?

**Comment by damiva** [comment]
?

**Comment by tsynik** [comment]
Just PR yourth MSX support improvements to review.
