### ISSUE TITLE
Не работает автоудаление кеша

### ISSUE THREAD

**Issue by Joy096** [YouROK/TorrServer#166]
Заметил следующую проблему! В настройках сервера отключаю тумблер "Очищать кеш при отключении торрента", чтобы кеш очищался при самом удалении торрента. При воспроизведении фильма выбираю "Воспроизвести без добавления" или если с телефона то "Играть". После окончания просмотра сам торрент через некоторое время автоматически удаляется, а кеш остается! Приходится удалять его на сервере вручную...

Из пожеланий: ОЧЕНЬ была бы полезной функция "удаленной загрузки" фильма в кеш, к примеру - я добавляю торрент, раздающих у него мало, поэтому скорости для стрима не хватает, и чтобы я мог его комфортно и без задержек вечерком глянуть он в течении какого то времени загружается в кеш. 
Ну и соответственно после просмотра я удаляю  торрент, а вместе с ним удаляется и кеш (при этом если включен тумблер "Очищать кеш при отключении торрента", то на кеш "удаленной загрузки" это не влияет).

Спасибо! Успехов в развитии проекта!

**Comment by YouROK** [comment]
Это опция и сделана для того чтобы можно было загрузить кэш для последующего просмотра. Только нужно использовать кэш на диск, с памятью это не работает

**Comment by Joy096** [comment]
Торрент сервер установлен на виртуальной машине Oracle, архитектура процессора arm64.




> Из пожеланий: ОЧЕНЬ была бы полезной функция "удаленной загрузки" фильма в кеш, к примеру - я добавляю торрент, раздающих у него мало, поэтому скорости для стрима не хватает, и чтобы я мог его комфортно и без задержек вечерком глянуть он в течении какого то времени загружается в кеш.
> Ну и соответственно после просмотра я удаляю торрент, а вместе с ним удаляется и кеш (при этом если включен тумблер "Очищать кеш при отключении торрента", то на кеш "удаленной загрузки" это не влияет).

Если Вы имеете ввиду функция "Предзагрузка", то она не работает. Нажимаю и ничего не происходит. В настройках хранение кеша стоит ПЗУ/Накопитель.

> Заметил следующую проблему! В настройках сервера отключаю тумблер "Очищать кеш при отключении торрента", чтобы кеш очищался при самом удалении торрента. При воспроизведении фильма выбираю "Воспроизвести без добавления" или если с телефона то "Играть". После окончания просмотра сам торрент через некоторое время автоматически удаляется, а кеш остается! Приходится удалять его на сервере вручную...

Также как и не работает автоудаление кеша.. через LAMPA фильм запустил, посмотрел, он через время автоматически удалился, а кеш остался... Тумблер "Очищать кеш при отключении торрента" отключен...

**Comment by Joy096** [comment]
> Заметил следующую проблему! В настройках сервера отключаю тумблер "Очищать кеш при отключении торрента", чтобы кеш очищался при самом удалении торрента. При воспроизведении фильма выбираю "Воспроизвести без добавления" или если с телефона то "Играть". После окончания просмотра сам торрент через некоторое время автоматически удаляется, а кеш остается! Приходится удалять его на сервере вручную...

Также как и не работает автоудаление кеша.. через LAMPA фильм запустил, посмотрел, он через время автоматически удалился, а кеш остался... Тумблер "Очищать кеш при отключении торрента" отключен...

**Comment by tsynik** [comment]
> Также как и не работает автоудаление кеша.. через LAMPA фильм запустил, посмотрел, он через время автоматически удалился, а кеш остался... Тумблер "Очищать кеш при отключении торрента" отключен...

При отключенном тумблере и не будет кеш удаляться, для удаления кеша после отключения торрента тумблер должен быть _включен_, иначе кеш удаляется при _удалении_ торрента из базы данных TorrServe - кнопка Удалить в вебе.
