### ISSUE TITLE
Docker pull latest is 112 and real latest is 114

### ISSUE THREAD

**Issue by Arelav** [YouROK/TorrServer#167]
`docker pull ghcr.io/yourok/torrserver:latest` get 112 instead of the latest 114
https://github.com/yourok/TorrServer/pkgs/container/torrserver
Here I can see 112 as well.
The releases page and Torrserve client say the latest is 114 and suggests to update

**Comment by tsynik** [comment]
probably fixed, last build 115

**Comment by Arelav** [comment]
Yes. It's fixed. Thank you.

**Comment by sK1LLer** [comment]
And again, Docker version lags a little bit behind. Can you please update?
Docker is 117 and release is 118.
