### ISSUE TITLE
DLNA Blocklist

### ISSUE THREAD

**Issue by mycek91** [YouROK/TorrServer#168]
Hello, can you add a function to block specific clients from accessing dlna server.
Something Like a LAN IP whitelist or block list.
Thank you!

**Comment by YouROK** [comment]
We use https://github.com/anacrolix/dms

**Comment by mycek91** [comment]
Thanks for the answer.
I don't know the way to start torrserver with custom parameters on androidTV.
Can you add -allowedIps as configurable parameter through Web Interface?
Like -friendlyName in the recent version.
Again thanks and have a nice day.
