### ISSUE TITLE
TorrServer over Interface/IP Address for Proxy

### ISSUE THREAD

**Issue by asheroto** [YouROK/TorrServer#169]
Hi there,

I want to run TorrServer over a SOCKS5 proxy. I planned on using proxychains but it doesn't seem to work with TorrServer.

Is there a way I can tell TorrServer to use a specific interface or IP address of an adapter on my machine?  That way I could force traffic through a VPN-tunnel or something.

And/or is there a way I can have TorrServer use a SOCKS5 proxy?

Thanks for your work on this, program rocks!

**Comment by asheroto** [comment]
Looks like I can set an IP using `--ipv4 IPV4` which might help.

What do you recommend for a setup like this, where a proxy is desired?

**Comment by asheroto** [comment]
When I use the IPv4 arg, it still connects over my other IPs. Am I doing something wrong?

```
# ./TorrServer-linux-amd64 --ipv4 10.66.66.1
2022/05/24 23:45:39 ffprobe and avprobe not found in $PATH
=========== START ===========
TorrServer MatriX.114, go1.18.1, CPU Num: 6
2022/05/24 23:45:39 Check dns OK [REDACTED] <nil>
2022/05/24 23:45:39 Check web port 8090
2022/05/24 23:45:39 Start TorrServer
2022/05/24 23:45:39 IPs: [10.66.66.1 172.17.0.1 172.23.0.1 192.168.0.134]
2022/05/24 23:45:39 Check upnp port 32000
2022/05/24 23:45:39 Set upnp port 32000
2022/05/24 23:45:39 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2022/05/24 23:45:39 Start web server at port 8090
```

**Comment by tsynik** [comment]
> Looks like I can set an IP using `--ipv4 IPV4` which might help.

This option not to bind to interface but to report public IP to bittorrent network / peers. Currently you can restrict access to server by enabling authorization with -a param only. And use firewall rules too.

**Comment by asheroto** [comment]
Hi,

Thanks. I'm not looking to restrict access really, my goal is to use TorrServer on another interface. Right now it's sending/receiving traffic on all interfaces, can I force it to use one interface, or specifically, use a SOCKS5 proxy for torrent traffic?

In qBittorrent it's this...

![image](https://user-images.githubusercontent.com/49938263/170183643-e8780537-e390-42cf-aec8-a3c3a7462c08.png)

**Comment by asheroto** [comment]
Or could you kindly tell me where in the code I can specify the interface IP address for TorrServer to download torrents using? That way I can build it myself.

Thank you

**Comment by tsynik** [comment]
> Or could you kindly tell me where in the code I can specify the interface IP address for TorrServer to download torrents using? That way I can build it myself.

Look at SetListenAddr function https://github.com/anacrolix/torrent/blob/ed1fe91dd2d11213afdb6c8ab49b3e4a12fa41e2/config.go#L161-L169 which can be used near this block in client config: https://github.com/YouROK/TorrServer/blob/266fe0637fcd03d6aefa6a2ff28cdef9a82867ba/server/torr/btserver.go#L123-L141

Here is example - https://github.com/anacrolix/confluence/blob/3c7a0c445dada1b5f9bdeef8ac49967e2c169688/main.go#L128-L130

**Comment by tsynik** [comment]
> Or could you kindly tell me where in the code I can specify the interface IP address for TorrServer to download torrents using? That way I can build it myself.

You can define required interface IP by new startup option --torrentaddr 10.66.66.1:1337 etc with 115 release https://github.com/YouROK/TorrServer/releases/tag/MatriX.115

**Comment by asheroto** [comment]
Thank you.

Will you consider adding in support for a proxy?

Such as...

```
--proxytype SOCKS5 --proxyserver 192.168.0.99 --proxyusername user --proxypassword password
```

Thanks :-)

**Comment by tsynik** [comment]
> Will you consider adding in support for a proxy?

probably no as socks implementation in go not trivial for me, bu you can make a PR ;-) Or you can configure nginx for that task.

**Comment by asheroto** [comment]
Okay, sounds good, thank you. 😊

**Comment by avengermsoft** [comment]
> > Will you consider adding in support for a proxy?
> 
> probably no as socks implementation in go not trivial for me, bu you can make a PR ;-) Or you can configure nginx for that task.

Use iptables and `-m owner` to redirect traffic
