### ISSUE TITLE
Сотрудничество

### ISSUE THREAD

**Issue by ghost** [YouROK/TorrServer#17]
@YouROK 
Я в GitHub новичок, как можно с тобой связаться в личке?
Я написал новый RemoteFork (масштабируемый) для ForkPlayer, тоже на Go.
У меня есть идея встроить в него TorrServer (ну или наоборот), что думаешь об этом? Мне кажется так будет удобней для пользователя ForkPlayer (и меньше ресурсов).

**Comment by YouROK** [comment]
https://t.me/TorrServe
