### ISSUE TITLE
Periodic CPU Usage

### ISSUE THREAD

**Issue by Jarikk** [YouROK/TorrServer#179]
I have the TorrServer MatriX.117 running on a docker container. Nobody is using the server at the moment. But periodically, ~ every 2 seconds, I notice that something inside the torrserver process starts to work and uses CPU up to 15%. Look at the picture below:

![image](https://user-images.githubusercontent.com/805740/181605937-c4c9e6d4-c056-495c-95c2-66136eaad420.png)

After a quick researching I've found, that when I cleared the torrents database inside web UI - this behavior disappeared.

![image](https://user-images.githubusercontent.com/805740/181605990-0845fd5c-51d0-4ce0-b935-1408a8ef2159.png)

There were ~ 150 torrent files in the database (I have the backup). It is very useful to have a history of the torrents, saved times positions and viewed series. But, is that count of torrents huge enough to increase CPU usage on the server every 2 seconds? Can we reduce or optimize  this periodic reload(refresh or whatever) in idle?

**Comment by tsynik** [comment]
> Can we reduce or optimize this periodic reload(refresh or whatever) in idle?
There are periodic go routines which do memory cleaning of inactive torrents, check watched dirs etc. also web need torrent stats to show info to user. If you'll find which routine causes this you can optimize it. And 10 percents is no much of use for torrent server.

**Comment by Jarikk** [comment]
OK. It seems that the issue is not directly caused by the TorrServer itself. I have 2 Android TV boxes with installed TorrServer Clients 117 on them (without local server). There are no any activity on the TorrServer if both tv boxes are offline. If I start any tv box and open the TorrServer client - it will start doing periodic requests to the server. These requests do not stop after closing the client. I can't see what requests it does, because there are no any information on the server (even with the option "Debug Server Log" enabled).
I do not use TorrServer channel on the Home screen on AndroidTV so I do not expect that TorrServer client will continue making requests to the server in background. I would not say that 10-15% CPU usage every couple of seconds on the server is something, that can be ignored. In my point of view, this is a waste of resources. So, just thoughts:
 - Is it possible to cache the latest results for clients if there are no active torrents at the moment or torrent list has not changed since the latest request?
 - Why the TorrServer client is producing a lot of activity in background if we do not use it? Is it possible to stop this activity if the client is minimized and not used at the Home screen as a channel?
