### ISSUE TITLE
Webserver error then adding .torrent file

### ISSUE THREAD

**Issue by T-Troll** [YouROK/TorrServer#18]
TorrServ 1.1.77, build for armv7.
System - OpenWRT-based router.
Server starts well, but any attempt to add torrent from android client provide error:
``Error upload torrent bencode: syntax error (offset: 0): unknown value type '\n'``
``Web server error: code=400, message=bencode: syntax error (offset: 0): unknown value type '\n' /torrent/upload``
Hardcoded path?

**Comment by YouROK** [comment]
Please give me log if actual issue

**Comment by T-Troll** [comment]
Ok, do it today.
BTW, it's only happened if torrent added from Android client, adding from web UI are ok.
