### ISSUE TITLE
Скачивание и хранение целиком файлов торрента.

### ISSUE THREAD

**Issue by anton-gs2** [YouROK/TorrServer#182]
Думаю, полезно было бы иметь возможность использовать TorrServer как полноценный торрент-клиент. С возможностью скачивания торрентов целиком. Например, настройки "Скачивать торрент целиком", "срок хранения скачанного", "Путь хранения файлов", "Максимальный размер хранилища". 
Это, соответственно, для тех, кто ставит на устройства с большим хранилищем.
Фитча даст поддержку торрент-сети, сидов будет больше.

**Comment by luckydevil13** [comment]
+1 для насов на arm тоже бы пригодилось

**Comment by inlarin** [comment]
> Думаю, полезно было бы иметь возможность использовать TorrServer как полноценный торрент-клиент. С возможностью скачивания торрентов целиком. Например, настройки "Скачивать торрент целиком", "срок хранения скачанного", "Путь хранения файлов", "Максимальный размер хранилища". Это, соответственно, для тех, кто ставит на устройства с большим хранилищем. Фитча даст поддержку торрент-сети, сидов будет больше.

Так и поставьте полноценный торрент-клиент на ваш сервер. Torrserver живет либо на android TV, где места как бы нет, он выключается время от времени. Либо оно живет в докере на дохлом VPS, где места хранить раздачи опять же нет. У меня vps с 5 гигами хранилища, как вы представляете логику хранения раздач?

**Comment by anton-gs2** [comment]
> Так и поставьте полноценный торрент-клиент на ваш сервер.

Ну, у меня TorrServer на моем NAS живет, т.к. на телике подтупливал. Там же (на NAS) живет и Transmission. А кино в основном смотрю через Lampa и, соответственно, TorrServer. После того как начал пользоваться для просмотра Lampa заходить и искать раздачи на торрент-трекерах стало лень.

Имеем: Чтобы поддерживать раздачи нужно закидывать торрент в Transmission отдельно, перед этим зайти на трекер, найти раздачу. 
Можно, конечно автоматизировать, скрипт написать по анализу логов TorrServer или свой парсер торрент-трекеров развернуть еще.
Но лучше, считаю, иметь в одном приложении. К тому, что сидов на раздачах будет больше, плюс после скачивания файлов целиком они будут доступны оффлайн и если на раздаче вдруг сидов мало и скорость скачивания низкая не нужно идти заражать на скачивание отдельный торрент-клиент, а только вернуться к просмотру чуть позже .

**Comment by alexunderboots** [comment]
Выбрать торрент — отправить — trancedroid — и скачка стартует на удалённой  торрент-качалке

**Comment by anton-gs2** [comment]
> Выбрать торрент — отправить — trancedroid — и скачка стартует на удалённой торрент-качалке

Это в каком месте в каком приложении на Android TV такая менюшка есть?

**Comment by alexunderboots** [comment]
> > Выбрать торрент — отправить — trancedroid — и скачка стартует на удалённой торрент-качалке
> 
> Это в каком месте в каком приложении на Android TV такая менюшка есть?

Сделал на смартфоне, на котором установлен Torrserv-client и Transdroid. Transdroid настроен на подключение к qbittorrent на NAS

**Comment by luckydevil13** [comment]
@alexunderboots , @inlarin идея в том что бы использовать для скачки torrserv . У меня на NAS (armv5) нету актуального transmission/qbittorent но есть torrserv

**Comment by anton-gs2** [comment]
> Сделал на смартфоне, на котором установлен Torrserv-client и Transdroid. Transdroid настроен на подключение к qbittorrent на NAS

Ну, т.е. лишние телодвижения, еще и на другом устройстве.  Из-за которых сидов не прибавится )

**Comment by anton-gs2** [comment]
Ну, хотя бы добавить автоматическое складывание файлов.torrent и magnet-ссылок в определенное место для простой интеграции с полноценным клиентом. Хотя это не решит проблемы управления местом.

**Comment by inlarin** [comment]
@luckydevil13, @anton-gs2 - тут вот в чем дело, есть такой принцип KISS. Инструмент должен выполнять одну задачу и выполнять ее хорошо, что собственно сейчас и имеем. Torrserver прекрасно работает с NUM и Lampa, работает на разных платформах, даже для лентяев типа меня собран docker образ. Причем мы имеем несколько хороших продуктов, если я правильно понял - разработчик один и тот же(torrserver, torrserve, NUM). Храни его ктулху, что он не стал это превращать в мегакомбайн все в одном)))
Если из torrserver начать делать полноценный торрент клиент, то точно ли он будет выполнять хорошо свою основную функцию?
Могу плюсануть только предложение @anton-gs2 - действительно в некоторых кейсах было бы удобно ловить torrent файл в определенной директории, сейчас я пошарился по работающему docker образу и не нашел директории с активной закачкой, только строчка в логе вида "2022-08-20T08:08:58+0000 TSM add torrent magnet:?xt=urn:btih:7868CBE6AB". Может не там ищу?

**Comment by babinskiy** [comment]
> Могу плюсануть только предложение @anton-gs2 - действительно в некоторых кейсах было бы удобно ловить torrent файл в определенной директории, сейчас я пош...

Тоже голосую хотябы за такой вариант. так можно было бы эту папку добавить как источник для того же rtorrent, а сам rtorrent, в свою очередь, через локальный ретрекер шарить для TorrServer. 
А rtorrent уже будет решать задачи и по поддержке раздач и как локальный кеш, если скорости пиров не хватает чтобы онлайн смотреть

Не уверен правда что многие смогут освоить настройку такой конфигурации, но если подготовить где-нить подробную инструкцию  - многие ставяшие себе локальный медиасервер будут использовать такую схему

**Comment by crzsotona** [comment]
> Но лучше, считаю, иметь в одном приложении. К тому, что сидов на раздачах будет больше, плюс после скачивания файлов целиком они будут доступны оффлайн и если на раздаче вдруг сидов мало и скорость скачивания низкая не нужно идти заражать на скачивание отдельный торрент-клиент, а только вернуться к просмотру чуть позже .

BiglyBT, и торрент-клиент (с очень широкими возможностями), и медиа-сервер DLNA.

**Comment by zeddius1983** [comment]
Будучи владельцем домашнего сервера с большим количеством свободного места я решил эту проблему с сохранением и скачкой торрентов следующим образом:

1.  Выставил кэш на диск 80GB (пока должно хватить для любого блю рипа).
2.  Включаем переключатель очистка кэша только при удалении торрента.
3.  Выставляем буффер предзагрузки в 0%.

Теперь при просмотре фильма весь фильм сохранится в кэше для возможного его повторного просмотра другим членом семьи.

Но тут есть проблемы. Первая из за баги дисковый кэш удаляется при рестарте сервера частично или полностью, как повезет. Вторая нельзя предзагружать торренты, что было бы полезно на раздачах с малым количеством пиров.

Обе проблемы я решил в своем форке. Но так как не являюсь go lang программистом, то довольно корявенько, но вроде работает.

**Comment by tsynik** [comment]
Для загрузки торентов используйте клиент для этого предназначенный

**Comment by holms** [comment]
> Для загрузки торентов используйте клиент для этого предназначенный

я вообще тоже согласен что нужен отдельный клиент, вот только чето лампа мне не дает воспользоваться отдельным клинетом :( Ну это конечно вопросы не к torrserver, а к лампе. Если кто знает как в num или lampa наставить чтобы использовал transmission а не сразу открывал torrserver был бы благодарен. 

В 4к смотреть онлайн это вообще нереально или хотя бы предоставьте возможность скачать 20% файла у меня никакого буфера не хватает, а на перемотке в kodi  вообще ломается torrserver на miboxTV и все... и че делать?

**Comment by Serjdud** [comment]
Поддерживаю комментарий выше

**Comment by werru** [comment]
Отмечено как "закрыто". Но в чём проблема сделать такой точно восстребованный функционал не ясно. Приходится каждый раз после добавление торрента через телек заходить в вебинтерфейс и жать кнопку "предзагрузка" (предварительно делав кэш 100 гб).

**Comment by holms** [comment]
Понять бы кто тут мейнтэнер деньги нужны или что :)? Я бы задонатил.

**Comment by Jipok** [comment]
Я для этой цели перешёл на https://github.com/distribyted/distribyted

**Comment by Danseries** [comment]
Можно же из скаченного на Тсервер торрента магнет ссылку выдрать и в свой торрент вставить или dw station

**Comment by GrechishkinNikolay** [comment]
Это также помогло бы в случае, когда скорость скачивания позволяет начинать смотреть фильм лишь тогда, когда 75% всего фильма скачено(или половина, если, к примеру, скорость скачивания в 2 раза ниже битрейта).Ты не захочешь ждать загрузки 30-75 Гигибайт часов 5, наблюдая вот это окошко со статусом заполнения буфера. Хотелось бы возможности скачивания в фоне

**Comment by babinskiy** [comment]
Я для таких ситуаций просто рядом с TorrServer поднял трансмишн и герберу, а на телевизор поставил клиент для трансмишна, и тепер в NUM я могу торрент отправить либо торсерву и сразу смотреть,  либо трансмишну, и смотреть позже, когда скачается, через герберу

**Comment by Danseries** [comment]
> Я для таких ситуаций просто рядом с TorrServer поднял трансмишн и герберу, а на телевизор поставил клиент для трансмишна, и тепер в NUM я могу торрент отправить либо торсерву и сразу смотреть, либо трансмишну, и смотреть позже, когда скачается, через герберу

Трансмисион знаю, а что такое "гербера"? Для lampa такой вариант подойдёт?

**Comment by babinskiy** [comment]
[Gerbera](https://github.com/gerbera/gerbera/) - DLNA/UPnP сервер, он не обязателен, скачанное можно шарить и по SMB.
Kodi, например, умеет в SMB
. 
Я не знаю как Lampa открывает торренты. Если умеет получить ссылку на торент и передать ее системе - то в системе можна будет выбрать какой программой ее открывать, клиентом трансмишна или Torrserva

**Comment by Danseries** [comment]
> [Gerbera](https://github.com/gerbera/gerbera/) - DLNA/UPnP сервер, он не обязателен, скачанное можно шарить и по SMB. Kodi, например, умеет в SMB . Я не знаю как Lampa открывает торренты. Если умеет получить ссылку на торент и передать ее системе - то в системе можна будет выбрать какой программой ее открывать, клиентом трансмишна или Torrserva

Попробую, для dnla юзаю jellyfin, а вот идея рядом трансмисмию поднять - интересно. Возможно на NUM перейду)) в общем спасибо, хоть будет, чем в выходные заняться))

**Comment by GrechishkinNikolay** [comment]
> Я для таких ситуаций просто рядом с TorrServer поднял трансмишн и герберу, а на телевизор поставил клиент для трансмишна, и тепер в NUM я могу торрент отправить либо торсерву и сразу смотреть, либо трансмишну, и смотреть позже, когда скачается, через герберу

Смотрю эта история на Ubuntu, а есть что-нибудь на ATV? Допустим чтобы к приставке SSD прицепить и что б на ней крутилось?

Кстати смотрю тут можно-таки запускать предзагрузку в фоне, есть один способ) Можно через веб-интерфейс зайти в список заархивированных торрентов, и по сути просто нажать details -> actions -> preload. Но теперь следующий вопрос - как заставить torrServe "видеть" внешний носитель аля SSD? Мои ТВ и приставка не распалагают таким больший количеством встроенной памяти, как, думаю, у многих.

**Comment by Dreyk007** [comment]
Поддерживаю реализацию данного функционала. Иногда хочется посмотреть что-то, где на раздаче маленькое кол-во сидов и не успевает подгружаться видео. На приставке с подключенным SSD памяти неограниченно практически. LAMPA не подружится номальном с каким-то сторонним торрент клиентом (на сколько я могу судить).

**Comment by xstaford** [comment]
Сделайте пожалуйста возможность добавление локального пира, 
Во превых огромное Вам спасибо за ваш продукт!
Бывают торенты с медленной раздачей, есть qbittorrent, Есть понимания что Вы (Разроботчики) не хотите смешивать одно с другим и на это Ваше право!!!
Если бы была возможность устнавить местный пир что бы торрсерв проверял есть ли в раздаче такойто торент то проблема с медленными торентами была бы решена.  попался медленный, отправил в кубит, подождал, запустил  и торрсерв уже подкачивает с кубита с норм скоростью.
И тогда торрсерв был бы единым источником видео-торрентов.

P.S. Откровенно говоря не понимаю почему это не происходит автоматом, я вижу что мой кубит раздает кому угодно но только не локальному торрсерверу.
