### ISSUE TITLE
TorrServer consumes CPU constantly on Windows 10 x64 after torrent playback (TorrServer постоянно потребляет CPU на Windows 10 x64 после просмотра торрента) (TorrServer MatriX.117, go1.18.3))

### ISSUE THREAD

**Issue by riffmasterv7** [YouROK/TorrServer#183]
On Windows 10 x64 system, after a playback of a video on a client device, TorrServer continues consuming CPU in idle state.

На системе Windows 10 x64, после воспроизведения видео на устройстве клиента, TorrServer начинает потреблять CPU в простое.

TorrServer MatriX.117, go1.18.3.

![image](https://user-images.githubusercontent.com/15357352/188316719-1d53d2b8-b99e-466b-8597-b5511ed2b7ea.png)

PS C:\TorrServe> .\TorrServer-windows-amd64.exe -u
2022/09/03 12:36:44 ffprobe and avprobe not found in $PATH
=========== START ===========
TorrServer MatriX.117, go1.18.3, CPU Num: 4
2022/09/03 12:36:44 Check dns OK [...] <nil>
2022/09/03 12:36:44 Check web port 8090
2022/09/03 12:36:44 Start TorrServer
2022/09/03 12:36:44 Local IPs: [...]
2022/09/03 12:36:44 Check listen port 32000
2022/09/03 12:36:44 Set listen port 32000
2022/09/03 12:36:44 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2022/09/03 12:36:44 PublicIp4: 78.26.130.42
2022/09/03 12:36:44 Start web server at port 8090
...
2022/09/03 22:58:30 Preload: 1448368c8956088f8a885a10c8f81189a29db9c2 32.45MB/32.00MB Speed:100.89KB Peers:[1]1/19
2022/09/03 22:58:31 Preload: 1448368c8956088f8a885a10c8f81189a29db9c2 32.75MB/32.00MB Speed:312.97KB Peers:[1]1/19
2022/09/04 01:30:19 New torrent 717f3b3128d233784633187ca29fee07fcb251ef
2022/09/04 01:35:19 Torrent close by timeout 717f3b3128d233784633187ca29fee07fcb251ef
2022/09/04 01:42:51 Torrent close by timeout 1448368c8956088f8a885a10c8f81189a29db9c2
2022/09/04 01:42:51 Close cache for: 1448368c8956088f8a885a10c8f81189a29db9c2
2022/09/04 05:39:15 New torrent 1448368c8956088f8a885a10c8f81189a29db9c2
2022/09/04 05:39:17 Create cache for: PAW.Patrol.The.Movie.2021.BDRip.AVC.Rip.by.HardwareMining.R.G.Generalfilm.mkv 1448368c8956088f8a885a10c8f81189a29db9c2
2022/09/04 06:34:10 Torrent close by timeout 1448368c8956088f8a885a10c8f81189a29db9c2
2022/09/04 06:34:10 Close cache for: 1448368c8956088f8a885a10c8f81189a29db9c2

**Comment by tsynik** [comment]
Отключение mTP в настройках сервера может исправить ситуацию.

**Comment by aIexus** [comment]
I have something like that but on Raspberry Pi 4 - no media played but CPU usage is about 15-20% all the time:
![image](https://user-images.githubusercontent.com/96982465/206998804-5be7db26-98b9-4164-9c80-5143f7ba3d97.png)

```● torrserver.service - torrserver
     Loaded: loaded (/etc/systemd/system/torrserver.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-12-11 15:49:09 EET; 18h ago
   Main PID: 557 (TorrServer-linu)
      Tasks: 8 (limit: 4915)
     CGroup: /system.slice/torrserver.service
             └─557 /opt/torrserver/TorrServer-linux-arm7 --p 8090

дек 11 23:07:56 raspberrypi TorrServer-linux-arm7[557]: 2022/12/11 23:07:56 Torrent close by timeout c87e4a6484b9e370e151d9c3f3da89100b7486e9
дек 11 23:07:56 raspberrypi TorrServer-linux-arm7[557]: 2022/12/11 23:07:56 Close cache for: c87e4a6484b9e370e151d9c3f3da89100b7486e9
дек 12 10:33:24 raspberrypi TorrServer-linux-arm7[557]: 2022/12/12 10:33:24 drop all torrents
дек 12 10:33:25 raspberrypi TorrServer-linux-arm7[557]: 2022/12/12 10:33:25 disconect
дек 12 10:33:25 raspberrypi TorrServer-linux-arm7[557]: 2022/12/12 10:33:25 connect
дек 12 10:33:25 raspberrypi TorrServer-linux-arm7[557]: 2022/12/12 10:33:25 Check listen port 32000
дек 12 10:33:25 raspberrypi TorrServer-linux-arm7[557]: 2022/12/12 10:33:25 Set listen port 32000
дек 12 10:33:25 raspberrypi TorrServer-linux-arm7[557]: 2022/12/12 10:33:25 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt"::false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
дек 12 10:33:25 raspberrypi TorrServer-linux-arm7[557]: 2022/12/12 10:33:25 PublicIp4: 46.98.189.169
дек 12 10:33:26 raspberrypi TorrServer-linux-arm7[557]: 2022/12/12 10:33:26 end set settings

```
It started to reproduce from Dec/10 after 19:28 (Kyiv), version 1.118 installed on Sep/22

**Comment by aIexus** [comment]
I don't know why - but problem is finished to reproduce yesterday....

**Comment by randaller** [comment]
Да, есть такая проблема, сервер на Windows 10 x64, отключение μTP в настройках сервера помогает.
Но, как следствие, в kodi с плагином rutracker пропадает отметка просмотренности серии, и перестаёт работать автопереход на следующую серию в раздаче.

**Comment by RomanLT** [comment]
Испытываю те же проблемы на Windows Server, мой Ryzen 5 2600 греется просто так.
Не хотелось бы терять функциональность и отключать mTP. Возможно ли решить эту проблему без отключения? Возможно в будущих версиях?
Спасибо!

**Comment by dasnolojy** [comment]
I, too, faced with the problem of CPU load at idle (TorrServer MatriX.120)

**Comment by randaller** [comment]
Да, проблема сохраняется в 1.20, похоже, что горутины, примерно по количеству сидеров торрента, что-то делают после отключения клиента коди.
![image](https://user-images.githubusercontent.com/22396871/217472336-e32862b2-5bae-4105-9ca2-7081c76d5c2d.png)

**Comment by randaller** [comment]
На тв-боксе на ARM такое же поведение у сервера 1.20, а процессор-то слабенький, в плеере проявляется как периодическое подлагивание картинки раз в несколько секунд.

**Comment by cerbcrowler** [comment]
на Dell 5050 x64 точно такая же история, в простое начинает грузить cpu до 40%, почти сразу после старта torrserver'a

**Comment by priZrak7495** [comment]
Ubuntu 18.04. Такая же история. В простое жрет процессор от 2 до 6%.
Включен только TCP протокол.
Что может сказать товарищ разработчик?

**Comment by tsynik** [comment]
> Ubuntu 18.04. Такая же история. В простое жрет процессор от 2 до 6%.
> Включен только TCP протокол.
> Что может сказать товарищ разработчик?

что это нормально

**Comment by RomanLT** [comment]
> Испытываю те же проблемы на Windows Server, мой Ryzen 5 2600 греется просто так. Не хотелось бы терять функциональность и отключать mTP. Возможно ли решить эту проблему без отключения? Возможно в будущих версиях? Спасибо!

К сожалению, с версией 120 ничего не изменилось, всё те же 15-17% в простое 
![image](https://user-images.githubusercontent.com/50948783/225687756-81d9f11e-cd60-4208-bb91-54d2b71ca8a3.png)

**Comment by RomanLT** [comment]
С версией 121 ситуация аналогичная: 15-20% CPU в простое.
Кажется, issue #183 закрыт преждевременно.

**Comment by TommyTon** [comment]
> С версией 121 ситуация аналогичная: 15-20% CPU в простое. Кажется, issue #183 закрыт преждевременно.

Пишут же,
Отключение mTP в настройках сервера может исправить ситуацию.
Мне помогло. Хотя там в настройках комментарий даже указан, что рекомендуют отключить в windows

**Comment by randaller** [comment]
Отключение μTP приводит к тому, что торрсервер, который работает в качестве торрент-клиента, теперь сможет подключиться только к тем сидам по tcp, у которых есть внешний белый ip, если сидов 500, то это неважно, а вот если у раздачи 5-10-20 сидов, то с белым ip может не оказаться ни одного, и всё, раздачу будет не скачать.

Проблема не в торрсервере, "проблема", точнее фича, в go библиотеке торрентов, но увы, дела всё ещё обстоят вот так.

Я решил вопрос поднятием торрсервера в докере на микротике без кулеров, но честно говоря, мне было бы удобнее крутить торрсервер на мощном виндовом сервере, но из-за взвываний вентиляторов пришлось от этого отказаться.

**Comment by TommyTon** [comment]
С трудностями пока не сталкивался. Стоит компик на n200, в котором homeassistant на виртуалке и в самой винде torrserve. А так да, заметил, что если  μTP  не отключить,  то проц подъедается знатно.
