### ISSUE TITLE
Torrserver only shows the sample.mkv from the torrent

### ISSUE THREAD

**Issue by TiSs12345** [YouROK/TorrServer#184]
Torrserver mostly shows only the sample.mkv from the torrent, so i can´t find the main movie in torrserver

**Comment by tsynik** [comment]
> Torrserver mostly shows only the sample.mkv from the torrent, so i can´t find the main movie in torrserver

TorrServer must show all video and music files in torrent (try to open BDMV or mp3 album torrent for example) - which tracker and torrent used? Add .torrent to reproduce.

**Comment by TiSs12345** [comment]
i used lampa on web os with jackett running privat tracker "tntracker"
But the most movies just show me the sample.mkv. even when i check torrserver interface is always shown one file per movie.
but the size is shown normal in the overview

**Comment by tsynik** [comment]
> i used lampa on web os with jackett running privat tracker "tntracker"
> But the most movies just show me the sample.mkv. even when i check torrserver interface is always shown one file per movie.
> but the size is shown normal in the overview

once again - copy .torrent file or hash to reproduce

**Comment by TiSs12345** [comment]
cc73ce631e1356917eada48000e07b343b6c38a6

**Comment by TiSs12345** [comment]
https://ibb.co/ysPtknB

**Comment by tsynik** [comment]
> cc73ce631e1356917eada48000e07b343b6c38a6

this hash can't be resolved via DHT so .torrent file needed.

**Comment by TiSs12345** [comment]
https://www.file-upload.net/download-15000915/TNsslThor.Love.and.Thunder.2022.GERMAN.DL.DV.2160P.WEB.H265-WAYNE.torrent.html

**Comment by tsynik** [comment]
> https://www.file-upload.net/download-15000915/TNsslThor.Love.and.Thunder.2022.GERMAN.DL.DV.2160P.WEB.H265-WAYNE.torrent.html

![Снимок экрана 2022-09-11 в 23 07 43](https://user-images.githubusercontent.com/1551446/189546927-40ac7c38-cbeb-4cb7-bf37-5d28eeadc86a.png)

just attach it here as txt or zip?

**Comment by TiSs12345** [comment]
as .torrent, but i saw now the problem, i guess the most movies are packed in rar´s but the sample not.
so i have to look for a tracker without rar´s

**Comment by tsynik** [comment]
> as .torrent, but i saw now the problem, i guess the most movies are packed in rar´s but the sample not.
> so i have to look for a tracker without rar´s

yes, it's not a problem of TorrServer but torrent contents. It doesn't contains supported mime.

**Comment by TiSs12345** [comment]
> 

ok ty anyway
