### ISSUE TITLE
How enable https ?

### ISSUE THREAD

**Issue by SergeKZ** [YouROK/TorrServer#188]
My ISP monitors http and blocks ip externally! tell me how to enable https ?

**Comment by slashfast** [comment]
Nginx reverse proxy

**Comment by lieranderl** [comment]
> Nginx reverse proxy

On Android?

**Comment by lieranderl** [comment]
I consider it more as a feature request to enable HTTPS in gin (directly in torrserver's webserver) using self-signed certs and (even better ) give users the ability to upload their own cert/key in web settings.

**Comment by slashfast** [comment]
> > Обратный прокси Nginx
> 
> На Android?

On Android it is better to use a local server, otherwise it is better to host on a dedicated server/VPS with any reverse proxy solution

**Comment by lieranderl** [comment]
> > > Обратный прокси Nginx
> > 
> > 
> > На Android?
> 
> On Android it is better to use a local server, otherwise it is better to host on a dedicated server/VPS with any reverse proxy solution

I do not think that setup an additional local server just for the reverse proxy is a good solution here. It requires additional physical server and knowledge. As I wrote above, it's easy to add HTTPS functionality directly on Torrserver.

Here is another use case there HTTPS is required on TorrServer:
Torrserver is running in the local network on android tvbox. Lampa or some other movie/torrents web applications can connect to Torrserver via API to add torrents. Such web apps are using HTTPS. Once a user tries to add a torrent to torrserver from the web app, the web app is making an API request to torrserver via HTTP, so we have a "HTTPS to HTTP" request which is blocked on all modern browsers. Users have to manually disable that security feature in the browser. Most of the users do not even know about that, so they think it just doesn't work. Moreover, you can not disable security features in mobile browsers, so you can not add torrents from the web app opened on your phone.

**Comment by tsynik** [comment]
PRs are welcome
