### ISSUE TITLE
Docker version not updated.

### ISSUE THREAD

**Issue by sK1LLer** [YouROK/TorrServer#189]
Docker version lags a little bit behind. Can you please update it?
Docker is 117 and release is ~~118~~ 119.

**Comment by skunkie** [comment]
The job failed: https://github.com/YouROK/TorrServer/actions/runs/3039442044
You can build a container by yourself by running `docker build .`

**Comment by lexbritvin** [comment]
Well, we can, of course 😅
But it's not as convenient as just update the version of the container.

The error log seems strange, because the image definitely [always exists](https://hub.docker.com/_/debian).
Maybe, the project maintainer can just restart the build?

**Comment by slothds** [comment]
> The error log seems strange, because the image definitely [always exists](https://hub.docker.com/_/debian). Maybe, the project maintainer can just restart the build?

yes, image exists, but job failed on building for arm v6.
arm v6 manifest not exists for that image.

**Comment by lexbritvin** [comment]
@YouROK the build for the last image also failed. Can you please take a look on Actions? 
We either need a new base image or ditch armv6

**Comment by lexbritvin** [comment]
It seems you are not providing armv6 binary anyway https://github.com/YouROK/TorrServer/releases/tag/MatriX.119

**Comment by chevcheli0s** [comment]
I think that need to start the workflow manually or wait for a new version.

**Comment by Strikysha** [comment]
> I think that need to start the workflow manually or wait for a new version.

Starting the pipeline manually doesn't make sense, because it will trigger the building process of the docker image from the last GIT tag in the repo (for now it MatriX.119) which is not including the fix now. So we need to wait for when authors will create a new release associated with the git tag that will include the fix. As a workaround, I've just forked a repo and built a new version of torrserve docker image(v119). So you can pull it from here: ghcr.io/strikysha/torrserver:MatriX.119

**Comment by Strikysha** [comment]
@tsynik @YouROK seems that it could be closed as the docker build is fixed.

**Comment by tsynik** [comment]
https://github.com/YouROK/TorrServer/actions/runs/4048686187

**Comment by chevcheli0s** [comment]
@sK1LLer @tsynik I think you need to reopen it.
https://github.com/YouROK/TorrServer/actions/runs/4681770029

**Comment by sK1LLer** [comment]
> @sK1LLer @tsynik I think you need to reopen it. https://github.com/YouROK/TorrServer/actions/runs/4681770029

I think he's got it :)
https://github.com/YouROK/TorrServer/issues/249
