### ISSUE TITLE
Авторизация / Authorization

### ISSUE THREAD

**Issue by krutogorets** [YouROK/TorrServer#191]
Hi!
I created file **accs.db** in _diff/opt/ts/config_ folder but authorization still doesn't work. _TS_HTTPAUTH=1_ is in config file too. Can someone please help?

Привет!
Создал **accs.db** в папке _diff/opt/ts/config_ , но авторизацию всё равно не предлагает и всё работает без пароля. _TS_HTTPAUTH=1_ в конфиге проставлен. Может кто-нибудь подскажет что я делаю не так?

**Comment by tsynik** [comment]
> Привет!
> Создал **accs.db** в папке _diff/opt/ts/config_ , но авторизацию всё равно не предлагает и всё работает без пароля.

Сервер должен быть запущен с ключем -a для включения авторизации, TS_HTTPAUTH=1 не знаю что это и зачем

**Comment by krutogorets** [comment]
> Сервер должен быть запущен с ключем -a для включения авторизации, TS_HTTPAUTH=1 не знаю что это и зачем

Забыл написать – сервер в докере крутится. Судя по инструкции, я предположу, что HTTPAUTH и запускает его с аргументом -a. Но спасибо за ответ, попробую без докера.

**Comment by krutogorets** [comment]
Да, без докера с аргументом -а всё работает, спасибо.
