### ISSUE TITLE
A feature to add a domain to the m3u file 

### ISSUE THREAD

**Issue by slashfast** [YouROK/TorrServer#192]
Hello! 
I use the nginx server for the reverse proxy, but if I want to download a .m3u playlist and open this as text file, I see `http://127.0.0.1:8090`, instead of `domain:port`.

Can you add a feature, that allows to add domain name to  the playlist instead of `127.0.0.1`

I knows about direct link, but I use mpv and don't wanna open terminal and paste link, only drag'n'drop file to the window.

**Additional:**
Copy link:
`https://example.com:443/stream/movie.mkv?link=blabla&index=1&play`

.m3u playlist
```
#EXTM3U
#EXTINF:0,movie.mkv
http://127.0.0.1:8090/stream/movie.mkv?link=blabla&index=1&play
```
What I want
```
#EXTM3U
#EXTINF:0,movie.mkv
https://example.com:443/stream/movie.mkv?link=blabla&index=1&play
```
(it's work, if I edit playlist manualy)

**Comment by avengermsoft** [comment]
Hello! Everything works with links correctly.

Use 
```
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;
```
