### ISSUE TITLE
Disk cache removed on startup

### ISSUE THREAD

**Issue by d61668** [YouROK/TorrServer#193]
Disk cache is removed on every TorrServer restart even having in settings only to remove it on torrent deletion.

I'm not a go lang programmer but this piece looks incorrect to me:

```
log.TLogln("Remove unused cache in dir:", settings.BTsets.TorrentsSavePath)
for _, d := range dirs {
    if len(d.Name()) != 40 {
	    // Not a hash
	    continue
    }
    
    if !settings.BTsets.RemoveCacheOnDrop {
	    for _, t := range torrs {
		    if d.IsDir() && d.Name() != t.InfoHash.HexString() {
			    log.TLogln("Remove unused cache:", d.Name())
			    removeAllFiles(filepath.Join(settings.BTsets.TorrentsSavePath, d.Name()))
			    break
		    }
	    }
    } else {
	    if d.IsDir() {
		    log.TLogln("Remove unused cache:", d.Name())
		    removeAllFiles(filepath.Join(settings.BTsets.TorrentsSavePath, d.Name()))
	    }
    }
}
```

Looks like the it takes the directories from the list and tries to compare it to torrent hash from the list. Therefore I believe most time they are not equal, because they're in random order in lists. But I'm not an expert it's just my suggestion.

**Comment by tsynik** [comment]
It's expected behavior. If there will be no cache clean on restart, probably stale cache will grow indefinitely it Remove cache on drop option is disabled.
