### ISSUE TITLE
Встроенный плеер 

### ISSUE THREAD

**Issue by ETH-contractDev** [YouROK/TorrServer#194]
Скажите есть ли возможность во встроенном плеере организовать плейлисты? Очень часто смотрю торренты где много серий или файлов и не удобно постоянно переключаться на новый выпуск.

Так же очень хотелось бы создание папок на главной странице сервера, что бы разделять торренты по группам

**Comment by susl16c** [comment]
Тоже вопрос с плеером интересен.

**Comment by tsynik** [comment]
Встроенного плеера у TorrServer нет
