### ISSUE TITLE
Не может загрузить hash торрента

### ISSUE THREAD

**Issue by Vortexar** [YouROK/TorrServer#196]
Имеется следующий сетап:
Lampa на WebOS и TorrServe Matrix.117 (работает на собственном сервере ubuntu 22.04 x64 через докер).

Проблема: сервер показывается Lamp'ой как активный, но при попытке загрузки торрента выдает ошибку 400 - "Не удалось получить hash".

Сам TorrServe работает исправно, и с ПК и с Forkplayer'а на том же телевизоре. В веб-версии Jackett все ОК, торренты грузятся (в том числе и через TorrServe). Так что это точно не Jackett, а TorrServe.
Важный момент: при указании в настройках Lamp'ы какого-либо другого публичного TorrServe (версия Matrix.API) все работает исправно. При переключении на собственный сервер (Matrix.117) выдает упомянутую ошибку.

![PXL_20221228_185745449](https://user-images.githubusercontent.com/84748456/209826958-f9895c7c-77bc-4f48-9e83-0e6f5993da29.jpg)

**Comment by tsynik** [comment]
Это не ошибка торрсервера
