### ISSUE TITLE
Пропали торренты в ATV но остались в web после переноса базы с торсервера под bsd на сервер в docker под debian

### ISSUE THREAD

**Issue by visilya** [YouROK/TorrServer#197]
v 1.18
Был торсервер во freenas
Запустил торсервер в докере в дебиане
Перенес базу
Результат:
На сайте торсервера все торренты на месете, можно удалять и добавлять.
В приложении на ТВ в трекерах пусто.

Если же очистить БД, то в приложении на ТВ торренты нормально добавляются и отображаются.

**Comment by HiHat** [comment]
У меня аналогичная ситуация. Некоторое время назад (после перехода на 1.18?) начала портиться база config.db. Список торрентов виден в web интерфейсе, но пустой в клиентах под Android. Два раза откатывал базу на момент перехода с 1.17 на 1.18 и оба раза, через некоторое, время она портилась!
Готов поделиться испорченной версией базы.

**Comment by tsynik** [comment]
не возможно воспроизвести
