### ISSUE TITLE
GLIBC_2.28 not found on ubuntu 18.04.2 LTS

### ISSUE THREAD

**Issue by Novarg** [YouROK/TorrServer#2]
Latest release can't run on ubuntu 18.04.2 LTS

```./TorrServer-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./TorrServer-linux-amd64)```

```libc6 is already the newest version (2.27-3ubuntu1).```

any workaround please?

**Comment by YouROK** [comment]
I updated my system to new ubuntu 19.04 and libc was also updated with it.
You have two options to fix the problem.
1) Update libc to version 2.28
2) Build from source

**Comment by Novarg** [comment]
It's too risky to upgrade libc.

It was a bit painful to go get all packages but at least it been compiled :)

**Comment by zyxmon** [comment]
Попытался за пустить на НАСе от Qnap с glibc 2.21 - получил аналогичный вигвам.
Собрал на debian 9, а том тоже новая glibc.
Пересборка с CGO_ENABLED=0 решила проблему с TorrServer-linux-amd64
При этом перестали собираться mips* варианты, но они и не нужны.

**Comment by zyxmon** [comment]
Для информации (сначала версия собранная с CGO_ENABLED=0, потом с гитхаба)

```
# ldd ./TorrServer-linux-amd64
$       not a dynamic executable


# ldd ./TorrServer-linux-amd64
 ldd ./TorrServer-linux-amd64
        linux-vdso.so.1 (0x00007ffcce9fe000)
        libpthread.so.0 => not found
        libdl.so.2 => not found
        libc.so.6 => not found

```

**Comment by zyxmon** [comment]
Версия 1.73 - аналогично не запускается. Просьба собрать с `CGO_ENABLED=0,`
