### ISSUE TITLE
Не подгружаются обложки в автоматическом режиме

### ISSUE THREAD

**Issue by RomanV0703** [YouROK/TorrServer#200]
Пример с **Rutracker.org**. Если в заголовке темы много слов (а на **Rutracker** так принято по правилам трекера), поиск обложки по **themoviedb.org** в автоматическом режиме не справляется.

![Screenshot 2023-01-14 220459](https://user-images.githubusercontent.com/6275837/212478659-12c88d01-7bf9-4a50-9709-fbb5ddf0325f.png)

Если забить название в **Custom title (optional)**, всё работает прекрасно.

![Screenshot 2023-01-14 220521](https://user-images.githubusercontent.com/6275837/212478655-4a6e8c97-7d9e-49a4-aae1-179168bb27d9.png)

Неплохо было бы разобраться с поиском: искать по отдельным словам из заголовка, если это возможно. Или небольшой костыль — обрезать до первой скобки в заголовке и искать по этой части.

**Comment by RomanV0703** [comment]
С зарубежными фильмами тоже проблема: ни по полному заголовку, ни по двойному названию (на двух языках, опять же по правилам **Rutracker**) обложка не находится.

![Screenshot 2023-01-14 221100](https://user-images.githubusercontent.com/6275837/212479015-eea7fadd-bc28-430e-9585-49959684f88b.png)

При этом по отдельным названиям (что русскоязычному, что оригинальному) находится прекрасно:

![Screenshot 2023-01-14 221121](https://user-images.githubusercontent.com/6275837/212479046-567d2a5d-bc31-4659-9151-f70ea54fe9b4.png)
![Screenshot 2023-01-14 221144](https://user-images.githubusercontent.com/6275837/212479053-e7dd51b1-d5d2-44fd-8a5d-86cf12dd423e.png)

**Comment by tsynik** [comment]
подгрузка работает as is
