### ISSUE TITLE
Extreme page cpu and mem usage

### ISSUE THREAD

**Issue by GribanovIvan** [YouROK/TorrServer#202]
html page uses 100% of one cpu core and several gigabytes of memory.
MatriX.118
Firefox 108.0.2
added torrents: 0

**Comment by tsynik** [comment]
Can't reproduce, maybe use other browser for torrserver web in case such Firefox behavior
<img width="1440" alt="trs-ff" src="https://user-images.githubusercontent.com/1551446/212570076-29a2d80f-4990-45dc-8954-8f51bf57a501.png">
.

**Comment by GribanovIvan** [comment]
That happens randomly. How I can collect logs or smth to help development?
