### ISSUE TITLE
Включив кэш с диска и поменяв локацию кэша приложение падает

### ISSUE THREAD

**Issue by holms** [YouROK/TorrServer#203]
Дело произходит на miTV боксе.

* Иду в настройки, 
* Указываю использовать кэш с диска
* Указываю путь к кэшу
   * нахожу директорию где хочу хранить кэш
   * создаю новую директорию, 
   * печают ее название, enter, и крэш 

Версия Matrix.117.Client

**Comment by tsynik** [comment]
logcat с устройства приложите, и это не относится к серверу и нужно рапортовать сюда https://github.com/YouROK/TorrServe/issues

**Comment by holms** [comment]
Понял извините. Рабортую туда.
