### ISSUE TITLE
Пролистав 10 секунд в Kodi приложение падает

### ISSUE THREAD

**Issue by holms** [YouROK/TorrServer#204]
APK в MiboxTV версия Matrix.117.Client

Lampa->4k torrent->TorrServer Add&Play->Kodi

При seeking'е в любое количество секунд падает TorrMatrix, оказываюсь в меню плеера Kodi.

**Comment by tsynik** [comment]
лог сервера (на андроиде он в /sdcard/Android/data/ru.yourok.torrserve/files/torrserver.log) приложите

**Comment by holms** [comment]
@tsynik может и это в  https://github.com/YouROK/TorrServe/ рапортавать? Или это уже по адресу? :)

**Comment by tsynik** [comment]
> Или это уже по адресу? :)

если падает сервер - по адресу. если Коди - это к коди

**Comment by holms** [comment]
Одни проблемы за другим с TorrServe не могу плеер выбрать, открывает выбор плеера и не могу пометить не одну из 3х иконок. Попробывал через настройки плеер сменить плеер на VLC, вроде не ломается. Простите за беспокойтво. Буду знать где логи искать хотя хз как мне их доставить с MiboxTV сюда.
