### ISSUE TITLE
При огромном кэшэ видео всеравно прирывает просмотр буферизацией

### ISSUE THREAD

**Issue by holms** [YouROK/TorrServer#205]
Помогите разобраться:

* Торрент в качестве 2480p
* Кэш выставлен на 256mb
* Размер торрента 1gb
* Pre-cache выставлен на 100%
* Открываю в плеере VLC

Каждые 5-10секунд всеравно произходит буферизация и при этом надо ждать 2-3 секунды. Почему так произходит? Длинна видео 10 минут

Использую Mi Box S

**Comment by tsynik** [comment]
Probably network isssue.
