### ISSUE TITLE
Переполнение ОЗУ при использовании на роутере ASUS RT-AX86U

### ISSUE THREAD

**Issue by jokereinherjar** [YouROK/TorrServer#207]
Имеется роутер ASUS RT-AX86U с прошивкой Merlin, на котором установлен Entware, на нём установлен пакет torrserver.
После просмотра торрента ОЗУ роутера не очищается, и соответственно спустя некоторое время память полностью забивается, из за этого torrserver начинает использовать Swap, и скорость закачки резко падает. Из-за этого приходится перезагружать роутер, что неудобно.
Как сделать, чтобы torrserver после просмотра торрента очищался из памяти?
torrserver установлен версии .118

**Comment by tsynik** [comment]
> Как сделать, чтобы torrserver после просмотра торрента очищался из памяти?
> torrserver установлен версии .118

Единственная возможность использовать сервер на роутерах - выбрать кеш на диске а не в ОЗУ, при этом на роутере все равно должно быть порядка 256МБ+ и обычная флешка для кеша не годится - это должен быть как минимум USB HDD.

**Comment by jokereinherjar** [comment]
Памяти на роутере достаточно, 1 гб. Свободно после перезагрузки около 450 мб. Я узнавал, как на других роутерах torrserver себя ведёт, и такой проблемы как на ASUS RT-AX86U не наблюдается. И такая проблема не только у меня, но и у других владельцев роутера.

**Comment by tsynik** [comment]
> Памяти на роутере достаточно, 1 гб. Свободно после перезагрузки около 450 мб. Я узнавал, как на других роутерах torrserver себя ведёт, и такой проблемы как на ASUS RT-AX86U не наблюдается. И такая проблема не только у меня, но и у других владельцев роутера.

Значит это проблема асуса, но совет все тот же - включить кеш на диск. На R1D с 256МБ торрсервер  работает без проблем в такой конфигурации.

**Comment by jokereinherjar** [comment]
После использования кеша на диске проблема с переполнением памяти ушла, но появилась другая проблема. Служба torrserver бывает сама собой отключается, и приходиться опять перезагружать роутер, либо через ssh вручную запускать.
Как сделать, чтобы служба автоматически запускалась, если она останавливается?

**Comment by tsynik** [comment]
> Как сделать, чтобы служба автоматически запускалась, если она останавливается?

пробуй запускать с параметром -k (сервер будет игнорировать сигналы завершения от ОС)

**Comment by jokereinherjar** [comment]
Я правильно понимаю, что в стартовом скрипте S90torrserver строку
`ARGS="-d /opt/etc/torrserver"`
надо изменить на строку
`ARGS="-d /opt/etc/torrserver -k"`

**Comment by tsynik** [comment]
> надо изменить на строку
> `ARGS="-d /opt/etc/torrserver -k"`

да, но имей в виду что S90torrserver stop после этого вероятно работать перестанет.
