### ISSUE TITLE
Empty playlist for DVD

### ISSUE THREAD

**Issue by Lodger-test** [YouROK/TorrServer#209]
Distro: Arch GNU/Linux
TorrServer MatriX.120

When trying to watch DVD the empty playlist is generated

**Expected behavior:**

Playlist for DVD lists video files (*VOB) from the VIDEO_TS directory of DVD

**Actual behavior**

torrserver generates the playlist, that consists only of "#EXTM3U" string and nothing more.

**How to reproduce:**

1. Add a torrent file or magnetic link to torrserver from the tracker for DVD video. 
2. Download playlist from web-interface of torrserver.
3. Read the generated *m3u playlist.

**Comment by Lodger-test** [comment]
Example of torrent hash: c5f8b5416746466ca360714c25d6b1d28d9d97f7

**Comment by tsynik** [comment]
fixed with https://github.com/YouROK/TorrServer/commit/fb2ba1e38603329f5129741a125fbaa953a66f9d
