### ISSUE TITLE
Крашится при переходе на другой момент во время просмотра фильма 

### ISSUE THREAD

**Issue by Djemchik** [YouROK/TorrServer#210]
OS: Debian Bullseye
На VDS
1 гб ОЗУ, 3 ГГц 1 ядерка
При перемотке фильма крашится сервак

**Comment by zhukovra** [comment]
@Djemchik как воспроизвести?

**Comment by Djemchik** [comment]
> @Djemchik как воспроизвести?

Сам ХЗ 
VDS От TimeWeb.cloud
Хоть на докере, хоть на стандарте
Debian 11 Bullseye 
1 ядро на 3ГГц
1 Гб оперативной памяти


Включаю (фильм, сериал), запускаю плеер на устройстве, играет, перематываю, всё TorrServer не отвечает

**Comment by tsynik** [comment]
> Включаю (фильм, сериал), запускаю плеер на устройстве, играет, перематываю, всё TorrServer не отвечает

Вероятно не хватает оперативной памяти. Подключаешь swap и проблема уходит. В случае проблем с torrserver информация о его аварийном завершении будет записана в консоль / лог (включить запись лога в файл на хостинге возможно добавив ключ запуска -l и указав путь к файлу лога (пример: - l /opt/torrserver-matrix/torrserver.log). Прилагай файл лога с ошибкой сервера, либо это не к нему.
