### ISSUE TITLE
Rutor поиск 

### ISSUE THREAD

**Issue by grannymaster** [YouROK/TorrServer#214]
Либо я слепой, либо тупой, но как можно использовать недавно добавленную функцию "Добавлен поиск по рутор"? Я включил её в настройках сервера, и что дальше?

**Comment by tsynik** [comment]
> Либо я слепой, либо тупой, но как можно использовать недавно добавленную функцию "Добавлен поиск по рутор"? Я включил её в настройках сервера, и что дальше?

На подобные вопросы можно найти ответ в группе Telegram https://t.me/TorrServe Если коротко - оно для приложений что могут это использовать.
