### ISSUE TITLE
Error read rutor db: flate: corrupt input before offset 12

### ISSUE THREAD

**Issue by MrKsey** [YouROK/TorrServer#215]
Не обновляется rutor.ls

2023-02-09T23:12:02+0300 TSM Update rutor db
2023-02-09T23:12:02+0300 TSM Load rutor db
2023-02-09T23:12:02+0300 TSM Error read rutor db: flate: corrupt input before offset 12
[rutor.zip](https://github.com/YouROK/TorrServer/files/10713664/rutor.zip)

**Comment by krasnh** [comment]
Исправлено с MatriX.120.3. 
Можно самостоятельно собрать с git, или взять бинарные [здесь](https://4pda.to/forum/index.php?showtopic=889960&view=findpost&p=119119092).


p.s. Вопрос к ответственным, есть ли смысл сообщать сюда о багах, если нет никакой реакции?
Сам, когда столкнулся с  `Error read rutor db: flate: corrupt input before offset 12`, первым делом подумал, что это у меня что-то сломалось.
А когда перепроверил на разных дистрах и хотел создать "New issue", то передумал, увидев отсутствующую обратную связь. Хорошо, что ТС оказался более сознательным. 
Или все на телегу перебрались с концами? :)

**Comment by tsynik** [comment]
> если нет никакой реакции?
если не сообщать, то её и не будет
