### ISSUE TITLE
PWA is not available when HTTP Auth is enabled

### ISSUE THREAD

**Issue by lexbritvin** [YouROK/TorrServer#221]
My server is configured to use HTTP Auth as described here https://github.com/YouROK/TorrServer#authorization
I tried to add PWA on iOS to use VLC link, but there is no Mobile App configuration view. I can't use VLC in PWA.

**Steps to reproduce:**
0. Use iOS
1. Configure HTTP Auth - https://github.com/YouROK/TorrServer#authorization
2. Open Safari and go to TS web UI
3. Add to Home (install PWA)
4. Open the app on Home

**Expected result:**
HTTP Auth is requested, PWA view is loaded, Mobile config page is available.

**Actual result:**
HTTP Auth is requested, PWA is not available, standard view is shown, Mobile config page is not available

I noticed: if I disable HTTP Auth, add PWA according to the steps, enable HTTP Auth again, all works as expected.
I suppose the issue may appear because PWA manifest is not available to Safari because of HTTP Auth header.

**Comment by tsynik** [comment]
> I suppose the issue may appear because PWA manifest is not available to Safari because of HTTP Auth header.

Added site.webmanifest to always accessible path, and can't reproduce on Android PWA app added from Chrome with HTTP auth enabled. So probably it's Safari issue and can't be fixed on TorrServer side.

**Comment by lexbritvin** [comment]
I found 2 similar issues:
https://github.com/koajs/basic-auth/issues/19
https://thatemil.com/blog/2018/02/21/pwa-basic-auth/

Maybe we need to implement the same?

**Comment by apnagaev** [comment]
Hi, I use v120 and can't use auth. I use docker with config:
```
docker run -d --name=torrserver \
            --restart=unless-stopped \
            -e TS_HTTPAUTH=1 \
            -v /docker/torrserver/db:/torrserver/db \
            -v /docker/torrserver/ts:/opt/ts \
            -v /etc/localtime:/etc/localtime:ro \
            -p 8090:8090 solopasha/torrserver
```
and file accs.db
```
{
"ust":"Pass1"
}
```
I tried put accs.db in /ts, /db, /ts/config, /db/config. What I do wrong? Torrserver does't ask autentification

**Comment by lexbritvin** [comment]
Hi @apnagaev 

It's thread related to PWA, not issues with HTTP Auth. 
Please, use search (#191) or create a new support issue. Don't post in other issues.

Besides, you are using image `solopasha/torrserver`, some other maintainer's project with a `latest` version, the version is not explicitly set. We can't confirm that you actually use `v120`.
We also can't support other repos here, you must send a support request in the original repo. It has a different Dockerfile.

Please, better use a docker image from [current repository](https://github.com/YouROK/TorrServer/pkgs/container/torrserver) with an exact version, which is `ghcr.io/yourok/torrserver:matrix.120`

Answering your question, I can confirm `TS_HTTPAUTH=1` works as expected in docker.

Here is an example of `docker-compose.yml` that I use.
```
version: "3.9"
services:
  torrserver:
    image: ghcr.io/yourok/torrserver:matrix.120
    container_name: torrserver
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./ts:/opt/ts
      - /etc/localtime:/etc/localtime:ro
    environment:
      TS_LOG_PATH: "/dev/null"
      TS_HTTPAUTH: "1"
```

You must ensure that you have the file `/opt/ts/config/accs.db` inside a container when you bind host FS inside a container. 
In my case, it's `./ts/config/accs.db` on host.
For you, according to your configuration, you have to put file in `/docker/torrserver/ts/config/accs.db`.

Besides, you bind `-v /docker/torrserver/db:/torrserver/db`. It won't be used by the original container.
The application works only inside `/opt/ts`. 
Please, refer to the original documentation and docker image.

**Comment by apnagaev** [comment]
Sorry, youre are right, when I change image to ghcr.io/yourok/torrserver:matrix.120 torrserver started working

**Comment by tsynik** [comment]
probably fixed in [MatriX.121](https://github.com/YouROK/TorrServer/releases/tag/MatriX.121) release

**Comment by tsynik** [comment]
Reopen if issue is still active

**Comment by lexbritvin** [comment]
Still not fixed for me
