### ISSUE TITLE
Torrserver + Yatse

### ISSUE THREAD

**Issue by TiBiDO** [YouROK/TorrServer#222]
Не могли бы вы помочь разработчикам Yatse добавить Torrserver в их плагин для передачи magnet ссылок, очень удобно (было) с телефона отправлять данные в Kodi.

https://community.yatse.tv/t/torrserver-for-sharing-magnet-links/4254/2?u=tibido

Заранее огромное спасибо!

**Comment by YouROK** [comment]
В коди не разбираюсь. А вся инфа есть в readme репозитория.
