### ISSUE TITLE
Постеры

### ISSUE THREAD

**Issue by GutsyHeart** [YouROK/TorrServer#224]
Две проблемы c постерами:

**1** Постеры в автоматическом режиме не загружаются из-за CORS:
`Запрос из постороннего источника заблокирован: Политика одного источника запрещает чтение удаленного ресурса на http://api.themoviedb.org/3/search/multi?language=ru&include_image_language=ru,null,en&query=Irreductible. (Причина: не удалось выполнить запрос CORS). Код состояния: (null).`

**2** Постеры пропадают:
  Добавляю торренты через [TorrServer Adder](https://github.com/Noperkot/TorrServerAdder)
  Постеры отлично загрузились
  Через некоторое захожу - постеров уже нет.

Torrserver запущен в контейнере podman

**Comment by tsynik** [comment]
Что казается CORS - он уже сконфигурирован в TorrServer на разрешение cross-origin requests, а причина вашей ошибки в первом случае вероятно в недоступности api.themoviedb.org конкретно для вас. Попробуйте выполнить то же действие с европейским ВПН и ошибок не будет.

Что же до пропадания постеров - мыслей нет. TorrServer проверяет url постера при добавлении на валидность изображения по ссылке, и либо добавляет её в БД при успехе, либо нет. Появиться и пропасть они при этом по идее не могут.

**Comment by GutsyHeart** [comment]
Да действительно api был заблокирован.
Но теперь 401 `Invalid API key: You must be granted a valid key.`

С постерами разобрался 
Постеры закачивающийся на .jpg?r=1 не подходят

**Comment by tsynik** [comment]
> Да действительно api был заблокирован.
> Но теперь 401 `Invalid API key: You must be granted a valid key.`

Если это самособранный torrserver, то читайте readme.md в web по добавлению tmdb api key в .env для сборки

**Comment by seba1213** [comment]
А у меня тоже постеры пропадают и дело не в названии фаила
TorrServer-linux-amd64[554]: 2023/08/24 00:02:55 add torrent file file
TorrServer-linux-amd64[554]: 2023/08/24 00:02:55 Create cache for: Star.Trek.Strange.New.Worlds.S02E03.1080p.rus.LostFilm.TV.mk>
TorrServer-linux-amd64[554]: 2023/08/24 00:02:55 save to db: b02f252333678fb13840547dd5d4790a17be9b09
TorrServer-linux-amd64[554]: 2023/08/24 00:02:57 Error decode image: image: unknown format
TorrServer-linux-amd64[554]: 2023/08/24 00:07:55 Torrent close by timeout b02f252333678fb13840547dd5d4790a17be9b09
TorrServer-linux-amd64[554]: 2023/08/24 00:07:55 Close cache for: b02f252333678fb13840547dd5d4790a17be9b09

происходит это в момент закрытия кеша, ссылка на постер пропадает, ссылка (пока она есть) без каких либо параметров в конце.
