### ISSUE TITLE
Enhancement: ability to compile under FreeBSD on arm64/aarch64

### ISSUE THREAD

**Issue by A-Petrov-atweb** [YouROK/TorrServer#225]
Currently I got:
GOOS=freebsd GOARCH=arm64   go build -ldflags='-s -w' -tags=nosqlite -o /home/petrov/src/TorrServer/dist/TorrServer-freebsd-arm64 ./cmd
 github.com/anacrolix/mmsg/socket
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/cmsghdr.go:9:10: undefined: cmsghdr
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/cmsghdr.go:10:10: undefined: cmsghdr
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/cmsghdr.go:11:10: undefined: cmsghdr
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/cmsghdr_bsd.go:9:10: undefined: cmsghdr
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/iovec_64bit.go:12:10: undefined: iovec
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/msghdr_bsd.go:11:10: undefined: msghdr
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/msghdr_bsd.go:11:28: undefined: iovec
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/msghdr_bsd.go:26:10: undefined: msghdr
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/msghdr_bsd.go:33:10: undefined: msghdr
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/msghdr_bsd.go:37:10: undefined: msghdr
../../../go/pkg/mod/github.com/anacrolix/mmsg@v1.0.0/socket/msghdr_bsd.go:37:10: too many errors

Seems there no required definitions under dependencies. So, a recomendation is wanted how it can be "workarounded".
Build attempted is on Rock Pi 4 board
//
Короче, каких-то деклараций в зависимостях нехватает :)
У самого ума не хватает откуда и куда что положить, чтобы собралось.
на всякий случай uname -a
FreeBSD tools 13.1-RELEASE-p6 FreeBSD 13.1-RELEASE-p6 GENERIC arm64

**Comment by tsynik** [comment]
workaround is to report compile errors to package maintainer which throw it: github.com/anacrolix/mmsg

**Comment by A-Petrov-atweb** [comment]
My hands are reach to try a cross-build for arm64 under amd64 machine.
And resulting binary are works!
May be it is a good idea to add an build variant 'freebsd/arm64' in build-all.sh ?
