### ISSUE TITLE
Добавление фильтрации в веб-интерфейс

### ISSUE THREAD

**Issue by DaMaNic2022** [YouROK/TorrServer#230]
Есть огромное желание увидеть в веб интерфейсе хотя бы минимальную фильтрацию по категориям/тэгам. Т.е. при вводе торрента добавляются тэги, с минимальной хотя бы подстановкой из списка, ну или список может быть жестко зафиксирован, а потом в основном интерфейсе по этому списку чтобы можно было отфильтровать. Фильмы/музыка/игры/другое - хотя бы так. Готов проспонсировать, если это вообще корректно.

**Comment by TopperBG** [comment]
Как в Лампе ?

**Comment by DaMaNic2022** [comment]
> Как в Лампе ?

Реализация абсолютно на Ваше усмотрение. Просто без фильтрации, хотя бы простейшей системы, через какое то время сервер превращается в свалку. Как папки на компьютере - примерно такая же система.

**Comment by DaMaNic2022** [comment]
> Как в Лампе ?

Скорее как в https://github.com/distribyted/distribyted, где при добавлении магнет ссылки можно выбрать категорию. Там до кучи вместе с веб-интерфейсом поддерживается WebDAV и fuse, что позволяет подключить ресурсы как сетевые/локальные диски, но серьезный минус в том что кэширование сделано не в память, а на диск, и минус в том что кэшируется все, т.е. в какой то момент кэш по размеру от скачанного полностью торрента уже мало отличается.

**Comment by TopperBG** [comment]
Я понял вас так:
![image](https://user-images.githubusercontent.com/23097319/229069789-825ff878-f477-409b-b184-f1651eecf8f0.png)

**Comment by DaMaNic2022** [comment]
> Я понял вас так: ...

Ну это уже зависит от того, насколько сложной фильтрацию делать ))) Указанные на Вашем скриншоте параметры это скорее подходят как тэги, меня же устроит хотя бы просто список категорий, а дальше уж как будет реализовано - зависит от желания. Я для своей докувики делал 5 вложенных категорий + отдельно тэги, этого достаточно было чтобы построить достаточно удобное дерево, которое можно отфильтровать дополнительно по тэгам.
![Буфер обмена02](https://user-images.githubusercontent.com/113093852/229075684-2078111f-aada-4f5c-bc60-28284111f546.jpg)

Для торрентов я думаю это избыточно, для простейшей сортировки хватит просто плоского списка категорий "Фильмы/музыка/.../сериалы", а дальше уже вопрос реализации подкатегорий и дополнительных тегов.
Плюс если же когда нибудь будет реализован доступ к содержимому через WebDAV или FUSE, как это сделано в distribyted, то эти категории/подкатегории легко отобразятся там как папки/подпапки, что дает уже совершенно новый уровень удобства работы с коллекцией торрентов.

**Comment by GutsyHeart** [comment]
> > Как в Лампе ?
> 
> Скорее как в https://github.com/distribyted/distribyted, где при добавлении магнет ссылки можно выбрать категорию. Там до кучи вместе с веб-интерфейсом поддерживается WebDAV и fuse, что позволяет подключить ресурсы как сетевые/локальные диски, но серьезный минус в том что кэширование сделано не в память, а на диск, и минус в том что кэшируется все, т.е. в какой то момент кэш по размеру от скачанного полностью торрента уже мало отличается.

Так можно просто создать папку в tmpfs и указать её для distribyted.
Кэшируется не всё, а только запрашиваемые части. Видимо у вас кеш неограничен.

**Comment by DaMaNic2022** [comment]
> Так можно просто создать папку в tmpfs и указать её для distribyted. Кэшируется не всё, а только запрашиваемые части. Видимо у вас кеш неограничен.

К сожалению это не так. У distribyted кэш задан 512 мб, торрентов на 24 гига, в кэше резервируется целиком файл, даже если запрошен очень небольшой его кусочек. Возможно помогло бы сжатие файловой системы (создаваемый файл скорее всего при обращении к нему на 99% пуст), но боюсь что если у Torrserver принцип кеширования по кусочкам в памяти эффективно работает, скачал-отдал-потерял, то distribyted скачал 1 мегабайт - занял 3 гигабайта, и так и лежит 3 гигабайта дальше в кэше. Плюс куча ошибок при старте и во время работы, плюс тормоза, пока он этот файл на 3 гигабайта создаст.
![Буфер обмена03](https://user-images.githubusercontent.com/113093852/229505243-11701ef8-659b-440b-848f-3187f4fef689.jpg)

В общем пока сырое поделие этот distribyted, надежда что все таки хотя бы часть его функционала будет реализована в Torrserver, он постабильнее в работе все таки.

**Comment by GutsyHeart** [comment]
> К сожалению это не так. У distribyted кэш задан 512 мб, торрентов на 24 гига, в кэше резервируется целиком файл, даже если запрошен очень небольшой его кусочек. Возможно помогло бы сжатие файловой системы (создаваемый файл скорее всего при обращении к нему на 99% пуст), но боюсь что если у Torrserver принцип кеширования по кусочкам в памяти эффективно работает, скачал-отдал-потерял, то distribyted скачал 1 мегабайт - занял 3 гигабайта, и так и лежит 3 гигабайта дальше в кэше. Плюс куча ошибок при старте и во время работы, плюс тормоза, пока он этот файл на 3 гигабайта создаст. ![Буфер обмена03](https://user-images.githubusercontent.com/113093852/229505243-11701ef8-659b-440b-848f-3187f4fef689.jpg)
> 
> В общем пока сырое поделие этот distribyted, надежда что все таки хотя бы часть его функционала будет реализована в Torrserver, он постабильнее в работе все таки.

Похоже на windows момент.

Кеш 120mb в tmpfs

![изображение](https://user-images.githubusercontent.com/49452820/229736817-66317f8e-47c9-41a6-879a-9fd187e61097.png)

На диске ничего не занято
![изображение](https://user-images.githubusercontent.com/49452820/229737521-c62ebb94-eb61-4e6d-afc5-94a4c7db51f5.png)

**Comment by DaMaNic2022** [comment]
> Похоже на windows момент.

Похоже да, причем у Вас похоже кэш чанками, как собственно это и должно быть, а у меня под Windows целыми файлами, причем они не удаляются после того как использованы.
![Буфер обмена03](https://user-images.githubusercontent.com/113093852/229742660-17b185da-bc50-4ded-a4bf-47d92d000257.jpg)

**Comment by DaMaNic2022** [comment]
В итоге реализовал на базе WSL1 + distribyted = WebDaV + NetDrive 2 то что я бы хотел видеть в TorrServer хотя бы в самом примитивном виде.
![Буфер обмена02](https://user-images.githubusercontent.com/113093852/235341330-684d013f-ade4-4cda-abcb-7f2fc29f54c4.jpg)
![Буфер обмена02](https://user-images.githubusercontent.com/113093852/235341370-61bce13d-4ed0-48b9-9145-877e275d0d18.jpg)
