### ISSUE TITLE
upnp или dlna в docker

### ISSUE THREAD

**Issue by mshakurov** [YouROK/TorrServer#231]
Добрый день.
Делал свой Dockerfile, запускал, вэб-интерфейс работает.
Использовал и ваш готовый образ, тоже вэб-интерфейс работает.
Но upnp/dlna клиенты, которые в той же сети, что и хост с докером, не видят этот сервер.
Я что-то не так сделал или не до конца понимаю как в докере torrserver работает?
Просто смысл иметь докер контейнер, который не публикует upnp/dlna?

**Comment by GutsyHeart** [comment]
Чтобы работал dnla в докере должна использоваться сеть хоста, а не мост и т.п.
network=host

**Comment by mshakurov** [comment]
А вы пробовали?  Я попробовал, в первую очередь. И предлагаемый образ, и свой крутил/вертел. Даже установливал мини пргораммки в контейнеры, которые должны были просто увидеть dlna, но видели только dlna  роутера (который шлюз) в сети, а свой локальный торсервер не обнаруживался...
Может быть версии для ПК (win, linux) вообще не реализуют сервисы dlna? 
Или может какая хитрая настройка докер сервиса должна быть?

**Comment by tsynik** [comment]
в  любом случае это настраивается в docker и к торрсерверу отношения не имеет - без контейнера все будет хорошо. p.s. dlna-протокол использует широковещательные multicast адреса для анонса и udp.

**Comment by mshakurov** [comment]
Отлично, спасибо! Буду искать решение... Я просто тему завел потому, что на самой стартовой странице гитхаба говорится о решение через докер, но при этом dlna из докера не работает. Даже внутри самого докера ни чего не обнаруживается. Вот я и подумал, что может быть было бы не плохо продумать решение, и описать его или дать ссылок на решение? Но в любом случае, шикарная вещь, этот сервер... Извините...

**Comment by mshakurov** [comment]
Ага, вон где собака зарылась. Я был прав - dlna в докере отключен, точнее- его ни кто не включает при стате (покопался в исходниках). Декстопный web-интерфейс закрывает большинство настроек под pro-версию, включая настройку, активирующую dlna. А если с андроид web-интерфейса подключиться к докерному torrserver, то можно включить dlna, и он  отлично работает!
