### ISSUE TITLE
Error read token rutor db: invalid character 'R' looking for beginning of value

### ISSUE THREAD

**Issue by MrKsey** [YouROK/TorrServer#239]
Если в каталоге TorrServe есть файл **rutor.ls** от "старой" версии TorrServe 120, то указанный файл не обновляется версией TorrServe 121.
Выдается такая ошибка:
2023/03/25 15:22:20 UTC0 Update rutor db
2023/03/25 15:22:20 UTC0 Less 3 hours rutor db old
2023/03/25 15:22:20 UTC0 Load rutor db
2023/03/25 15:22:20 UTC0 Error read token rutor db: invalid character 'R' looking for beginning of value

После ручного удаления файла обновление проходит нормально.

**Comment by tsynik** [comment]
В данном случае причина указана в логе - файл данных обновлен менее чем 3 часа назад.По истечении этого времени он обновится.
