### ISSUE TITLE
Настройка DHT

### ISSUE THREAD

**Issue by apnagaev** [YouROK/TorrServer#240]
Добрый день!
Как я понимаю, настройки DHT хранятся в файле config.db, у меня есть потребность вносить изменения в настройки DHT скриптом, но просто заменить вхождение не получится. Подскажите, может есть какой-либо параметр, который позволяет указывать порт DHT при запуске? Или возможно порт можно поменять через api? Не нашел ничего подобного в документации

**Comment by tsynik** [comment]
порт для DHT он же порт для торрентов задается параметром Порт для входящих подключений (Listen Port) в настройках либо ключем запуска сервера --torrentaddr (:32000 127.0.0.1:443 etc)

**Comment by apnagaev** [comment]
а можно этот ключ каким-то образом использовать в докере?

**Comment by tsynik** [comment]
> а можно этот ключ каким-то образом использовать в докере?

по настройке докера - к докеру
