### ISSUE TITLE
Просьба сделать возможность делать Backup библиотеки торрентов

### ISSUE THREAD

**Issue by YoshiKill** [YouROK/TorrServer#241]
Приветсвую, хотел бы предложить реализовать идею с возможностью делать бэкап своей библиотеки уже добавленных торрентов. 
Казалось бы пустяк, но при разных переездах на другое железо или банально сваленый софт, потом практически невозможно или очень сложно опять добавлять всё что уже было добавлено.

**Comment by DaMaNic2022** [comment]
> Приветсвую, хотел бы предложить реализовать идею с возможностью делать бэкап своей библиотеки уже добавленных торрентов. Казалось бы пустяк, но при разных переездах на другое железо или банально сваленый софт, потом практически невозможно или очень сложно опять добавлять всё что уже было добавлено.

Там один файл config.db, просто копируете его и бэкап готов.
