### ISSUE TITLE
Torrent close by timeout

### ISSUE THREAD

**Issue by ElizarovEugene** [YouROK/TorrServer#242]
День добрый, сооружаю интеграцию со своим проектом TorrentMonitor, столкнулся с проблемой, что торренты удаляются через 5 минут после добавления автоматически, с сообщение из заголовка
```
2023/04/10 12:20:03 UTC0 Create cache for: Die.Hart.S02E05.720p.rus.LostFilm.TV.mp4 9b3ad9aef9b2fe0a0f1e0a508af2f736b63c7b29
2023/04/10 12:20:03 UTC0 save to db: 9b3ad9aef9b2fe0a0f1e0a508af2f736b63c7b29
2023/04/10 12:25:03 UTC0 Torrent close by timeout 9b3ad9aef9b2fe0a0f1e0a508af2f736b63c7b29
2023/04/10 12:25:03 UTC0 Close cache for: 9b3ad9aef9b2fe0a0f1e0a508af2f736b63c7b29
```
Не нашёл ничего по этому поводу в настройках.
Добавляю ссылкой на Torrent-файл
http://_address_/stream/fname?link=_torrentfile_&save&stat

**Comment by tsynik** [comment]
> Не нашёл ничего по этому поводу в настройках.

В данном логе нет удаления торрента, только его отключение. Если в базе его после отключения не остается - значит эта база возможно работает в режиме только-чтение и он по факту не сохраняется изначально. Других мыслей нет.

**Comment by ElizarovEugene** [comment]
Да, уже подсказали по поводу --rdb

**Comment by tsynik** [comment]
> Да, уже подсказали по поводу --rdb

Таким образом, это ожидаемое поведение.
