### ISSUE TITLE
Веб интерфейс не работает в K-meleon 75...76.4.7

### ISSUE THREAD

**Issue by DaMaNic2022** [YouROK/TorrServer#243]
При попытке открыть страницу сначала подгружает меню, потом вываливается в пустой экран. Брал K-meleon разных версий, последнюю скачивал с http://kmeleonbrowser.org/forum/read.php?19,154431, без разницы - все то же самое.
Проверил старые версии Torrserver, что то видно, пусть и с ошибками отображения, с версии 0.96

**Comment by tsynik** [comment]
> При попытке открыть страницу сначала подгружает меню, потом вываливается в пустой экран. Брал K-meleon разных версий, последнюю скачивал с http://kmeleonbrowser.org/forum/read.php?19,154431, без разницы - все то же самое.

более странного браузера не нашлось? торрсервер не будет работать везде, но его веб исправно отображается в большинстве современных браузеров
