### ISSUE TITLE
Поддержка RSS лент

### ISSUE THREAD

**Issue by sheldhur** [YouROK/TorrServer#246]
Такая возможность есть в большинстве торрент клиентов из коробки или через плагины, при этом можно с помощью регулярок или по точным совпадениям фильтровать необходимые раздачи.
![image](https://user-images.githubusercontent.com/4166193/232098638-443236eb-3b16-42ec-ac25-a513b3a1237e.png)

Почти все торрент трекеры имеют RSS ленту, всякие индексаторы торрент сайтов тоже отдают результат в виде ленты. Я видел у вас поиск по рутору, который как я понял у некоторых нет возможности использовать, т.к. он требует много памяти, а RSS лента решила бы эту проблему кмк. 

Плюс видел уже несколько прослоек к TorrServer которые именно этим и занимаются, читают RSS ленту и добавляют результат в TorrServer

**Comment by tsynik** [comment]
> Плюс видел уже несколько прослоек к TorrServer которые именно этим и занимаются, читают RSS ленту и добавляют результат в TorrServer

И что мешает их использовать? rss-лента для сервера не актуальна, только для клиента
