### ISSUE TITLE
Torrserver удаляет постеры

### ISSUE THREAD

**Issue by Noperkot** [YouROK/TorrServer#247]
Начиная с версии MatriX.114 торрсервер стал негативно относится к некоторым постерам и удаляет ссылки на них из сохраняемых из веб-интерфейса торрентов.
Постеры удаляются либо через несколько минут после добавления торрента, либо по ручному дропу.
До 112-й версии включительно такой проблемы нет.

Примеры таких постеров:

https://i3.imageban.ru/out/2021/05/11/700bf0aa88d8222da4e996c38ed1e7dd.gif ([отсюда](http://rutor.info/torrent/656220/manifest_deklaracija_manifest-01-04x01-44-iz-62-2018-2022-web-dlrip-lostfilm))

https://i120.fastpic.org/big/2022/1010/58/4a982a129eb564f2da9aecd4ad1bd358.webp ([отсюда](https://rutracker.org/forum/viewtopic.php?t=6268611))

https://i121.fastpic.org/big/2023/0213/db/07b931c4ac7a76cdfa911a685b8becdb.webp ([отсюда](https://torrent.by/64662/Maska-04x01-05-2023-WEBRip-ot-Files-x))

**Comment by tsynik** [comment]
> Примеры таких постеров:

Это сделано было для безопасности, на данный момент поддерживаются только постеры в png и jpeg
https://github.com/YouROK/TorrServer/blob/master/server/torr/utils/webImageChecker.go

**Comment by Peligro1886** [comment]
.jfif можно было бы добавить

**Comment by tsynik** [comment]
fixed with https://github.com/YouROK/TorrServer/commit/59bcfe3843f7bd01903dd39fb509f21b306bc5aa
