### ISSUE TITLE
Update docker repo

### ISSUE THREAD

**Issue by galgofa** [YouROK/TorrServer#249]
May i ask you to update docker repo with new version please ?

**Comment by tsynik** [comment]
> May i ask you to update docker repo with new version please ?

it will be updated on next release

**Comment by Anton-Ka** [comment]
> 
> it will be updated on next release

I also want to follow this question.
I wanted to update the server (currently version MatriX.112), but nothing changes.
I ran the following list of commands:
```
sudo systemctl stop torrserver.service
curl -s https://raw.githubusercontent.com/YouROK/TorrServer/master/installTorrServerLinux.sh | sudo bash
sudo systemctl start torrserver.service
```
It's right?
