### ISSUE TITLE
Просмотр сериалов

### ISSUE THREAD

**Issue by Vagrant2001** [YouROK/TorrServer#250]
Спасибо за приложение. 
Прошу добавить функционал по более удобному просмотру сериалов. Интересует автоматическая предзагрузка следующей серии в рамках максимального текущего буфера. Сейчас при переходе на следующую серию приходиться ждать заново предзагрузки.

**Comment by tsynik** [comment]
Серии одного сериала находятся в пределах торрента и следуют политике его загрузки.

**Comment by Vagrant2001** [comment]
Да, они в одном торренте, но загрузка останавливается на текущей серии. Загрузка новой серии происходит только когда к ней обращается плеер.
