### ISSUE TITLE
[FR] Добавить опцию убрать из интерфейса кнопку "Выключить". 

### ISSUE THREAD

**Issue by filimonic** [YouROK/TorrServer#251]
Прошу добавить опцию убрать из интерфейса кнопку "Выключить" через параметры запуска

![image](https://user-images.githubusercontent.com/2893566/233747342-9306abf4-268b-430c-9121-a728f23222c0.png)

**Comment by tsynik** [comment]
Кнопка выключить имеет в действии подтверждение выключения воизбежание случайного нажатия и не имеет проблем отрисовки интерфейса.
