### ISSUE TITLE
FFPROBE

### ISSUE THREAD

**Issue by Fox-llc** [YouROK/TorrServer#252]
Не работает FFPROBE.![Screenshot_2023-04-24-12-59-23-18_83432c9f305f1e592f7ec43af1da4619.jpg](https://user-images.githubusercontent.com/123845684/233949587-83580c82-5810-4a5b-9f14-a805373e362c.jpg)

![Screenshot_2023-04-24-12-59-36-70_83432c9f305f1e592f7ec43af1da4619.jpg](https://user-images.githubusercontent.com/123845684/233949599-5cf8b716-0ef2-4b12-b683-98c77dd97d74.jpg)

**Comment by tsynik** [comment]
Известная проблема в последних андроидах, к серверу отношения не имеет. ffprobe работает в windows, linux, osx, и в Android в зависимости от версии: после 11-го может не работать на устройствах с  SElinux в режиме enforced. Исправить это на стороне сервера скорее всего не возможно.

**Comment by Fox-llc** [comment]
Тогда зачем добавлять не работающую функцию в Android клиент?

**Comment by tsynik** [comment]
> Тогда зачем добавлять не работающую функцию в Android клиент?

то, что она не работает у вас, не означает, что она не работает у других.

**Comment by Fox-llc** [comment]
Тогда как решить эту проблему?

**Comment by tsynik** [comment]
> Тогда как решить эту проблему?

использовать клиент c ffprobe на устройстве с другой прошивкой Android разве что, либо на ПК, WPS etc
