### ISSUE TITLE
Иногда лог файл растет до бесконечности

### ISSUE THREAD

**Issue by mshakurov** [YouROK/TorrServer#256]
ОС - debian. 
TorrServer запущен в докере, базовом (ghcr.io/yourok/torrserver:latest). 
Пользуюсь сервером часто, по dlna  с телевизора. 
Все всегда было ОК.
Но вот оставил комп без внимания на 2 недели (отпуск). Вернулся - на компе 0 байт.
Пришлось в режиме восстановления искать виновника - **лог файл TorrServer вырос, заполнив весь диск**.
Жаль не увидел содержимого лог файла, спешил восстанвоить комп....
Но, думаю, что стоит обратить внмание на эту проблему...

**Comment by tsynik** [comment]
Это вероятно был разовый сбой при получении некорректного файла базы rutor. Исправлено в 123-м релизе.
