### ISSUE TITLE
Постеры (доп функция или через запрос http://127.0.0.1:8090/stream/fname?link=...&save&title=...&poster=

### ISSUE THREAD

**Issue by IGNATOV93** [YouROK/TorrServer#257]
Доброго времени суток .Делаю себе бота для поиска торрентов ,и добавления их в торрсервер мой .Но вот проблема что постеры не могу добавить .Если добавлять вручную через сайт Matrix ,после ввода ссылки и написания названия .Автоматически постер подхватывается .Можно как то сделать это через подобный запрос ?http://127.0.0.1:8090/stream/fname?link=...&save&title=...&poster= 
или какой то запрос по поиск постеров в торрентах ,на которых нет постеров ?

**Comment by tsynik** [comment]
> Доброго времени суток .Делаю себе бота для поиска торрентов ,и добавления их в торрсервер мой .Но вот проблема что постеры не могу добавить .Если добавлять вручную через сайт Matrix ,после ввода ссылки и написания названия .Автоматически постер подхватывается

TorrServer в вебе использует api tmdb и делает запрос туда, работает это не у всех, не работает у тех, у кого доступ к tmdb заблокирован ими (Россия). Вам нужно реализовать подобный функционал самостоятельно в ваших скриптах.
