### ISSUE TITLE
Особенности удаленного управления параметрами сервера

### ISSUE THREAD

**Issue by krasnh** [YouROK/TorrServer#259]
```sh
% sudo ./TorrServer-linux-amd64_MatriX.123.1
=========== START ===========
TorrServer MatriX.123.1, go1.20.4, CPU Num: 4
2023/05/17 22:41:45 Check dns OK [64.233.161.105 64.233.161.103 64.233.161.106 64.233.161.104 64.233.161.147 64.233.161.99 2a00:1450:4010:c07::68 2a00:1450:4010:c07::67 2a00:1450:4010:c07::63 2a00:1450:4010:c07::69] <nil>
2023/05/17 22:41:45 Check web port 8090
2023/05/17 22:41:45 Start TorrServer MatriX.123.1 torrent v1.50.0
2023/05/17 22:41:45 Local IPs: [192.168.1.115]
2023/05/17 22:41:45 Check listen port 32000
2023/05/17 22:41:45 Set listen port 32000
2023/05/17 22:41:45 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/05/17 22:41:45 PublicIp4: 188.64.133.138
2023/05/17 22:41:45 Start web server at port 8090
2023/05/17 22:42:02 drop all torrents
2023/05/17 22:42:03 disconect
2023/05/17 22:42:03 connect
2023/05/17 22:42:03 Check listen port 32000
2023/05/17 22:42:03 Set listen port 32000
2023/05/17 22:42:03 Client config: {"CacheSize":67108864,"ReaderReadAHead":5,"PreloadCache":0,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":0,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":true,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/05/17 22:42:03 PublicIp4: 188.64.133.138
2023/05/17 22:42:04 end set settings
2023/05/17 22:42:06 Update rutor db
2023/05/17 22:42:23 Load rutor db
2023/05/17 22:42:31 Index rutor db
2023/05/17 22:42:35 Torrents count: 335546
2023/05/17 22:42:35 Indexed words: 95722
```
 
--------

После запуска ./TorrServer-linux-amd64_MatriX.123.1, я включаю поиск по Rutor, командой `curl -s --json "{\"action\":\"set\",\"sets\":{\"EnableRutorSearch\":true}}" http://localhost:8090/settings`.
Как можно видеть, включается "EnableRutorSearch", но и меняются "ReaderReadAHead", "PreloadCache" и "RetrackersMode".

Что это и зачем я так "измываюсь"? ) Есть bash-скрипт, который:
- копирует из буфера название фильма
- подставляет в `http://localhost:8090/search/?query=` и выдает нужные раздачи rutor
- далее, копируется hash фильма/сериала и подставляется в плеер, `mpv "http://localhost:8090/stream/fname?link=XXXXXXXXXXX&m3u&fromlast"`
- и т.д. и т.п.
Так же, я включаю и выключаю "EnableRutorSearch" командой curl из скрипта, чтобы не загружать RAM, когда поиск не нужен.

----

Так вот вопрос, может я делаю неправильно и посредством _curl_ не самый лучший способ удаленного изменения параметров торрсервера. И есть более правильный и простой способ, а главное описанный в доках, и этот способ я в упор не вижу. )
Или придется подставлять в curl сразу весь массив параметров.

**Comment by tsynik** [comment]
> Так вот вопрос, может я делаю неправильно и посредством curl не самый лучший способ удаленного изменения параметров торрсервера. И есть более правильный и простой способ, а главное описанный в доках, и этот способ я в упор не вижу. )
> Или придется подставлять в curl сразу весь массив параметров.


Именно, массив настроек изменяется только целиком, поэтому надо сначала получить текущие настройки, изменить  нужное и сохранить результат.
