### ISSUE TITLE
Ошибка при установке на TrueNAS-13.0-U4

### ISSUE THREAD

**Issue by Dom2306** [YouROK/TorrServer#260]
В конце установки выдаёт ошибку:

Error: TorrServer had a failure Exception:
GitCommandError Message: Cmd("git)
failed due to: exit code(1) cmdline: git
checkout master stderr: 'error: pathspec
master' did not match any file(s) known
to git Partial plugin destroyed

**Comment by tsynik** [comment]
Не понятно, каким образом это к torrserver. Релизные бинарные файлы для всех архитектур самодостаточны и не используют git.

**Comment by Dom2306** [comment]
Я установливаю в стандартных настройках. Может есть какие-то рекомендации (инструкции). Я не силен в коде и не понимаю о чем идёт речь.

**Comment by tsynik** [comment]
> Я установливаю в стандартных настройках. Может есть какие-то рекомендации (инструкции). Я не силен в коде и не понимаю о чем идёт речь.

Как поставить сервер на linix или freebsd написано в README.md - https://github.com/YouROK/TorrServer#linux-on-vps-install--configure--uninstall-script

Так же с вопросами по установке можно обратиться в Telegram-канал @TorrServe

**Comment by Dom2306** [comment]
В truenas core он идёт как плагин, вроде все просто, но что-то идёт не так! 
Спасибо, попробу поискать ответ в телеграме.
