### ISSUE TITLE
Возможность сделать новую функцию в андроид версию 

### ISSUE THREAD

**Issue by IGNATOV93** [YouROK/TorrServer#262]
Доброго времени суток. Если когда либо будет возможность сделать, было бы не плохо. При открытие фильма или серии,когда зажимаешь нажатием сделать бы копировать ссылку для воспроизведения файла. Такой функционал есть в веб версии.

**Comment by tsynik** [comment]
В вебе сервера эта функция реализована, в клиенте за ассоциации открытия ссылок отвечает ОС
