### ISSUE TITLE
v123 TorrServer странно работает на MiTV Stick Full HD

### ISSUE THREAD

**Issue by gOuTM** [YouROK/TorrServer#265]
Привет!

Регулярно обновляю как клиент Matrix, так и Torrserver, но не так давно столкнулся с вполне повторяемой (в моих условиях) проблемой, и так как всё ещё верю, что обратная связь может помочь делать классные вещи, о делюсь. Возможно, проблема началась на v122, но в любом случае, речь пойдёт о v123.

Итак, в качестве основного устройства у меня довольно непримечательный MiTV Stick Full HD. Проблема проявляется следующим образом: в какой-то произвольный момент плеер будто-бы теряет поток от TorrServe.

В плеере это выглядит примерно так:
![Torrserve123-Виму10](https://github.com/YouROK/TorrServer/assets/3069440/83aaac51-4425-4ccc-9bd3-d5802dd5a204)

А в визуализации кэша Torrserve примерно (у меня остался не самый показательный скриншот — но количество заполненных блоков "впереди" и степень их заполнения абсолютно непринципиально) так:
![Torrserve123LiveCache](https://github.com/YouROK/TorrServer/assets/3069440/f15531a2-d2ff-4f9c-90cf-7a4b8b50d9ce)

Все настройка TorrServe "по умолчанию".

То есть происходит следующее. В какой-то произвольный момент фильма — от 2 минут до ~20 происходит фриз, Виму при этом показывает, что в его собственном кэше ещё что-то есть, а примерно секунд через 10 этот кэш сбрасывается на 0. И в целом всё. Фриз продолжается какое-то время, Виму пытается что-то подгружать (а можно даже поставить воспроизведение на паузу, чтобы кэш полностью подгрузился), но на нормальное воспроизведение выйти уже не получится. При этом интерфейс самого плеера не тормозит (такое бывает, когда кэш сильно большой, и некорректная работа вызвана тормозами самого устройства — но я это уже проходил).

Выглядит ровно так, что не хватает скорости. Но при этом веб-интерфейс Torrserve показывает, что кэш при этом ещё есть.

Что было сделано самостоятельно, чтобы исправить/локализовать проблему.
(1) VLC ведёт себя точно также.
(2) Уменьшение/увеличение кэша/предзагрузки в настройках TorrServe — не оказывает влияние.
(3) Уменьшение таймаута для торрентов (у меня была теория, что они подвисают и в итоге Torrserve просто не успевает тянуть из того, что ещё "не повисло") — не оказывает влияния.
(4) Уменьшение/увеличения кэша предзагрузки в Виму — не оказывает влияние.
(5) Установка v123 Torrserver на находящийся в той же локальной сети Synology 216j — не оказывает влияние.

Что решило проблему:
Установка на Synology 216j Torrserve v121(!)

Не знаю, на 4PDA на любой подобный вопрос отправляют читать FAQ — но если эта проблема решается так просто чтением раздела для чайников, можете подсказать где конкретно про это прочитать, чтобы больше не отвлекать уважаемых людей? Заранее спасибо!

UPD: Вот, нашёл более показательный скриншот на момент возникновения фриза:
![Torrserve123CacheDetails](https://github.com/YouROK/TorrServer/assets/3069440/2645f31a-4688-48f2-9ced-ddcdf3c7a760)

**Comment by tsynik** [comment]
Проверьте работоспособность с актуальным релизом TorrServer
