### ISSUE TITLE
panic: io.Copy will get stuck

### ISSUE THREAD

**Issue by asxtray** [YouROK/TorrServer#266]
2023/06/01 12:34:59 End preload: d1198ad1667e85f780b212acacddcaab77234e9a Peers:[ 4 ] 4 / 13
panic: io.Copy will get stuck

goroutine 5221299 [running]:
github.com/anacrolix/torrent/storage.Piece.ReadAt({{0xfe7260?, 0xc00400ba40?}, {0xc003630980?, 0xc00149b8b0?}}, {0xc00256c000, 0x4000, 0x8000}, 0x3fc000)
        /Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.49.1/storage/wrappers.go:89 +0x375
io.(*SectionReader).Read(0xc000f74420, {0xc00256c000?, 0x2?, 0xc0039c3f70?})
        /usr/local/go/src/io/io.go:513 +0x54
io.(*LimitedReader).Read(0xc00397db30, {0xc00256c000?, 0x4000?, 0x8000?})
        /usr/local/go/src/io/io.go:477 +0x45
io.copyBuffer({0xfdeea0, 0xc00397db18}, {0xfdede0, 0xc00397db30}, {0x0, 0x0, 0x0})
        /usr/local/go/src/io/io.go:427 +0x1b2
io.Copy(...)
        /usr/local/go/src/io/io.go:386
io.CopyN({0xfdeea0, 0xc00397db18}, {0xfdee40?, 0xc000f74420}, 0x400000)
        /usr/local/go/src/io/io.go:362 +0x9a
github.com/anacrolix/torrent/storage.Piece.WriteTo({{0xfe7260, 0xc00400ba40}, {0xc003630980, 0x1b6}}, {0xfdeea0, 0xc00397db18})
        /Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.49.1/storage/wrappers.go:51 +0x186
github.com/anacrolix/torrent.(*Torrent).hashPiece(0xc002786000, 0x1b6)
        /Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.49.1/torrent.go:1012 +0x4fa
github.com/anacrolix/torrent.(*Torrent).pieceHasher(0xc002786000, 0x1b6)
        /Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.49.1/torrent.go:2202 +0x75
created by github.com/anacrolix/torrent.(*Torrent).tryCreatePieceHasher
        /Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.49.1/torrent.go:2161 +0x12b

**Comment by asxtray** [comment]
When rewinding forward few times in a row

**Comment by tsynik** [comment]
> When rewinding forward few times in a row

are you using memory or disk cache? looks like it's storage issue with disk read

**Comment by asxtray** [comment]
storage cache. VM in the cloud. Reproducible

**Comment by tsynik** [comment]
> storage cache. VM in the cloud. Reproducible

so, it's transport issue. it's recommended use memory cache with torrserver. if you don't have enough memory, use disk swap to extend it. memory cache don't have such panics. anyway, here's nothing to be done with torrserver itself, so closed.
