### ISSUE TITLE
Не работает v124 на Synology DS213j 

### ISSUE THREAD

**Issue by JoyZzzzz** [YouROK/TorrServer#269]
https://github.com/vladlenas/Synology-TorrServer/issues/15

На Synology DS213j (MARVELL Armada 370) DSM 6.2.4-25556 Update 7 была установлена версия 123 и работало все без проблем. А вот версия Synology-TorrSrver MatriX.124 не стартует. 
Судя по логу не стартует веб сервер. Ни автоматом, ни при ручном запуске.

Start without authorization
=========== START ===========
TorrServer MatriX.123, go1.20.3, CPU Num: 1
2023/06/05 22:04:36 UTC0 Check dns OK [209.85.233.99 209.85.233.147 209.85.233.106 209.85.233.105 209.85.233.104 209.85.233.103 2a00:1450:4010:c03::6a 2a00:1450:4010:c03::93 2a00:1450:4010:c03::63 2a00:1450:4010:c03::68]
2023/06/05 22:04:36 UTC0 Check web port 8090
2023/06/05 22:04:36 UTC0 Start TorrServer MatriX.123 torrent v1.49.1
2023/06/05 22:04:36 UTC0 Local IPs: [192.168.50.100]
2023/06/05 22:04:36 UTC0 Check listen port 32000
2023/06/05 22:04:36 UTC0 Set listen port 32000
2023/06/05 22:04:36 UTC0 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/06/05 22:04:37 UTC0 PublicIp4: 89.0.0.*
2023/06/05 22:04:37 UTC0 Start web server at port 8090
Stop

Start without authorization
=========== START ===========
TorrServer MatriX.124, go1.20.3, CPU Num: 1
2023/06/07 21:13:56 UTC0 Check dns OK [142.250.185.164 2a00:1450:4001:811::2004]
2023/06/07 21:13:56 UTC0 Check web port 8090
2023/06/07 21:13:56 UTC0 Start TorrServer MatriX.124 torrent v1.52.0
2023/06/07 21:13:56 UTC0 Local IPs: [192.168.50.100]
2023/06/07 21:13:56 UTC0 Check listen port 32000
2023/06/07 21:13:56 UTC0 Set listen port 32000
2023/06/07 21:13:56 UTC0 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/06/07 21:13:56 UTC0 PublicIp4: 89.0.0.*
Stop

Start without authorization
=========== START ===========
TorrServer MatriX.124, go1.20.3, CPU Num: 1
2023/06/07 21:19:16 UTC0 Check dns OK [142.250.185.164 2a00:1450:4001:811::2004]
2023/06/07 21:19:16 UTC0 Check web port 8090
2023/06/07 21:19:16 UTC0 Start TorrServer MatriX.124 torrent v1.52.0
2023/06/07 21:19:16 UTC0 Local IPs: [192.168.50.100]
2023/06/07 21:19:16 UTC0 Check listen port 32000
2023/06/07 21:19:16 UTC0 Set listen port 32000
2023/06/07 21:19:16 UTC0 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}
2023/06/07 21:19:16 UTC0 PublicIp4: 89.0.0.*

**Comment by tsynik** [comment]
у меня не мыслей в чем может быть причина, ничего в коммитах от 123 до 124 версии нет кмк что могло бы вызвать такое поведение. на других arm7 подобного поведения не наблюдается.

**Comment by JoyZzzzz** [comment]
Попробовал запускать бинарники [TorrServer-linux-arm7] 120, 123 и 124 версий. Все запускаются кроме 124. У последней версии не стартует web server.

**Comment by JoyZzzzz** [comment]
Версия 124.OE запускается и работает

**Comment by YouROK** [comment]
Исправлено в новом движке
