### ISSUE TITLE
Не работает TorServer 1.24 под mips

### ISSUE THREAD

**Issue by mic7131** [YouROK/TorrServer#270]
Не стартует 1.24, заменил на 1.23, всё нормально работает 

root@dm7080:~# /usr/bin/TorrServer
2023/06/09 00:54:08 ffprobe and avprobe not found in $PATH
=========== START ===========
TorrServer MatriX.124, go1.20.3, CPU Num: 4
2023/06/09 00:54:08 Check dns OK [172.217.169.132 2a00:1450:4017:814::2004] <nil>
2023/06/09 00:54:08 Check web port 8090
2023/06/09 00:54:08 Start TorrServer MatriX.124 torrent v1.52.0
2023/06/09 00:54:08 Local IPs: [192.168.1.5]
2023/06/09 00:54:08 Check listen port 32000
2023/06/09 00:54:08 Set listen port 32000
2023/06/09 00:54:08 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0}

**Comment by YouROK** [comment]
Исправлено в новом движке
