### ISSUE TITLE
error client on windows server 2016

### ISSUE THREAD

**Issue by serjsat** [YouROK/TorrServer#271]
2023/06/11 15:38:13 Create cache for: Ekspress.2022.WEB-DL.1080p.ExKinoRay.mkv 51eeefe5c59530fa783eba51d993b50796b7324b
[2023-06-11 15:41:09 +0300  WRN] *torrent.PeerConn 0xc00798ea80: received invalid reject [request={432 {2637824 16384}}, peer=*torrent.PeerConn 0xc00798ea80 [id="-TR2940-GPxlAwK(SEfZ", exts=0000000000180005 (ltep, fast, dht, 1 unknown), v="Transmission/2.94"]] [github.com/anacrolix/torrent peerconn.go:826]
2023/06/11 15:49:13 Close cache for: 51eeefe5c59530fa783eba51d993b50796b7324b
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0xe682ce
]
goroutine 650547 [running]:
github.com/anacrolix/torrent/storage.Piece.ReadAt({{0x0?, 0x0?}, {0xc03780a380?, 0x0?}}, {0xc00963a000, 0x4000, 0x4000}, 0x138000)
	/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/storage/wrappers.go:84 +0x1ee
github.com/anacrolix/torrent.(*Torrent).readAt(0xc0002ee000, {0xc00963a000?, 0xc000204500?, 0xc00ee18660?}, 0x0?)
	/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/torrent.go:1433 +0x14d
github.com/anacrolix/torrent.(*PeerConn).readPeerRequestData(0xc01288ca80, {0x14d2fa0?, {0x0?, 0x38040?}})
	/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/peerconn.go:661 +0x7f
github.com/anacrolix/torrent.(*PeerConn).peerRequestDataReader(0xc01288ca80, {0x70dfd0?, {0xc0?, 0x10899a6?}}, 0xc02479d460)
	/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/peerconn.go:601 +0x309
created by github.com/anacrolix/torrent.(*PeerConn).onReadRequest
	/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.0/peerconn.go:586 +0x63b

Помогите пожалуйста разобраться, или я что неправильно делаю?. Клиент часто крашится..

**Comment by tsynik** [comment]
> Помогите пожалуйста разобраться, или я что неправильно делаю?. Клиент часто крашится..

Тут происходит попытка чтения данных торрента после закрытия кеша этого торрента. Возможно, дело в плеере или приложении что его использует. Или ошибка в текущей версии библиотеки torrent.

**Comment by tsynik** [comment]
Если проблема воспроизводится в актуальном релизе TorrServer - сообщите об этом.
