### ISSUE TITLE
100% utilization of 2 CPU cores after The connection has been broken due to keep-alive activity

### ISSUE THREAD

**Issue by VictorLoktev** [YouROK/TorrServer#274]
Version: Matrix.124 TorrServer-windows-amd64.exe
Steps are:
1) delete config.db
2) run the server
Server is not used at all - no torrents or UI requests.

The server works fine until the following message in a console:

`2023/06/29 15:24:16 error reading Socket PacketConn: read udp6 [::]:32000: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.`

Any combination of time, port, and TCP version produces the same result:
2 CPU cores are fully utilized by the server.
At this time there is no disk activity.
Time to time network activity could present or be zero.

Last time the server start sending small pockets to 50-100 adresses. Default settings but up/down network limits, IPv6 and timeout=300.

---

Версия: Matrix.124 TorrServer-windows-amd64.exe
Файл config.db удален перед запуском сервера.
Стандартные настройки изменены в части IPv6, лимитах отдачи и приемки, таймаута отключения торрента.
Торренты и UI у сервера не запрашивались.

Несколько часов сервер молчал и ресурсов не потреблял, пока не появилось сообщение

`2023/06/29 15:24:16 error reading Socket PacketConn: read udp6 [::]:32000: wsarecvfrom: The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress.`

С этого момента два ядра CPU полностью загружены сервером без передыха. Не перестает, пока мне не надоест слушать гудение вентиляторов и я не перезапускаю сервер.
Вовремя нагрузки на CPU дисковой активности нет, нулевая.
Сетевая активность либо нулевая, либо сервер отправляет данные небольшими пакетами в сотню разных мест.

У меня два предположения.
Либо сервер подвержен атакам снаружи, после чего превращается в бот и начинает слать пакеты куда не должен.
Либо после "connection has been broken" входит в бесконечный цикл.
Принудительное отключение машины от сети нагрузку на CPU не снижает.
И монитор ресурсов не показывает наличие у программы TCP подключений, что означает, что отправляются UDP пакеты.

**Comment by tsynik** [comment]
https://github.com/YouROK/TorrServer/issues/227#issuecomment-1451259478 related

**Comment by VictorLoktev** [comment]
Thank you!
Switching off the mTP is really helped me!
