### ISSUE TITLE
[Feature request] Security improvement: add explicit network interface binding

### ISSUE THREAD

**Issue by vassoz** [YouROK/TorrServer#279]
Such configuration option will prevent the IP exposure by binding the server to a VPN interface explicitly.

**Comment by tsynik** [comment]
> Such configuration option will prevent the IP exposure by binding the server to a VPN interface explicitly.

You can use TorrentAddr server startup param for that purpose. By default it's :32000 but you can explicitly define which address and port torrent will work with, ex. 127.0.0.1:32777
