### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by spvkgn** [YouROK/TorrServer#28]
Sometimes TorrServer tab's memory usage grows to over 1Gb.
Ubuntu 20.04, Firefox, TorrServer 1.1.77 with default settings.

![mem](https://user-images.githubusercontent.com/4147135/98690184-7dedd980-238e-11eb-964e-a6723c1d42ed.png)

**Comment by YouROK** [comment]
https://github.com/golang/go/issues/37569#issue-572952099
Need compile with older version of go (go 1.11.x)

**Comment by spvkgn** [comment]
@YouROK I'm using the binary from releases page, as far as can see it compiled with golang 1.11.13
