### ISSUE TITLE
Неправельный путь для  retracker.local

### ISSUE THREAD

**Issue by GentleFly** [YouROK/TorrServer#280]
[Здесь](https://github.com/YouROK/TorrServer/blob/736b993617509b8474f1a3534dd2578678bb2dc8/server/torr/utils/torrent.go#L18C2-L18C27) неправельный путь "http://retracker.local/".

На основании того, что самый популярный [bittorrent-tracker](https://github.com/webtorrent/bittorrent-tracker) на github, использует дополнительный путь "/announce", должен быть http://retracker.local/announce.

**Comment by tsynik** [comment]
Анонс на локальном ретрекере может быть где угодно, в том числе и в корне
