### ISSUE TITLE
new torrents are being deleted 1.24

### ISSUE THREAD

**Issue by IGNATOV93** [YouROK/TorrServer#281]
Good time of day.New torrents are deleted after being added via the Http Api of Topserver .Version 1.24 was put through a script .
Here's what I have in the log
2023/08/13 21:12:17 UTC0 Create cache for: The.Little.Mermaid.2023.WEB-DL.1080p.seleZen.mkv 83c9f30d7d5e36f04ff79dfb246c0233e9780377
2023/08/13 21:12:17 UTC0 save to db: 83c9f30d7d5e36f04ff79dfb246c0233e9780377
2023/08/13 21:12:18 UTC0 Create cache for: John.Wick.Chapter.4.2023.D.BDRip.2.93Gb.MegaPeer.rus 18ae8230ff2c9330f599bef3ffe2965bd9ec27d0
2023/08/13 21:12:18 UTC0 save to db: 18ae8230ff2c9330f599bef3ffe2965bd9ec27d0
2023/08/13 21:12:19 UTC0 Create cache for: Fast.X.2023.720p.MA.WEB-DL.ExKinoRay.mkv 072f1ea06dc372cb7720255c9c134398ba2fa3bd
2023/08/13 21:12:19 UTC0 save to db: 072f1ea06dc372cb7720255c9c134398ba2fa3bd
2023/08/13 21:12:21 UTC0 Create cache for: Sympathy.For.The.Devil.2023.WEB-DL.1080p.seleZen.mkv b6762f74648d59eeea554dbf03837118525c392d
2023/08/13 21:12:21 UTC0 save to db: b6762f74648d59eeea554dbf03837118525c392d
2023/08/13 21:12:22 UTC0 Create cache for: Kung.fu.zherebets.2023.WEB-DL.1080p.ELEKTRI4KA.UNIONGANG.mkv 3581fa16039cbfc411d5f026472e4f6a48c8846a
2023/08/13 21:12:22 UTC0 save to db: 3581fa16039cbfc411d5f026472e4f6a48c8846a
2023/08/13 21:12:24 UTC0 Create cache for: Guardians.of.the.Galaxy.Vol.3.2023.720p.AMZN.WEB-DL.ExKinoRay.mkv 763603bd6f14d387d44b1b5e92c57696683338ad
2023/08/13 21:12:24 UTC0 save to db: 763603bd6f14d387d44b1b5e92c57696683338ad
2023/08/13 21:12:28 UTC0 Torrent close by timeout 903f48c2d0d4c3e96ea3569dde25ccbe342ff779
2023/08/13 21:12:28 UTC0 Close cache for: 903f48c2d0d4c3e96ea3569dde25ccbe342ff779
2023/08/13 21:17:18 UTC0 Torrent close by timeout 83c9f30d7d5e36f04ff79dfb246c0233e9780377
2023/08/13 21:17:18 UTC0 Close cache for: 83c9f30d7d5e36f04ff79dfb246c0233e9780377
2023/08/13 21:17:19 UTC0 Torrent close by timeout 18ae8230ff2c9330f599bef3ffe2965bd9ec27d0
2023/08/13 21:17:19 UTC0 Close cache for: 18ae8230ff2c9330f599bef3ffe2965bd9ec27d0
2023/08/13 21:17:19 UTC0 Torrent close by timeout 072f1ea06dc372cb7720255c9c134398ba2fa3bd
2023/08/13 21:17:19 UTC0 Close cache for: 072f1ea06dc372cb7720255c9c134398ba2fa3bd
2023/08/13 21:17:21 UTC0 Torrent close by timeout b6762f74648d59eeea554dbf03837118525c392d
2023/08/13 21:17:21 UTC0 Close cache for: b6762f74648d59eeea554dbf03837118525c392d
2023/08/13 21:17:22 UTC0 Torrent close by timeout 3581fa16039cbfc411d5f026472e4f6a48c8846a
2023/08/13 21:17:22 UTC0 Close cache for: 3581fa16039cbfc411d5f026472e4f6a48c8846a
2023/08/13 21:17:24 UTC0 Torrent close by timeout 763603bd6f14d387d44b1b5e92c57696683338ad
2023/08/13 21:17:24 UTC0 Close cache for: 763603bd6f14d387d44b1b5e92c57696683338ad
Everything works fine on version 1.20 , but it is not normal to install it on the new server with autoloading .Or is there a script with this version ?

**Comment by tsynik** [comment]
don't see any torrent deletions from this log
