### ISSUE TITLE
Возможность переименовать уже добавленный торрент.

### ISSUE THREAD

**Issue by santus118** [YouROK/TorrServer#282]
Приветствую, комрад, столкнулся с кривым добавлением, подумалось о полезной фиче...

<img width="487" alt="2023-08-14 18_23_35-TorrServer MatriX" src="https://github.com/YouROK/TorrServer/assets/82486186/6e0e2fd9-1dca-4c0e-8d4f-fc2995d04e54">

**Comment by tsynik** [comment]
возможно установить любой тайтл для добавленного торрента нажав на постер
