### ISSUE TITLE
Установка TorrServer на роутер ASUS (кеширование на флешку)

### ISSUE THREAD

**Issue by aymalov** [YouROK/TorrServer#283]
Я прочитал в интернете, что существует возможность поставить TorrServer на роутер 
- Keenetic (https://telegra.ph/TorrServer-MatriX-s-avtozapuskom-cherez-skript-Keenetic-37-09-18)
- Еще какой-то (https://www.linksysinfo.org/index.php?threads/need-help-installing-torrserver-on-arm-router.76340/)

Может кто-то в курсе, как можно установить TorrServer на роутер ASUS?

Обратил внимание, что установка Transmission на ASUS возможна. (https://www.youtube.com/watch?v=-Id-6GlsNos&t=2592s)

Прошу поделиться способами, если такие есть.

**Comment by tsynik** [comment]
> Прошу поделиться способами, если такие есть.

TorrServer включен в entware-ng. Но запускать TorrServer на роутере - плохая идея, так как он требователен к ресурсам оборудования. Минимальное количество оперативной памяти для хранения кеша в ней - от 512МБ. В случае использования кеша на диске - оперативной памяти должно быть не менее 256МБ а диск должен быть быстрым - обычная флешка не подойдет. Только HDD или SSD.

**Comment by aymalov** [comment]
Я взял ASUS TUF Gaming AX4200
https://www.asus.com/networking-iot-servers/wifi-routers/asus-gaming-routers/tuf-gaming-ax4200/techspec/
- 2.0 GHz quad-core processor
- 256 MB Flash
- 512 MB RAM

Этой мощности должно хватить чтобы поднять TorrServer с кэшем на внешний диск/ флешку.

Вопрос, можно ли вообще ставить приложения на роутер ASUS, и, если можно, то как. В интеренете не особо смог найти информации по этому поводу, поэтому создал тему тут.

Мне это нужно в первую очередь, чтобы смотреть торренты на телевизоре Samsung Tizen. Насколько я понял, на них нельзя поднимать TorrServer в отличие от LG и Android TV. Если все же на Samsung можно поднять - напишите пожалуйста как.

**Comment by tsynik** [comment]
> Этой мощности должно хватить чтобы поднять TorrServer с кэшем на внешний диск/ флешку.

Да, на таком железе шансы есть. Про флешку писал выше - не подойдет.

> Вопрос, можно ли вообще ставить приложения на роутер ASUS,

Обычно можно, копать в сторону entware-ng. И это в тематические форумы и группы по вашему роутеру.

**Comment by aymalov** [comment]
Окей, спасибо за совет. Буду искать в этом направлении.

Если кто еще прочитает эту тему и захочет поделиться инструкциями - буду очень признателен.

**Comment by izzzgoy33** [comment]
> Окей, спасибо за совет. Буду искать в этом направлении.
> 
> Если кто еще прочитает эту тему и захочет поделиться инструкциями - буду очень признателен.

Для стоковой прошивки AsusWRT есть простой способ включить поддержку Entware: [https://github.com/jacklul/asuswrt-scripts/blob/master/asusware-usb-mount-script/README.md](https://github.com/jacklul/asuswrt-scripts/blob/master/asusware-usb-mount-script/README.md). Но лучше перейти на OpenWRT.
