### ISSUE TITLE
Пропадают постеры

### ISSUE THREAD

**Issue by seba1213** [YouROK/TorrServer#284]
TorrServer-linux-amd64[554]: 2023/08/24 00:02:55 add torrent file file
TorrServer-linux-amd64[554]: 2023/08/24 00:02:55 Create cache for: Star.Trek.Strange.New.Worlds.S02E03.1080p.rus.LostFilm.TV.mk>
TorrServer-linux-amd64[554]: 2023/08/24 00:02:55 save to db: b02f252333678fb13840547dd5d4790a17be9b09
TorrServer-linux-amd64[554]: 2023/08/24 00:02:57 Error decode image: image: unknown format
TorrServer-linux-amd64[554]: 2023/08/24 00:07:55 Torrent close by timeout b02f252333678fb13840547dd5d4790a17be9b09
TorrServer-linux-amd64[554]: 2023/08/24 00:07:55 Close cache for: b02f252333678fb13840547dd5d4790a17be9b09

происходит это в момент закрытия кеша, ссылка на постер пропадает, ссылка (пока она есть) без каких либо параметров в конце.

**Comment by tsynik** [comment]
> Error decode image: image: unknown format

говорит о том, что формат изображения не поддерживается сервером, либо у него нет доступа к источнику изображения для проверки его валидности
