### ISSUE TITLE
webui: scrollbar appears when torrent title takes four lines of text, even if text fits.

### ISSUE THREAD

**Issue by filimonic** [YouROK/TorrServer#285]
**Description**:<br/>Scrollbar appears when torrent title takes four lines of text, even if text fits.
![image](https://github.com/YouROK/TorrServer/assets/2893566/9cb9bd3f-5229-48b7-8b5a-e220d1c01216)

**Expected behavior:**<br/>No vertical scrollbar seen when text takes up to 4 lines, as all text is visible.

**Actual behavior:**<br/>Vertical scroll is visible when there are exactly four lines of text in some browsers

**Affected browsers** (some):<br/>
* Chrome 116.0.5845.141 : ⚠️problem exists
* Edge 116.0.1938.69 : ⚠️problem exists
* Firefox 117.0b8 : ✅no problem exists

**Proposed solution:** add `min-height: 4lh` for `description-torrent-title`. LH units are [supported by ~80% of internet users](https://caniuse.com/mdn-css_types_length_lh).

**Comment by tsynik** [comment]
I't not so easy to fix, because torrent card have different layouts and font size on different screens. So just short the title by pressing on cover, if you don't like scrollbars.
