### ISSUE TITLE
Add optional IMDB / TMDB API key

### ISSUE THREAD

**Issue by cocool97** [YouROK/TorrServer#286]
Hey, 

What do you think of adding an optional IMDB (or TMDB, or something else) as a server optional configuration parameter to let users get films / series informations when adding (or even after) a torrent ?

This could even be done automatically if the file name matches a given predicate.

I can add support if you think this is a revelant feature.

**Comment by tsynik** [comment]
> What do you think of adding an optional IMDB (or TMDB, or something else) as a server optional configuration parameter to let users get films / series informations when adding (or even after) a torrent ?
> 
> This could even be done automatically if the file name matches a given predicate.
> 
> I can add support if you think this is a revelant feature.

TMDB key already used in torrserver web for searching torrent's posters on add. It can be defined on compile time with .env variable. Look here: https://github.com/YouROK/TorrServer/tree/master/web#torrserver-web-client

**Comment by cocool97** [comment]
Ok, I did not see this option.

But there is still an issue with that... This is set only at compile time, but when using prebuilt release binaries this cannot be added.

This is why I'd like to make it configurable at runtime, and this would be used to retrieve even more informations 

Let me know what do you think of it !

**Comment by YouROK** [comment]
It will overload the functionality. There is a separate field for storing information about the torrent

**Comment by TheRealMaN** [comment]
Can I use my API key for TMDB using torrserver docker container? Didn't find this on docs. Please add the support for custom API key to be set in the settings?
