### ISSUE TITLE
Крашится с ошибкой

### ISSUE THREAD

**Issue by VOVAiS** [YouROK/TorrServer#289]
После выхода из просмотра торрента крашится со ошибкой

> stderr:%20panic%3A%20runtime%20error%3A%20invalid%20memory%20address%20or%20nil%20pointer%20dereference%0Astderr%3A%20%5Bsignal%20SIGSEGV%3A%20segmentation%20violation%20code=0x1%20addr=0x30%20pc=0x556d30%5D%0Astderr%3A%20%0Astderr%3A%20goroutine%20742339%20%5Brunning%5D%3A%0Astderr%3A%20github.com/anacrolix/torrent/storage.Piece.ReadAt(%7B%7B0x0?,%200x0?%7D,%20%7B0x4000c1c500?,%200x7fbc237f18?%7D%7D,%20%7B0x40084ae000,%200x22cb2c0?,%200x4000%7D,%200x11c000)%0Astderr:%20%09/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.5/storage/wrappers.go:84%20+0x1a0%0Astderr:%20github.com/anacrolix/torrent.(*Torrent).readAt(0x40215e4a80,%20%7B0x40084ae000?,%200x0?,%200xf3fe0?%7D,%200x400450c200?)%0Astderr:%20%09/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.5/torrent.go:1433%20+0xe8%0Astderr:%20github.com/anacrolix/torrent.(*PeerConn).readPeerRequestData(0x400e658000,%20%7B0xb98870?,%20%7B0x0?,%200x2300500?%7D%7D)%0Astderr:%20%09/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.5/peerconn.go:661%20+0x7c%0Astderr:%20github.com/anacrolix/torrent.(*PeerConn).peerRequestDataReader(0x400e658000,%20%7B0x816c4?,%20%7B0x0?,%200x5cdf2c0?%7D%7D,%200x4018d184e0)%0Astderr:%20%09/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.5/peerconn.go:601%20+0x240%0Astderr:%20created%20by%20github.com/anacrolix/torrent.(*PeerConn).onReadRequest%20in%20goroutine%20741749%0Astderr:%20%09/Users/yourok/go/pkg/mod/github.com/anacrolix/torrent@v1.52.5/peerconn.go:586%20+0x560

**Comment by tsynik** [comment]
Это было исправлено в актуальном коде torrserver, будет в релизе и есть в тестовых сборках в telegram

**Comment by VOVAiS** [comment]
Не подскажите группу?
