### ISSUE TITLE
В скрипте для Linux меняешь на 80 порт и не открывается GUI.

### ISSUE THREAD

**Issue by Fox-llc** [YouROK/TorrServer#292]

**Comment by tsynik** [comment]
Порты до 1024 требуют запуска сервера от root на большинстве дистрибутивов. Нужно править скрипт установки и менять пользователя torrserver на root для использования привелигированных портов. либо этот порт уже занят в вашем конкретном случае.

**Comment by Fox-llc** [comment]
Как сменить пользователя после отработки скрипта?

**Comment by tsynik** [comment]
Параметры
User = $username
Group = $username

в /opt/torrserver/torrserver.service
