### ISSUE TITLE
What port does it open if I don’t want to use upnp?

### ISSUE THREAD

**Issue by SiNaPsEr0x** [YouROK/TorrServer#299]
Hello and thank you for the wonderful app... I would like to know which ports it uses by default since if you disable upnp it is not specified

**Comment by tsynik** [comment]
It's random autoselect or any static port which you can define in TorrServer settings via web or api. On previous TorrServer releases it was 32000 by default.

**Comment by SiNaPsEr0x** [comment]
![image](https://github.com/YouROK/TorrServer/assets/5438823/3fe7d541-bb54-4cfc-9967-bd1c7e6f6ac0)


Is impossible to set or is peer port?

**Comment by tsynik** [comment]
> ![image](https://github.com/YouROK/TorrServer/assets/5438823/3fe7d541-bb54-4cfc-9967-bd1c7e6f6ac0)
> 
> 
> Is impossible to set

It's always possible to set as any other settings option there. Check you don't run torrserver in read-only mode

**Comment by SiNaPsEr0x** [comment]
Is peer set port?

**Comment by tsynik** [comment]
> Is peer set port?

I don't understand. It's Peer listen port on your screen and 0 means random.

![Screenshot_2023-10-20-21-03-47-543.jpg](https://github.com/YouROK/TorrServer/assets/1551446/885691ed-a035-4073-ab22-cd2e6d635e7b)
