### ISSUE TITLE
[feature] allow to assign added torrents to customizeable groups or categories

### ISSUE THREAD

**Issue by chpasha** [YouROK/TorrServer#3]
since we can add multiple torrents to the list, they start to clutter at some point - it would be great if we could assign some groups/categories/tags to torrents and let them be shown in groups, for instances tv shows, football, etc.

**Comment by YouROK** [comment]
This is all implemented in the client, the server stores only the database and makes the stream. I do not want to make it a multitool

**Comment by chpasha** [comment]
> This is all implemented in the client

I cannot agree with you - think about it again for a second: we have a server, and it already manages a list of added torrents. If client implements grouping - it won't be able to sync this state to other clients. It is crucial that server stores some additional attributes - only than client, including web frontend can make use of them. 

> I do not want to make it a multitool

I understand. But you already support a list of added torrents. As soon as you do it  - you have to make this list at least minimally managable.  Just add the asc sorting and allow the client to change the torrent label - not the original name, stored in torrent, but any arbitrary. Please, it doesn't sound too complicated and has a lot of value

**Comment by YouROK** [comment]
I made a special application in which part of this was implemented, it was all in the client.
Говоришь по русский? Это все реализуется в клиенте, в серваке с каждым торрентом можно сохранять json в виде строки

**Comment by chpasha** [comment]
>Говоришь по русский?

Говорю :) . 

> Это все реализуется в клиенте

И да и нет. Клиентов как минимум 3 (тут под клиентом я понимаю любой интерфейс, через который можно добавлять контент) -  встроенный веб-клиент, андроид, коди. Все что один клиент сохранит локально, другие не увидят. Т.е. инфа по-любому должна на сервере лежать централизовано - на сервере добавляем еще одно поле к каждой записи, например "label" + endpoint для его модификации +  отдаем новое поле с остальной инфой клиенту. А дальше да, уже клиент должен с этим что-то уметь (отобразить/позволить изменить при добавлении или после). Имхо это полюбому полезно даже с той точки зрения, что торренты очень часто мусор в названии имеют, т.е. показывать список в таком виде это швах.

**Comment by YouROK** [comment]
Так я про это и говорю, есть уже к каждому торренты поле, в клиенте последнем уже и используется оно, категорий нет, но постеры и название есть
