### ISSUE TITLE
[Feature] Read medias without external mediaplayer

### ISSUE THREAD

**Issue by cocool97** [YouROK/TorrServer#300]
It would be nice if compatible medias could be played with an integrated player like exoplayer on Android (https://developer.android.com/codelabs/exoplayer-intro?hl=fr) or react-player on web (https://www.npmjs.com/package/react-player?activeTab=code)

Reading medias with external players force users to download such apps, even if video/audio formats are directly compatible with Web or Android players.

**Comment by YouROK** [comment]
If the web supports the format, the link will open in the built-in player. Doing the player separately will heavily load the program
