### ISSUE TITLE
Build NetBSD/arm7

### ISSUE THREAD

**Issue by damiva** [YouROK/TorrServer#302]
Could you please build torrserver for NetBSD/arm7 in the next realizes?

**Comment by YouROK** [comment]
OK

**Comment by damiva** [comment]
Привет! Пока нет NetBSD билдов....
Кстати новая проблема на билде linux-arm7 версии Матрикс.127: мой девайс не запускает этот билд (хотя ранние версии запускались), выдает ошибку при запуске:
runtime: this CPU has no floating point hardware, so it cannot run
this GOARM=7 binary. Recompile using GOARM=5.
