### ISSUE TITLE
Экспорт ссылок на торренты в базе торсервера  в текстовый файл. 

### ISSUE THREAD

**Issue by avia07** [YouROK/TorrServer#306]
Есть предложение добавить в будущие версии торсервера функцию выгрузки ссылок на торренты в текстовый файл. Многие ставят сервер на VPS/VDS  там никакой DLNA не работает идобавление торрентов в каталогизатор/плеер идет по ссылкам. Было бы классно иметь функцию выгрузки ссылок на торренты в базе торсервера одной кнопкой. Тем более сейчас некоторые плееры ( Инфуз) уже реализовали функциона загрузки  ссылок из файла. Спасибо. Просьба  рассмотреть такой вариант.
Ссылка на торрент (если я правильно называю вещи) находится   в каждом торренте по кнопке ИНФО - Копировать
То что копируем и хотелось бы получить  сразу со всей базы в один файл.   Или может какую утилиту для этого кто сделает.  Ссылка не на m3U !!!! Вот какого вида http://localhost:8090/stream/%D0%93%D1%80%D0%B0%D0%BD%20%D1%82%D1%83%D1%80%D0%B8%D0%B7%D0%BC%D0%BE.2023.WEB-DL.2160p.DV.mp4?link=1b1c09f78813688d499da4260028f8d16cae8eba&index=1&play

**Comment by YouROK** [comment]
Не пойму что нужно. Нужно выгрузить в файл на диск где находится ТоррСервер или нужно отдать по ссылке файл со списком "торрентов"?
Список "торрентов", тут тоже не понятно, нужно отдавать ссылки на проигрывание все файлов из всех торрентов или магнетов?
Если список всех файлов из всех торрентов, то отдавать нужно только музыку или видео или вообще все файлы?

Не очень понятно что нужно

**Comment by iDrimus** [comment]
Также хотел бы узнать о возможности получить список ссылок с конкретного торента, например в формате Infuse (.links) или текстовом. [Подробнее в теме форума с примером файла.](https://community.firecore.com/t/add-direct-urls-in-bulk/30900) При добавлении сериала, например, приходится копировать ссылку на каждую серию и вставлять в приложение, так как m3u плейлисты Infuse не воспринимает.

**Comment by avia07** [comment]
Есть для iphone скрипт для приложения "Команды" который вытаскивает все ссылки с торсервера и сохраняет их в файл .links а также сразу скармливает Инфузу. https://www.icloud.com/shortcuts/a994e83222ec41dbbd51b2cd5b89b4b8

**Comment by iDrimus** [comment]
Неплохое решение. Вопрос как использовать скрипт, если в моем случае сервер не на vps, а на старой андроид приставке, либо запущен локально на маке фоном.

**Comment by avia07** [comment]
Тоже работает. Прописываете адрес логин пароль убираете.

**Comment by Pavel2603** [comment]
I agree with you. The script is convenient. But if, for example, there is a large list of torrent files, the script takes a long time to run on VDS. It would be convenient to have a separate button for a specific torrent to create a .links file. Please consider adding such a button. Thank you in advance for your response.
![Example](https://github.com/YouROK/TorrServer/assets/158084607/579484ac-96e6-4d00-9369-c91fd9dfd7f6)
