### ISSUE TITLE
Не работает авторизация на Synology DSM 7.2 - 126

### ISSUE THREAD

**Issue by rrmt23** [YouROK/TorrServer#308]
Приветствую!

При установке пакета ставлю галочку, чтобы была авторизация.
Но после установки без учетных данных попадаю по ip:8090.

NAS Synology 7.2 920+, 126 версия amd64.

**Comment by tsynik** [comment]
адресуйте вопрос сюда https://github.com/vladlenas/Synology-TorrServer/issues
