### ISSUE TITLE
Не воспроизводятся внешние субтитры и внешние аудиодорожки

### ISSUE THREAD

**Issue by alexeynl** [YouROK/TorrServer#309]
Плейлист формируется со ссылками на субтитры и аудиодорожки, 

#EXTM3U
#EXTINF:0,[Erai-raws] Vinland Saga Season 2 - 01 [1080p].mkv
#EXTVLCOPT:input-slave=http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2001%20%5B1080p%5D.mka?link=556539d480ab08a99deb5f2889146f665627f24f&index=1&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2001%20%5B1080p%5D.mka?link=556539d480ab08a99deb5f2889146f665627f24f&index=25&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2001%20%5B1080p%5D.mka?link=556539d480ab08a99deb5f2889146f665627f24f&index=49&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2001%20%5B1080p%5D.ass?link=556539d480ab08a99deb5f2889146f665627f24f&index=73&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2001%20%5B1080p%5D.ass?link=556539d480ab08a99deb5f2889146f665627f24f&index=97&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2001%20%5B1080p%5D.ass?link=556539d480ab08a99deb5f2889146f665627f24f&index=121&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2001%20%5B1080p%5D.ass?link=556539d480ab08a99deb5f2889146f665627f24f&index=145&play#
http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2001%20%5B1080p%5D.mkv?link=556539d480ab08a99deb5f2889146f665627f24f&index=170&play
#EXTINF:0,[Erai-raws] Vinland Saga Season 2 - 02 [1080p].mkv
#EXTVLCOPT:input-slave=http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2002%20%5B1080p%5D.mka?link=556539d480ab08a99deb5f2889146f665627f24f&index=2&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2002%20%5B1080p%5D.mka?link=556539d480ab08a99deb5f2889146f665627f24f&index=26&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2002%20%5B1080p%5D.mka?link=556539d480ab08a99deb5f2889146f665627f24f&index=50&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2002%20%5B1080p%5D.ass?link=556539d480ab08a99deb5f2889146f665627f24f&index=74&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2002%20%5B1080p%5D.ass?link=556539d480ab08a99deb5f2889146f665627f24f&index=98&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2002%20%5B1080p%5D.ass?link=556539d480ab08a99deb5f2889146f665627f24f&index=122&play#http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2002%20%5B1080p%5D.ass?link=556539d480ab08a99deb5f2889146f665627f24f&index=146&play#
http://localhost:8090/stream/%5BErai-raws%5D%20Vinland%20Saga%20Season%202%20-%2002%20%5B1080p%5D.mkv?link=556539d480ab08a99deb5f2889146f665627f24f&index=171&play

но медиаплееры их не видят. Пробовал VLC на Windows, а также VLC и MXPlayer на андроиде.

Магнет ссылка на торрент:
magnet:?xt=urn:btih:556539d480ab08a99deb5f2889146f665627f24f&dn=Vinland.Saga.Season2.WEBRip.1080p

**Comment by tsynik** [comment]
все вопросы к медиаплеерам

**Comment by alexeynl** [comment]
> все вопросы к медиаплеерам

Медиаплееры тут не при чем, писал уже об этом https://github.com/YouROK/TorrServer/issues/40#issuecomment-1793839258:

Во первых, #EXTVLCOPT - это кастомный тег, который распознается только VLC медиаплеером, остальные медиаплееры о нем ничего не знают.
Во вторых, VLC отказалась от реализации воспроизведения внешних субтитров и видеодорожек M3U через #EXTVLCOPT input-slave из соображений безопасности.

Итого: нет никакого смысла генерить M3U плейлесты с #EXTVLCOPT input-slave тегом, как это сейчас реализовано torrserver, потому что ни один медиаплеер не поддерживает и не будет поддерживать это.

**Comment by tsynik** [comment]
>Медиаплееры тут не при чем

пишется с "ни", и именно плеер решает,  использовать ему предоставленную информацию, или нет

> Итого: нет никакого смысла генерить M3U плейлесты с #EXTVLCOPT input-slave тегом, как это сейчас реализовано torrserver, потому что ни один медиаплеер не поддерживает и не будет поддерживать это.

итого: нет никакого смысла рассказывать, что имеет смысл, а что нет - если Вы не нашли плеер, поддерживающий данный тег, это не значит, что его нет.

**Comment by pursvir** [comment]
@alexeynl если для вас это ещё актуально, я написал скрипт для MPV, который как раз парсит этот плейлист и автоматически подгружает дорожки для текущего проигрываемого видео. Посмотрите в моём профиле.
