### ISSUE TITLE
Unsolicited response received 

### ISSUE THREAD

**Issue by al3l** [YouROK/TorrServer#31]
Система Debian 10. В логах при воспроизведении циклически вылетает ошибка:

- Jan 16 08:43:34 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:43:34 Connect client
- Jan 16 08:43:34 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:43:34 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:43:47 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:43:47 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:43:53 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:43:53 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:44:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:44:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:44:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:44:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:45:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:45:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:45:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:45:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:46:12 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:46:12 Disconnect client
- Jan 16 08:46:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:46:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:46:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:46:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:47:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:47:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:47:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:47:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:47:36 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:47:36 Disconnect client
- Jan 16 08:48:06 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:48:06 Close cache for: cbb8cc8e3b1c44f6a4c1415a0f9f1b8a592c5df6
- Jan 16 08:48:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:48:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:48:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:48:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:49:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:49:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:49:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:49:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:50:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:50:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:50:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:50:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:51:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:51:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>
- Jan 16 08:51:32 srv TorrServer-linux-amd64[1701]: 2021/01/16 08:51:32 Unsolicited response received on idle HTTP channel starting with "HTTP/1.0 408 Request Timeout\r\nConnection: Close\r\nContent-Type: text/plain\r\nContent-Length: 37\r\nServer: github.com/truekenny/etracker\r\n\r\nd14:failure reason15:Request Timeoute"; err=<nil>

И сразу вопрос как можно заставить сервер писать логи в отдельный файл а не в syslog?

**Comment by YouROK** [comment]
Это ошибки соединения с трекером. В файл нужно перенаправлять вывод
