### ISSUE TITLE
Разный список торрентов для разных пользователей

### ISSUE THREAD

**Issue by Frew777** [YouROK/TorrServer#310]
Приветствую, использую TorrServer для семьи. Включена авторизация httpauth.

Можно ли сделать, что у каждого пользователя был свой список торрентов, иначе получается беспорядок. Либо приходится запускать отдельный сервер для каждого пользователя.

Спасибо.

**Comment by tsynik** [comment]
Нельзя. Именно разными серверами для разных пользователей и решается.

**Comment by Frew777** [comment]
Понял, но тогда хватило бы возможности сортировки по папкам или тегам как предлагали ранее.
