### ISSUE TITLE
Некорректно работает UPnP\DLNA

### ISSUE THREAD

**Issue by baradetsky** [YouROK/TorrServer#329]
Переустановил Torrserver Matrix до версии 128 - вообще неясно работает ли upnp\dlna. Но скорее не работает, потому что upnp-сниффер даже не показывает пакеты от него. Соответственно на устройствах не видно сервера. Перезагрузка торра и переприменение настроек ничего не дало( Раньше такая проблема тоже возникала, но как-то сама решалась непонятным образом

**Comment by tsynik** [comment]
DLNA работает на MatriX.128
<img width="824" alt="DLNA" src="https://github.com/YouROK/TorrServer/assets/1551446/8ec23851-879d-4bfd-8a17-dbc0f5552df2">
