### ISSUE TITLE
Stuck on getting torrent info when initializing from forkplayer

### ISSUE THREAD

**Issue by vukisz** [YouROK/TorrServer#33]
Hello. 
I am getting trouble with forkplayer. Added% torrserverURL% / playlistall / all.m3u to fork player and it resolves torrents. After clicking on torrent name instead torrent content files I am getting a long wait and a timeout. 
Opening torrserver UI from browser torrent is stuck on getting torrent info status and no files are displayed there either. Clicking drop button on torrserver UI and reloading torrent files is populated in torrserver web ui and status changes to torrent working. 
Then going back to forkplayer and clicking on same torrent it's also working and I can play it. 
But after couple of hours from fork player - same thing again

P.S. it's.only with latest beta. With stable fork player does not play at all.

**Comment by ramsay05** [comment]
I have the same issue. I launch the matrix server and when I search any torrent on TV forkplayer and click on it, it does not open.

**Comment by YouROK** [comment]
All questions to the fork player, I do not know how it opens the list and links
