### ISSUE TITLE
Скачивает стабильно медленнее, чем rtorrent или qbittorrent 

### ISSUE THREAD

**Issue by kt368** [YouROK/TorrServer#330]
Уже с год gробую смотреть 4K фильмы через torrserver, и у меня он никак не хочет качать на скоростях приближённых к тем, которые я вижу качая обычными клиентами, такими как rtorrent (Openwrt) и qbittorrent (Win10).
Например [вот эта](https://rutracker.org/forum/viewtopic.php?t=6230388) раздача на 180 ГБ.
Скорости скачивание:

- 30-80 Мбит/сек через torrserver на Win10 (release MatriX.128)
- 20 Мбит/сек на ТВ присатавке с amlogic s905x4
- 100 Мбит/сек качая через rtorrent на роутере
- под 250 Мбит/сек (ограничение моего интернет канала) через qbittorrent на Win10.

По настройкам: пробовал пробросить клиенту порт для входящих торрент соединений, пробовал увеличить ограничение на количество подключений до 100 (клиент запущен на I5-10600K 32GB RAM Win10).
Временами вижу до 80 Мбит/сек, но оптом снова опускается до 30. В итоге филь смотреть невозможно, постоянно фризы.
Подскажите, только я наблюдаю, что torrserver качает сильно медленнее, чем другие торрент клиенты?

**Comment by rze0** [comment]
@kt368 сейчас столкнулся с похожей проблемой, выше 30-40 не поднималось. Помогло следующее: сбросил настройки, и выставил такие - https://i.imgur.com/ntmlxQx.png 
итог - https://i.imgur.com/3rcgPkc.png

**Comment by tsynik** [comment]
Not an issue

**Comment by kt368** [comment]
Почему таск был закрыт? Никакие настройки не помогают, скорость все равно недостаточная для просмотра 4к фильмов с битрейтом >80 Мбит/сек. Лишь некоторые раздачи позволяют получить 60...80 Мбит/сек, хотя тот же rtorrent тянет все эти раздачи на скорости >100 Мбит/сек.

**Comment by tsynik** [comment]
> Почему таск был закрыт? Никакие настройки не помогают, скорость все равно недостаточная для просмотра 4к фильмов с битрейтом >80 Мбит/сек.

Это не проблема торрсервера, а ваша. Фильмы с битрейтом более 50 Мбит/с через торрсервер смотреть не стоит. Ничего улучшать в этом плане не планируется.

**Comment by kt368** [comment]
Хм, ясно. Я как раз и пробовал торрсервером смотреть фильмы c битрейтом более 50 Мбит/с, т.к. фильмы с меньшим битрейтом можно за 5-10 минут скачать и смотреть оффлайн, чего не скажешь про 50+ гигабайтные раздачи.
Ладно, жалко.
Спасибо.

**Comment by OnRaptor** [comment]
> Это не проблема торрсервера, а ваша. Фильмы с битрейтом более 50 Мбит через торрсервер смотреть не стоит. Ничего улучшать в этом плане не планируется.

Если не сложно ответить, а с чем это связано?

**Comment by tsynik** [comment]
> Если не сложно ответить, а с чем это связано?

как минимум с последовательной загрузкой данных.

**Comment by kt368** [comment]
Ну, для чистоты, qbittorrent с включенной последовательной загрузкой все равно качает намного быстрее...

**Comment by tsynik** [comment]
> Ну, для чистоты, qbittorrent с включенной последовательной загрузкой все равно качает намного быстрее...

им и пользуйтесь

**Comment by kt368** [comment]
Хм, а его можно использовать как торрсервер, чтоб он скачивал часть файла, видео плеер его потоково воспроизводил, и потом старые фрагменты файла удалялись?

**Comment by tsynik** [comment]
Про "старые удалялись" это врядли, а играть при последовательной загрузке шанс есть.
