### ISSUE TITLE
Добавить возможность скачивать торент файл из добавленого в библиотеку

### ISSUE THREAD

**Issue by YoshiKill** [YouROK/TorrServer#336]
Приветствую, хотел бы попросить добавить кнопку с возможностью скачивать торент файл из уже добавленного в библиотеку TorrServer. Бывает полезно когда нужно, что то скачать, а оригинальный файл или ссылка на раздачу потеряна или забыта. 
Кстати выводить ссылку на раздачу торента в каком то описании тоже было бы не лишним. 
Благодарю автора за труды.

**Comment by tsynik** [comment]
Magnet-ссылки добавленных раздач доступны в веб-интерфейсе torrserver, а так же в клиенте torrserve в меню Поделиться
