### ISSUE TITLE
Flatpak/Flathub build

### ISSUE THREAD

**Issue by faveoled** [YouROK/TorrServer#338]
Hello,

Could you publish your application to [Flathub](https://flathub.org/)? It's based on a cross-distro [Flatpak technology](https://docs.flatpak.org/en/latest/introduction.html).

Or: would you agree if someone else writes the necessary build files for you and sends them to the Flathub maintainers?

**Comment by YouROK** [comment]
> Or: would you agree if someone else writes the necessary build files for you and sends them to the Flathub maintainers?
I'm fine with it. 
I don't have time to do this.
