### ISSUE TITLE
The ability to group torrents by series and seasons.

### ISSUE THREAD

**Issue by tomandocubatas** [YouROK/TorrServer#344]
Good morning,
Would it be possible to group torrents by series and seasons? Right now, they are separate items, and I believe that grouping would be very interesting.
Thanks for your work!

**Comment by cocool97** [comment]
Would love to see that feature coming too !

**Comment by YouROK** [comment]
That should be done by the client, not the server.

**Comment by tomandocubatas** [comment]
Can you tell one cliente for this??
