### ISSUE TITLE
Экспорт/импорт списка торрентов

### ISSUE THREAD

**Issue by Hipokys** [YouROK/TorrServer#345]
Здравствуйте!
Было бы неплохо иметь возможность делать экспорт(backup) всех добавленных торрентов.

И импорт одним файлом, а не кучей ссылок, вручную, как сейчас.

При смене сервера замучился переносить.

**Comment by tsynik** [comment]
Для переноса списка торрентов достаточно скопировать config.db

**Comment by Hipokys** [comment]
Спасибо
