### ISSUE TITLE
[BUG]Версия 1.29 не запускается под win 7

### ISSUE THREAD

**Issue by Khanmgn69** [YouROK/TorrServer#348]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 22.04]
 - TorrServer Version [e.g. MatriX.129]

**Smartphone or tvbox on Android (please complete the following information):**
 - Device: [e.g. Ugoos am6]
 - OS: [e.g. Android 9]
 - TorrServer Version [e.g. MatriX.129]

**Additional context**

**Comment by filimonic** [comment]
Начиная с `go1.21.0` Windows 7 считается неподдерживаемой платформой для go ([ссылка](https://go.dev/doc/go1.21#windows)).

Начиная с `go1.21.5`, билды для Windows более не работают на Windows 7 или Windows Server 2008 R2. ([подробности](https://github.com/golang/go/issues/64622)).

<hr>

✔️[Matrix.124](https://github.com/YouROK/TorrServer/releases/tag/MatriX.128)
Последняя версия, собранная go c поддержкой Windows 7
Собрана в go1.20.3 

⚠️ [Matrix.128](https://github.com/YouROK/TorrServer/releases/tag/MatriX.128)
Не поддерживается, но, может быть, работает
Собрана go1.21.4

❌ [Matrix.129](https://github.com/YouROK/TorrServer/releases/tag/MatriX.129)
Не будет запускаться на Windows 7
Собрана go1.21.6 

<hr>

Количество Win7:
- в мире - [около 3%](https://gs.statcounter.com/windows-version-market-share/desktop/worldwide/#yearly-2024-2024-bar)
- в Европе - [чуть более 2%](https://gs.statcounter.com/windows-version-market-share/desktop/europe/#yearly-2024-2024-bar)
- в России - [около 3%](https://gs.statcounter.com/windows-version-market-share/desktop/russia/#yearly-2024-2024-bar)

<hr>

Поддержка Windows 7 закончилась
- [Microsoft: Январь 2020](https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962)
- [Google Chrome: Январь 2023](https://support.google.com/chrome/a/answer/7100626?hl=en)
- [Mozilla Firefox: Август 2023](https://support.mozilla.org/en-US/kb/firefox-users-windows-7-8-and-81-moving-extended-support)
- [Mozilla Firefox ESR: Сентябрь 2024](https://support.mozilla.org/en-US/kb/firefox-users-windows-7-8-and-81-moving-extended-support)
- [Go: Август 2023](https://go.dev/doc/go1.21#windows)

**Comment by filimonic** [comment]
Чисто на попробовать - собрал тут на go1.21.4 https://github.com/tsw7/torrserver-windows7/releases

**Comment by tsynik** [comment]
> Чисто на попробовать - собрал тут на go1.21.4 https://github.com/tsw7/torrserver-windows7/releases

master теперь собирается так же с go1.20 без ошибок

**Comment by stunndard** [comment]
try this: https://github.com/stunndard/golangwin7patch
