### ISSUE TITLE
Error on torr file

### ISSUE THREAD

**Issue by TheMasterDan** [YouROK/TorrServer#35]
root@x:/torrserver# 2021/03/03 22:39:51 Start TorrServer MatriX.83
2021/03/03 22:39:51 Find upnp port
2021/03/03 22:39:51 Set upnp port 32000
2021/03/03 22:39:51 Configure client: {"CacheSize":209715200,"PreloadBuffer":true,"ReaderReadAHead":70,"ForceEncrypt":true,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableIPv6":true,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":20,"DhtConnectionLimit":500,"PeersListenPort":0,"Strategy":0}
2021/03/03 22:39:51 Start web 8090
2021/03/03 22:39:51 UPnP discovery result ca3b9118-5da5-3db8-06e0-052db8c2b468/WANDevice/urn:upnp-org:serviceId:WANIPConn1/urn:schemas-upnp-org:service:WANIPConnection:1/http://192.168.1.111:52899/ctl/IPConn
2021-03-03 22:39:53 portfwd.go:31: discovered 1 upnp devices
2021-03-03 22:40:19 client.go:316: completed bootstrap, [{*dht.Server [dht server on [::]:32000]} {*torrent.Client [0xc0002b6580]} {dht.TraversalStats [{3445 469}]}]
2021/03/03 22:40:21 add torrent file file0
2021/03/03 22:40:22 Create cache for: Shorta.2020.BDRip.1080p.mkv e01b5e41e0bf62de4aa82a0ed2a7aeada397da15
2021/03/03 22:40:22 save to db: e01b5e41e0bf62de4aa82a0ed2a7aeada397da15
2021-03-03 22:40:33 client.go:316: completed bootstrap, [{*dht.Server [dht server on 0.0.0.0:32000]} {*torrent.Client [0xc0002b6580]} {dht.TraversalStats [{9436 6761}]}]
2021/03/03 22:40:43 add torrent file file0
2021/03/03 22:40:43 Create cache for: PoslednijBogatyr2WEBRip1080p.mkv 18ec4dd37f19044a81b34f99314b3e417de2f901
2021/03/03 22:40:43 save to db: 18ec4dd37f19044a81b34f99314b3e417de2f901
2021/03/03 22:40:46 add torrent file file0
2021/03/03 22:40:46 Create cache for: American.Gods.S03E07.1080p.rus.LostFilm.TV.mkv 29ff964233af0f27573d77462f0341549d961616
2021/03/03 22:40:46 save to db: 29ff964233af0f27573d77462f0341549d961616
2021/03/03 22:40:49 add torrent file file0
2021/03/03 22:40:49 Create cache for: Tom.Gerry.2021.WEB-DL.1080p.mkv 862e7c32ff62e9fcd054eb8d7f7fbf8830345a4d
2021/03/03 22:40:50 save to db: 862e7c32ff62e9fcd054eb8d7f7fbf8830345a4d

2021/03/03 22:41:07 [Recovery] 2021/03/03 - 22:41:07 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212 (0x4373ba)
/usr/local/go/src/runtime/signal_unix.go:734 (0x450232)
/space/Projects/GO/TorrServer/server/torr/torrent.go:354 (0x8fe880)
/space/Projects/GO/TorrServer/server/web/api/upload.go:69 (0x903fa8)
/home/yourok/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x8efd70)
/home/yourok/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x8efd57)
/home/yourok/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x8e768f)
/home/yourok/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x8e7676)
/home/yourok/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x8e72ac)
/usr/local/go/src/net/http/server.go:2887 (0x6cdc82)
/usr/local/go/src/net/http/server.go:1952 (0x6c986c)
/usr/local/go/src/runtime/asm_amd64.s:1371 (0x470660)

**Comment by YouROK** [comment]
Please give me file for test

**Comment by TheMasterDan** [comment]
In new version is OK
32000
2021/04/16 21:38:30 Configure client: {"CacheSize":209715200,"PreloadBuffer":true,"ReaderReadAHead":70,"ForceEncrypt":true,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableIPv6":true,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":20,"DhtConnectionLimit":500,"PeersListenPort":0,"Strategy":0}
2021/04/16 21:38:30 Start web 8090
2021/04/16 21:43:19 add torrent file file0
2021/04/16 21:43:19 Create cache for: Tom.Gerry.2021.WEB-DL.1080p.mkv 862e7c32ff62e9fcd054eb8d7f7fbf8830345a4d
2021/04/16 21:43:20 save to db: 862e7c32ff62e9fcd054eb8d7f7fbf8830345a4d
2021/04/16 21:43:51 Close cache for: 862e7c32ff62e9fcd054eb8d7f7fbf8830345a4d
2021/04/16 21:44:58 add torrent file file0
2021/04/16 21:44:58 Create cache for: Tom.Gerry.2021.WEB-DL.1080p.mkv 862e7c32ff62e9fcd054eb8d7f7fbf8830345a4d
2021/04/16 21:44:58 save to db: 862e7c32ff62e9fcd054eb8d7f7fbf8830345a4d
