### ISSUE TITLE
[Feature] [webui] Добавить легенду к карте кеша

### ISSUE THREAD

**Issue by filimonic** [YouROK/TorrServer#351]
**Is your feature request related to a problem? Please describe.**
Сейчас совершенно непонятно, что означают квадратики с буквами A, R, в рамочке, ...
![image](https://github.com/YouROK/TorrServer/assets/2893566/5446cc60-74e3-4971-9a07-3234811d4381)

**Describe the solution you'd like**
Добавить легенду к карте кеша, рядом с картой.

**Comment by tsynik** [comment]
эта информация не нужна пользователю, и была добавлена для разработки. проще просто отключить вывод приоритетов
