### ISSUE TITLE
[Feature] Option to add poster and name when API is used

### ISSUE THREAD

**Issue by and7ey** [YouROK/TorrServer#352]
When I upload a torrent file with API (http://192.168.1.1:8090/torrent/upload), I have to find the poster and the movie name manually. When I add the file thru web interface, the name and the picture are searched automatically.

It would be great to implement the same for API (like http://192.168.1.60:8090/torrent/upload?auto=true). I understand that mistakes are possible there.

**Comment by tsynik** [comment]
Find a poster is not torrserver task and can't be done automatically.

**Comment by and7ey** [comment]
But this is already done by web interface of TorrServer ;)
I understand that this is not easy task to repeat web-server part on backend.

**Comment by tsynik** [comment]
> But this is already done by web interface of TorrServer ;)

Web interface is user interface and user will choose poster from suggestions. It's not possible on api call.

**Comment by and7ey** [comment]
as I said, it is ok to automatically choose the first found poster (=mistakes are ok)

**Comment by tsynik** [comment]
> as I said, it is ok to automatically choose the first found poster (=mistakes are ok)

No, it's not ok

**Comment by and7ey** [comment]
I think it is better than nothing ;)

Once torrents are added thru API, can I update their posters in bulk thru web-interface? 
Can this functionality be added to your backlog?

**Comment by tsynik** [comment]
> Once torrents are added thru API, can I update their posters in bulk thru web-interface?
> Can this functionality be added to your backlog?

You can update any added torrent (title and its poster) through web interface

**Comment by and7ey** [comment]
> You can update any added torrent (title and its poster) through web interface
I haven't found a way to 
1) automatically do it (as it is done when torrent is added manually)
2) do it in bulk

Could you please clarify how it could be done? Thanks.

**Comment by TopperBG** [comment]
> > You can update any added torrent (title and its poster) through web interface
> > I haven't found a way to
> 
> 1. automatically do it (as it is done when torrent is added manually)
> 2. do it in bulk
> 
> Could you please clarify how it could be done? Thanks.

Click on the poster of torrent.
In bulk what you mean ?

**Comment by and7ey** [comment]
> Click on the poster of torrent. 
It requires me to input the poster url manually.
When I add the torrent file, it is suggested automatically,

> In bulk what you mean ?
Currently I have to update movies one by one.
The following scenario is expected:
1. I press `Bulk update` button
2. The interface goes thru all movies without poster 
3. It shows update screen for movie 1
4. When I press OK, it automatically shows update screen for movie 2
5. and so on, until all movies without posters are not updated

**Comment by TopperBG** [comment]
I can't understand why do you bother so about posters in TorrServer, which by meaning is middle-ware between frontend indexer/parser and player.

**Comment by and7ey** [comment]
> I can't understand why do you bother so about posters in TorrServer, which by meaning is middle-ware between frontend indexer/parser and player.

Good question ;) If it is there, I would prefer to have good picture ;). 
I think I recognize the movies by their posters. I use VLC on iOS and go to TorrServe web interface, choose the movie there and copy its link, then paste it into VLC.

**Comment by TopperBG** [comment]
> > I can't understand why do you bother so about posters in TorrServer, which by meaning is middle-ware between frontend indexer/parser and player.
> 
> Good question ;) If it is there, I would prefer to have good picture ;). I think I recognize the movies by their posters. I use VLC on iOS and go to TorrServe web interface, choose the movie there and copy its link, then paste it into VLC.

Ok but torrents are pushed to TorrServer by front-end (NUM, Lampa etc) and they are responsible to fullfill info into TS about torrent?

**Comment by and7ey** [comment]
> Ok but torrents are pushed to TorrServer by front-end (NUM, Lampa etc) and they are responsible to fullfill info into TS about torrent?

in my case they are pushed thru API myself (see the first post), there is no NUM or Lampa

**Comment by tsynik** [comment]
Once again. User must approve any suggested poster in torrserver web. Do it in bulk by yourself ;-)

**Comment by and7ey** [comment]
> Once again. User must approve any suggested poster in torrserver web. Do it in bulk by yourself ;-)

this approach - https://github.com/YouROK/TorrServer/issues/352#issuecomment-1935457047 - assumes that user approves each poster

**Comment by TopperBG** [comment]
PR are welcome :)
