### ISSUE TITLE
Add blackhole directory

### ISSUE THREAD

**Issue by Spp595** [YouROK/TorrServer#353]
Many torrent clients (qbitttorrent, deluge) have support for the blackhole folder. When a torrent file gets into it, it is automatically set for downloading. Is it possible to implement this in torrserver? Jacket also has such a function; it can add a torrent to the blackhole folder

**Comment by tsynik** [comment]
> Many torrent clients (qbitttorrent, deluge) have support for the blackhole folder. When a torrent file gets into it, it is automatically set for downloading. Is it possible to implement this in torrserver? Jacket also has such a function; it can add a torrent to the blackhole folder

It's already implemented. See --torrentsdir startup option.
