### ISSUE TITLE
Доработка скрипта для Linux

### ISSUE THREAD

**Issue by Fox-llc** [YouROK/TorrServer#354]
Добавить в скрипт для Linux установку Speedtest CLI, чтобы тестировать скорость на VPS.![Screenshot_2024-02-10-14-59-00-30_a87fd7db6caa850b517aa6fa9d2fcd0e.jpg](https://github.com/YouROK/TorrServer/assets/123845684/7e60c3c4-e9c0-4357-a563-ec11bb8407be)

**Comment by tsynik** [comment]
Для тестов есть специализированные утилиты и они не имеют отношения к торрсерверу. Не спидтестом единым. Мне например больше нравится bench.sh что использует тот же спидтест.
