### ISSUE TITLE
Samsung TV Hack

### ISSUE THREAD

**Issue by varlesh** [YouROK/TorrServer#36]
Привет, мой запрос сумбурный и все-таки...
Не будем лукавить, что большинство "народных" торрентов у нас XVID/DIVX, что является проблемой для нынешних WEB-плееров. Но обход найден в виде подмены ID и DESCRIPTION кодека в файле. Оказалось, что Samsung программно выпилила поддержку народных форматов (с 2018 года), но благодаря **cfourcc**  это все прекрасно можно решить. Но тут встает вопрос  о том, что файлы торрента у нас Socket или Pipe... и может быть лучшим решением было бы добавить опцию хакнуть этот AVI и заменить пару первых байт, перед транслированием в HTTP-поток.
Понимаю, что это дикий костыль и направлен чисто на самсунговский ТВ, но многим будет приятно иметь такую опцию.
Подобное уже обсуждалось в 4pda, как Visual AVI FourCC Changer

**Comment by YouROK** [comment]
Нужен пример файла, для теста

**Comment by varlesh** [comment]
[xvid-sample-video.tar.gz](https://github.com/YouROK/TorrServer/files/6128445/xvid-sample-video.tar.gz)
Команда смены ID и DESCRIPTION:
`cfourcc -u MP4V -d MP4V mp4v.avi`
Просмотр ID и DESCRIPTION:
`for f in *.avi; do cfourcc -i $f; done`

**Comment by varlesh** [comment]
Только что проверил оба файл в Samsung UE43TU8000UXRU, версия Tizen 5.5 через USB.
- **xvid.avi** Не воспроизводит, ошибка.
- **mp4v.avi** Воспроизводит.

**Comment by varlesh** [comment]
HEX-коды для замены.
ID:

- XVID - `0x58 0x56 0x49 0x44`
- xvid - `0x78 0x76 0x69 0x64`
- DIVX - `0x44 0x49 0x56 0x58`
- divx - `0x64 0x69 0x76 0x78`
- MP4V - `0x4d 0x50 0x34 0x56`

DESCRIPTION:

- vidsxvid - `0x76 0x69 0x64 0x73 0x78 0x76 0x69 0x64`
- vidsXVID - `0x76 0x69 0x64 0x73 0x58 0x56 0x49 0x44`
- vidsDIVX - `0x76 0x69 0x64 0x73 0x44 0x49 0x56 0x58`
- vidsdivx - `0x76 0x69 0x64 0x73 0x64 0x69 0x76 0x78`
- vidsMP4V - `0x76 0x69 0x64 0x73 0x4d 0x50 0x34 0x56`

**Comment by YouROK** [comment]
Если торрент действующий предоставите то будет вообще супер

**Comment by varlesh** [comment]
Да любой с рутора из топаю. Вот, к примеру:
`magnet:?xt=urn:btih:e29c0b1aa955bbf95ffbad5d4e8b29e74e4a03be&dn=rutor.info_%D0%94%D0%B5%D0%BD%D1%8C+%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%B0+%282021%29+WEBRip+%D0%BE%D1%82+ELEKTRI4KA+%7C+IVI&tr=udp://opentor.org:2710&tr=udp://opentor.org:2710&tr=http://retracker.local/announce`

**Comment by varlesh** [comment]
Формат: AVI
Качество: WEBRip
Видео: XviD, 1955 Kb/s, 720x304
Аудио: Russian: 48 kHz, AC3 Dolby Digital, 2/0 (L, R) ch, ~192 Kbps

**Comment by YouROK** [comment]
Я так понимаю если есть по определенным позициям слово xvid меняем его на mp4v?

**Comment by varlesh** [comment]
да, xvid и divx. Возможно в разных регистрах ... Надо гуглить встречается ли еще типа Xvid Divx и т.д.

**Comment by varlesh** [comment]
В HEX-редакторе любом в самом начале указывается ID и описание DESCRIPTION:
![image](https://user-images.githubusercontent.com/8083855/110937203-785bcc80-834b-11eb-93fb-9b7e2688c6b2.png)

**Comment by YouROK** [comment]
Да я уже посмотрел оба файла

**Comment by varlesh** [comment]
магнет, который я вам давал выше, вот его данные:
![image](https://user-images.githubusercontent.com/8083855/110937662-1fd8ff00-834c-11eb-843f-e9b4bf7e969f.png)

**Comment by YouROK** [comment]
Готово, если будут ошибки пиши

**Comment by varlesh** [comment]
Собрал с гита, вот такая ошибка вываливается:
```
2021-03-12 17:49:38 torrent.go:1527: piece failed hash: 10 connections contributed, [{*torrent.Client [0xc0002fa000]} {*torrent.Piece [583ca464f193ed38026b1fc031e91750fa666e77/0]} {*torrent.Torrent ["Огонь.2020.WEB-DLRip.  Files-x.avi"]}]
dsMP4V�[�������'�0strf((�0
                          MP4V

```

**Comment by varlesh** [comment]
Даже поменяв регистр, все равно ошибку хеша выбивает:
`if str == "XVID" || str == "DIVX" || str== "xvid" || str== "divx" {`
Видео не грузится:
```
2021-03-12 18:14:57 torrent.go:1527: piece failed hash: 6 connections contributed, [{*torrent.Client [0xc0000dd600]} {*torrent.Piece [583ca464f193ed38026b1fc031e91750fa666e77/0]} {*torrent.Torrent ["Огонь.2020.WEB-DLRip.  Files-x.avi"]}]
dsMP4V�[�������'�0strf((�0
                          MP4V
```

**Comment by varlesh** [comment]
можно прям на серваке проверить, открыв плейлист в vlc, mpv  и т.д.

**Comment by YouROK** [comment]
Про проверку хэша я и забыл

**Comment by YouROK** [comment]
Поправил

**Comment by varlesh** [comment]
ок, как проверю на самсунге, отпишусь

**Comment by varlesh** [comment]
при сборке, ошибку выдало:
`torr/storage/torrstor/cache.go:65:4: unknown field 'Hash' in struct literal of type Piece`

**Comment by YouROK** [comment]
Не залил остатки

**Comment by varlesh** [comment]
По предварительным тестам, на самсунге работает. Единственно в логах постоянно реконнект клиента...
```
2021/03/16 16:26:54 Connect client
2021/03/16 16:26:58 Disconnect client
2021/03/16 16:26:58 Connect client
2021/03/16 16:27:00 Disconnect client
2021/03/16 16:27:00 Connect client
2021/03/16 16:27:00 Disconnect client
2021/03/16 16:27:00 Connect client
2021/03/16 16:27:06 Disconnect client
2021/03/16 16:27:06 Connect client
```
А так видос прогружает и кажет. Пробовал Xvid
Большое спасибо за хак))

**Comment by YouROK** [comment]
Реконект из-за плеера, или что-то не нравится или просто такой плеер

**Comment by varlesh** [comment]
Ну главное хак сработал
