### ISSUE TITLE
Can't install it on TrueNAS-13.0-U6.1

### ISSUE THREAD

**Issue by bluesky576** [YouROK/TorrServer#360]
**Describe the bug**C

Can't install on TrueNAS-13.0-U6.1
Error: torr-server had a failure Exception: GitCommandError Message: Cmd('git') failed due to: exit code(1) cmdline: git checkout master stderr: 'error: pathspec 'master' did not match any file(s) known to git' Partial plugin destroyed.

**Comment by tsynik** [comment]
TrueNAS builds not an issue of this repository
