### ISSUE TITLE
Authentication problems/issues

### ISSUE THREAD

**Issue by arashtotti88** [YouROK/TorrServer#366]
Hi

I have been using TorrServer for a long time already, I have some problems/issues when I turn on the authentication on the first installation.
I can set username and password perfectly, but when I wanted to run a torrent link by emby ( or vlc on pc or any other players ) it doesn't recognize the link, and it won't play,
if I wanted to make it run I must keep the torrent file on my home page of TorrServer and it cannot be done when I have more than 10,000 movie links and at the end I must turn off the Authentication functions 

how should I fix this problems/issues?

in addition:
i run TorrServer on linux Debian 11
with
curl -s https://raw.githubusercontent.com/YouROK/TorrServer/master/installTorrServerLinux.sh | sudo bash

Start TorrServer in public read-only mode? (Yes/No) no
Enable TorrServer log output to file? (Yes/No) yes

thanks in advance

**Comment by tsynik** [comment]
> how should I fix this problems/issues?

You must authenticate to add torrent to torrserver in case Authentication is enabled. So, implement it before play, or don't use authentication.
