### ISSUE TITLE
Error getting metainfo from magnet link

### ISSUE THREAD

**Issue by dps123** [YouROK/TorrServer#37]
При добавлении magnet-ссылки. Процесс зависает на "Getting torrent info", а через минут 5 падает с ошибкой.

Логи:
`2021/03/08 18:45:28 Start TorrServer MatriX.83
2021/03/08 18:45:28 Configure client: {"CacheSize":209715200,"PreloadBuffer":true,"ReaderReadAHead":100,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":0,"DhtConnectionLimit":0,"PeersListenPort":32001,"Strategy":0}
2021/03/08 18:45:28 Start web 8090
2021/03/08 18:45:28 UPnP discovery result 65adec60-a77c-4a55-ac26-3e57c2b84408/WANDevice/urn:upnp-org:serviceId:WANIPConn1/urn:schemas-upnp-org:service:WANIPConnection:1/http://192.168.2.1:58716/ctl/IPConn
2021-03-08 18:45:30 portfwd.go:31: discovered 1 upnp devices
2021/03/08 18:45:39 add torrent magnet:?xt=urn:btih:E95E21C12DBA03819569E9A751F3147DFEFFC04C&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=%D0%A1%D1%82%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5%20%D0%B8%D0%B3%D1%80%D1%8B%20%2F%20Ransum%20Games%20(%D0%9F%D0%B0%D1%80%D1%80%D0%B8%D1%81%20%D0%A0%D0%B8%D0%B2%D0%B7%20%2F%20Parris%20Reaves)%20%5B2021%2C%20%D0%A1%D0%A8%D0%90%2C%20%D0%BA%D1%80%D0%B8%D0%BC%D0%B8%D0%BD%D0%B0%D0%BB%2C%20%D1%82%D1%80%D0%B8%D0%BB%D0%BB%D0%B5%D1%80%2C%20WEB-DLRip%5D%20DVO%20(Mallorn)%20%2B%20Sub%20Rus%2C%20Eng%20%2B%20Original%20Eng
2021-03-08 18:46:00 client.go:316: completed bootstrap, [{*dht.Server [dht server on 0.0.0.0:32001]} {*torrent.Client [0xc0000d9080]} {dht.TraversalStats [{9136 6703}]}]
2021/03/08 18:55:40 error add torrent: timeout connection torrent
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x8fce09]

goroutine 147848 [running]:
github.com/anacrolix/torrent.(*Torrent).InfoHash(...)
/home/yourok/go/pkg/mod/github.com/yourok/torrent@v0.0.0-20210302124413-ade31ee47747/t.go:14
server/torr.(*Torrent).progressEvent(0xc000383ce0)
/space/Projects/GO/TorrServer/server/torr/torrent.go:150 +0x329
created by server/torr.(*Torrent).watch
/space/Projects/GO/TorrServer/server/torr/torrent.go:141 +0xaa`

**Comment by YouROK** [comment]
Поправил
