### ISSUE TITLE
[BUG] При установке определённого буфера предзагрузки, торрент перестаёт скачиваться

### ISSUE THREAD

**Issue by moninahh** [YouROK/TorrServer#370]
OS: TorrServer-windows-amd64.exe
TorrServer Version: MatriX.130

При установке буфера предзагрузки 50%, торрент перестаёт скачиваться (после достижения этой отметки), а заново скачивать начинает только при расходовании этого буфера.

Например, кеш стоит 1024 МБ, а буфер предзагрузки 50% (512 МБ). При достижении отметки 512 МБ — торрент обрывается и скорость падает до нуля, и ждёт, пока не запустится проигрывание, и начнётся расходоваться буфер, и только после этого заново начинается скачивание (подключается к этому же торренту, ищет пиры и т.д). Из-за этого на "тяжёлых" фильмах (BDremux) быстро расходуются эти 512 МБ, а скорость не успевает разогнаться, чтобы избежать буферизации. Но, если нет этого обрыва скорости, а продолжается скачивание после достижения буфера предзагрузки, то буферизации нет, так как скорость наращивается постоянно.

Пример: до достижения буфера предзагрузки, скорость ~40-50 МБ, но из-за обрыва начинается разгоняться заново с нуля и не успевает достичь этих же 40-50 МБ до начала буферизации.

Поэтому я решил, чтобы устранить данную проблему: нужно установить общий кеш 1024 МБ, чтобы остановка скачивания произошла только по достижении этой отметки. А при достижении буфера предзагрузки должно только произойти перенаправление в видеоплеер и начало воспроизведения, но скачивание торрента продолжаться до установленного кеша (1024 МБ).

**Comment by tsynik** [comment]
При установке кеша в терабайт тоже работать не будет. Это не баг торрсервера. Поведение выше - ожидаемое. Для загрузки 1024МБ установить буфер предзагрузки 100%

**Comment by moninahh** [comment]
Так получается, что, установив любое значение в буфере (хоть — 50%, хоть — 100%), скорость будет обрываться при достижении этого значения. По моим многочисленным тестам именно это приводит к буферизации, как  я описал выше. Есть ли какая-то возможность реализации, чтобы торрент продолжал скачиваться при достижении буфера предзагрузки?
