### ISSUE TITLE
[BUG] Stream stops if I pause for more than a few seconds (minutes) in Kodi but also other clients.

### ISSUE THREAD

**Issue by puppinoo** [YouROK/TorrServer#371]
**Describe the bug**
As subjects states stream stops if I pause for more than a few seconds (minutes to be precise) in Kodi but also other clients.

**To Reproduce**
1. Open a stream and choose Kodi as client
2. After a few minutes when you are sure buffer is full stop the reproduction.
3. Wait a few minutes.
4. Resume play.
5. After a few seconds stream suddenly stops.

**Expected behavior**
After resuming the paused stream I should be able to play it until the end.

**Desktop (please complete the following information):**
 - OS: [e.g. Linux Ubuntu 23.10 on a VPS]
 - Docker container containing latest image.

**Comment by tsynik** [comment]
Probably you use torrserver with authorization enabled. In this case you need to add torrent to DB before or with play, to avoid such situations. Player can't re-add torrent as it can't authorize.
