### ISSUE TITLE
[Feature] Добавить дополнительную функцию для буфера предзагрузки

### ISSUE THREAD

**Issue by moninahh** [YouROK/TorrServer#372]
Исходя из этой [темы](https://github.com/YouROK/TorrServer/issues/370), предлагаю добавить дополнительную функцию (возможность) продолжения скачивания торрента без остановки при достижении буфера предзагрузки.

По моим многочисленным тестам именно это приводит к буферизации. Вы можете поверить это сами, и убедиться в этом.

**Comment by tsynik** [comment]
Для загрузки файлов торрента целиком используйте специализированные клиенты. TorrServer не для этого, и играет медиа любого размера без буферизации с настройками буферизации по умолчанию.

**Comment by moninahh** [comment]
Дело в том, что именно на файлах с большим битрейтом это очень заметно и сразу становится очевидно. Когда Вы начинаете загрузку любого торрента, то торрент не сразу же достигает максимальной скорости вашего интернета, а это происходит постепенно (понятное дело, что эта скорость достижения зависит от количества раздающих, но даже при огромном количестве раздающих, вы не получите максимальную скорость моментально после старта, — на это потребуется определённое время). Поэтому и существуют настройки по умолчанию, которые подходят, если у торрента очень много раздающих. Но если торрент не очень популярен, и имеет не такое огромное кол-во раздающих, тут нужно делать ставку на постепенное наращивание скорости и её удержание. К тому же в некоторых раздачах, у некоторых раздающих пиров, может быть тайм-аут на соединение (например, Вы подключились к этому пиру — он Вам отдаёт, если Вы отключаетесь от него, — то вновь к нему вы можете подключится через определённое кол-во времени, заданное этим пиром). Из-за этого так и происходит, как я описывал раннее. Поэтому, хоть ставить настройки по умолчанию, хоть 1024 МБ, — будет результат один и тот же, так как Вы не сможете подключится к тем немногим пирам, но которые отдают очень много.

Как я понимаю Вашу логику: Вы не хотите вникать в проблему углублённо (закрывая мои темы моментально, без обсуждения), и для Вас ответ, — что, в таких случаях, нужно скачивать на флешку целиком файл, и смотрите оттуда, а торрсервер предназначен для других целей. Но одно дело: подождать закачки этих же самых 1024 МБ (для наращивания скорости), которое занимает буквально 3 минуты (при гигабитном интернете), и начать просмотр, либо скачивать целиком 100-гиговый фильм полностью и ждать 20-30 минут, а то и больше.

Исходя из всего этого, я и предлагаю добавить эту небольшую, но очень важную функцию (например, в качестве пункта в настройках торрсервера, с возможностью выбора). Это сделать просто и легко, и нетрудозатратно: добавить данный пункт в настройках, — отключаться от торрента после достижения буфера предзагрузки / или продолжать качать без остановки.

**Comment by tsynik** [comment]
Дело в том, что это _уже_ реализовано. Для предварительной загрузки указанного кеша целиком есть кнопка Предзагрузка в вебе торрсервера, и параметр предзагрузки кеша при старте воспоизведения. И торрсервер сначала полностью предзагружает указанный кеш и только потом запускает воспроизведение. После перемотки же - ставите кино на паузу и ждете заполнения есть это критично. Но, еще раз - кеш торрсервера более к примеру 200-500 МБ бессмысленен на любом интернете и любом контенте.

**Comment by moninahh** [comment]
Например, я ставлю такие значения: «Размер кеша - 2048 МБ», «Буфер предзагрузки - 50% (1024 МБ)».

При достижении 1024 МБ, — торрсервер отключается от торрента, пока осуществляется переход в плеер. И пока не начнётся воспроизведение, он качать до 2048 МБ не начнёт. А я пишу о том, чтобы добавить возможность скачивания  без отключения от торрента.

**Comment by tsynik** [comment]
все эти действия бессмысленны, а для неотключения кеша без воспроизведения увеличивайте таймаут отключения торрента, к примеру 600 секунд это 10 минут хранения данных предзагрузки без ее воспроизведения

**Comment by moninahh** [comment]
Установил 600 секунд в «тайм-аут отключения торрента». Проблема осталась — во время перехода из торрсерв в видеоплеер происходит отключение от торрента на ~5 секунд, — скорость падает до 0 бит/с (это можно увидеть в «Информация о торренте» → «Скорость загрузки» в веб-интерфейсе торрсервера в браузере). Это происходит при любом значении кеша и буфера предзагрузки.
