### ISSUE TITLE
How to change password and username

### ISSUE THREAD

**Issue by ancylow** [YouROK/TorrServer#374]
Sure this is a noob question, but cannot find the option to change user name and password. I have torrserver installed with docker on a Synology NAS. 
And is possible to add more users with different privilege?

Thanks in advance, love your work

**Comment by puppinoo** [comment]
> Sure this is a noob question, but cannot find the option to change user name and password. I have torrserver installed with docker on a Synology NAS. And is possible to add more users with different privilege?
> 
> Thanks in advance, love your work

I have credentials saved into a file called accs.db . For me it's saved into torrserver folder but maybe it could be saved into home folder. Look for it.

Cheers..

**Comment by tsynik** [comment]
> I have credentials saved into a file called accs.db . For me it's saved into torrserver folder but maybe it could be saved into home folder. Look for it.

Why you use Docker when there is Synology packages of TorrServer at https://grigi.lt?

this file must be in torrserver settings dir with config.db, but the main thing is -a (--httpauth) startup key. You can add any amount of users - https://github.com/YouROK/TorrServer#authentication

for Docker - https://github.com/YouROK/TorrServer#environments check TS_HTTPAUTH

**Comment by ancylow** [comment]
> > I have credentials saved into a file called accs.db . For me it's saved into torrserver folder but maybe it could be saved into home folder. Look for it.
> 
> Why you use Docker when there is Synology packages of TorrServer at https://grigi.lt?
> 
> this file must be in torrserver settings dir with config.db, but the main thing is -a (--httpauth) startup key. You can add any amount of users - https://github.com/YouROK/TorrServer#authentication
> 
> for Docker - https://github.com/YouROK/TorrServer#environments check TS_HTTPAUTH

You are right. First time I installed it using docker, but then realize that exists all that packages so I made a new clean installation from grigi. sorry for my confusion.

The thing is that I don't know how can I access to that file (access.db) or how can I execute that command -a (--httpauth)

**Comment by tsynik** [comment]
> The thing is that I don't know how can I access to that file (access.db) or how can I execute that command -a (--httpauth)

auth can be enabled on package install without access to those options and auth file. Just remove it and reinstall.
