### ISSUE TITLE
[BUG] with docker container.

### ISSUE THREAD

**Issue by TheShadowMax** [YouROK/TorrServer#377]
Default example is not working.

RUN

`docker run --rm -d --name torrserver -p 8090:8090 ghcr.io/yourok/torrserver:latest`

error output :

```
root@localhost:~# docker logs 18de2d4e3f4e02205361ae6fa1ea795f24a60d710008764eee2e8b5c93e847db
sh: out of range
sh: out of range
sh: out of range
Running with: --path /opt/ts/config --logpath /opt/ts/log --port 8090 --torrentsdir /opt/ts/torrents
root@localhost:~# 
```

the container will not start.
please make corrections.

**Comment by rendaa** [comment]
MatriX.133t, same issue but container will start, the web UI works.
however, if I try to add any magnet link, browser shows an "OFFLINE" page, and torrserver container will not appear in "docker ps" outputs.
