### ISSUE TITLE
[BUG] Setting category via web on adding .torrent via file

### ISSUE THREAD

**Issue by tsynik** [YouROK/TorrServer#378]
**Describe the bug**
Category not saved if torrent added via web as .torrent file

**To Reproduce**
Add new torrent via web and set it's category

**Expected behavior**
Category must be added

**Desktop:**
 - OS: Any
 - TorrServer MatriX.130.4

**Additional context**
Category saved if torrent added via magnet link and don't saved if added via .torrent file from Web UI

@cocool97 something missing?

**Comment by tsynik** [comment]
fixed in 5922c7d

**Comment by cocool97** [comment]
Yes loading from torrent file has not been tested... Thanks for the fix !
