### ISSUE TITLE
При редактировании торрента затирается поле data

### ISSUE THREAD

**Issue by Noperkot** [YouROK/TorrServer#379]
Я хотел бы при добавлении торрента на торрсервер через api хранить в поле data некоторую информацию (адрес страницы трекера с которой торрент был добавлен). Но проблема в том, что при последующем редактировании этого торрента в веб-интерфейсе торрсервера (название, постер, категория) это поле затирается и весь мой функционал связанный с хранимой там информацией перестает работать.

На примере TorrServer MatriX.132:

После добавления торрента(через api) поле data содержит:
`{"TSA":{"srcUrl":"http://rutor.info/torrent/978921/djuna-chast-vtoraja_dune-part-two-2024-web-dlrip-1080p-ot-selezen-p"}}`

После выбора категории для этого торрента в веб-интерфейсе:
`{"TorrServer":{"Files":null}}`

**Comment by tsynik** [comment]
Вероятно исправлено в https://github.com/YouROK/TorrServer/commit/7a5d22b8bf5e83e2937883b7a9a4b9845a5c3830
