### ISSUE TITLE
Preload & kodi

### ISSUE THREAD

**Issue by Mutronics** [YouROK/TorrServer#38]
1. Коди, работает через плагин plugin.video.torrserve, в нем стоит пребуфферизация в размере кэша. 300 mb.
Если в коди нажать продолжить просмотр, то пребуфферизация начинается в начале файла, когда начинается просмотр, то резко начинается загрузка нужных блоков, и половина кэша почему-то остается вначале. Та же история с перемоткой, перемотал и половина кэша осталась где-то там.
https://ibb.co/xSnMKs5
2. Если передавать имя в ссылке (&title=) кириллицей, то файл отказывается воспроизводиться..
3. Раньше вместо FNAME отображалось имя воспроизводимого файла, теперь там всегда FNAME.
4. Очень плохо находит сиды, несмотря на то, что порт проброшен.

**Comment by YouROK** [comment]
1. Коди не закрывает соединение
2. Не понял про что это
3. Тоже не понял про что это
4. Движок не изменился, скорее всего поменялось что-то другое
