### ISSUE TITLE
а как вообще установить тс на андроид?

### ISSUE THREAD

**Issue by PlatonIvashin** [YouROK/TorrServer#382]
вот скачал файл для андроид амд64, а у него нет расширения. ставлю апк, ошибка. в зип архиве файлы непонятные.

**а что делать**

**Comment by tsynik** [comment]
сервер устанавливается через клиент TorrServe в разделе Обновление. Для доступа к выбору сервера нужно поместить его в папку Download на устройстве и 5 раз нажать на Удалить сервер
