### ISSUE TITLE
Fix file name when downloading a file

### ISSUE THREAD

**Issue by asidko** [YouROK/TorrServer#385]
First of all, thanks for a great project! I'm using it to download different files, not necessarily movies.

To get the file, I'm using `GET /play/{hash}/{id}` endpoint, but the problem is the name of the file downloaded is just the ID, for example, `1` or `2` without any extension or reasonable info.

Please, add at least optional query parameter to put a custom name to 'content-disposition' header to fix this.

**Comment by tsynik** [comment]
It's possible with /stream endpoint. Use this instead /play https://github.com/YouROK/TorrServer/blob/master/server/web/api/stream.go
