### ISSUE TITLE
Slow Caching speed

### ISSUE THREAD

**Issue by AgentLeone** [YouROK/TorrServer#386]
Hi,
Torrserver speed is very low. I tried with similar software Stremio. There the stream speed is very high(around 2MB/s). But in torrserver the speed is around 0.20MB/s. Should I change anything in the settings? I use the default settings

**Comment by tsynik** [comment]
It depends on connected peers upload speed, and open port for torrent to increase peers availability. Also, your provider can shape torrent traffic.
