### ISSUE TITLE
Потребление RAM

### ISSUE THREAD

**Issue by Fox-llc** [YouROK/TorrServer#387]
Почему после просмотра, оперативная память не скидывается до значений после перезагрузки vps?
![Screenshot_2024-05-02-21-09-28-28_68e6fbd18cf87e713eb44152d67d0941.jpg](https://github.com/YouROK/TorrServer/assets/123845684/be0a610a-1ece-4fbd-8c9c-bc5234b41420)

![Screenshot_2024-05-02-21-20-53-11_68e6fbd18cf87e713eb44152d67d0941.jpg](https://github.com/YouROK/TorrServer/assets/123845684/0a135cf5-3de1-4d9b-9542-07f4e35ae6e2)

**Comment by tsynik** [comment]
Менеджментом памяти занимается go
