### ISSUE TITLE
[BUG] Проблемы с разметкой и масштабированием интерфейса

### ISSUE THREAD

**Issue by Omegaplexx** [YouROK/TorrServer#395]
Здравствуйте. Давно уже есть проблемы с отображением полос прокрутки там, где они быть не должны, но недавно обновился с 129 версии на 132 и не выдержал очередной добавленной мешающей полосы, поэтому вот, пишу вам сейчас.

Имею ноутбук с экраном 1920x1080 и браузер Brave. После добавления категорий появилась полоса прокрутки кнопок меню сервера (масштабирование 100%):
![100](https://github.com/YouROK/TorrServer/assets/95503207/15928673-6704-4e21-8b70-746938f32362)
Предлагаемые пути решения:
1. Убрать полосу, но оставить возможность прокручивания кнопок (если это возможно);
2. Добавить в настройки опцию "Скрыть категории".

Изменить масштабирование я, конечно, могу, но мне становится слишком мелко, да и тогда плывёт другая часть интерфейса.
Масштабирование 90%:
![90](https://github.com/YouROK/TorrServer/assets/95503207/ecf79f57-ab8a-4602-acc6-abe613657592)
Надписи на кнопках отображаются в две строки, хотя свободного места предостаточно.

Масштабирование 100%:
![100-2](https://github.com/YouROK/TorrServer/assets/95503207/75e43015-520c-4dce-9d7e-272cedd9fa0a)

Теперь про увеличение. Я установил масштаб 110% и теперь наблюдаю аж 3 полосы прокрутки вместо одной:
![110](https://github.com/YouROK/TorrServer/assets/95503207/a905a904-cece-41c9-b15d-689a99458b2b)
Самая правая полоса прокручивает весь интерфейс сервера ровно на 1 пиксель вверх или вниз. При 100% или 125% она не отображается. При увеличении интерфейса на 125% появляется уже другая, горизонтальная полоса, двигающая интерфейс на 2 пикселя из-за того, что выпирают кнопки "Удалить" (чего делать они не должны):
![125](https://github.com/YouROK/TorrServer/assets/95503207/fd43a658-f0a0-4a59-9868-f27041b82fd6)

200% - отдельная песня. 5 полос на экране, хотя при грамотном кодинге интерфейса обойтись можно только той, что прокручивает список торрентов:
![200](https://github.com/YouROK/TorrServer/assets/95503207/2e98b98e-0052-41de-a08f-96f696e69a74)

Теперь про окно добавления торрента. Снова полоса, хотя места хоть отбавляй (100%):
![100-3](https://github.com/YouROK/TorrServer/assets/95503207/5cfbac86-e4a4-40a6-9121-bbb062a853d7)
Для чего устанавливать единый размер элементов и кнопок для всех экранов? Можно ли сделать ширину и высоту динамическими, чтобы убрать эти чёртовы полосы?

Благодарю за прочтение. Надеюсь, что не оставите без внимания эти проблемы.

**Desktop (please complete the following information):**
 - OS: Windows
 - TorrServer MatriX.132

**Comment by tsynik** [comment]
leftbar fixed with https://github.com/YouROK/TorrServer/commit/445f640d29ae076a13fcfaf75cf210433bd86d76
