### ISSUE TITLE
[Feature] Возможность ручной отметки серий как просмотренных

### ISSUE THREAD

**Issue by Omegaplexx** [YouROK/TorrServer#396]
В TorrServe для Android при долгом нажатии на элемент списка серий можно пометить серию как просмотренную или снять с неё эту отметку. В веб-интерфейсе этой фичи нет.

**Describe the solution you'd like**
Было бы удобно, если б вместо зелёной точки была небольшая кнопка с глазиком, нажимая на которую можно было бы легко управлять этими отметками. Обычный глаз - просмотрено, зачёркнутый - не просмотрено.
![Снимок экрана (173)](https://github.com/YouROK/TorrServer/assets/95503207/1c02919f-e50f-4802-838d-839d9779b469)

Спасибо!

**Comment by tsynik** [comment]
Изменение веба не планируется
