### ISSUE TITLE
DLNA discovering via ssh

### ISSUE THREAD

**Issue by mashkovd** [YouROK/TorrServer#397]
I have a remote server running the torr server application. I am redirecting the router's local port 8090 to the remote server's port 8090
I can see the router_ip:8090 web interface, but I can't see the dlna server through the TV or other device

I want to do something (forward another [port](https://github.com/YouR OK/TorrServer/blob/92e8063d39d1becba64e17171db5b6001a93b089/server/dlna/dlna.go#L45)? I'm trying to redirect 9080, but it doesn't help)

Do you have a solution for detecting a dlna server over ssh?

**Comment by tsynik** [comment]
DLNA will not work on any network after the router, as it uses multicast to announces.
Only solution to forward DLNA is any Layer 2 VPN network

**Comment by alexunderboots** [comment]
use GRE or shuttle to connect to vps

**Comment by vortigont** [comment]
you can forward one port and proxy DLNA announces via [dlnapass](https://github.com/Cycloctane/dlnapass)
