### ISSUE TITLE
TorrServer logging options

### ISSUE THREAD

**Issue by baragoon** [YouROK/TorrServer#4]
Please add server runtime parameter (or option in server settings) for logging.
For example - full logging, only errors, errors+warnings, info events, disable logging.
Now i'm observing a lot of messages which I want to suppress in journalctl\rsyslog.

For example. I don't need messages regarding to "Clean memory GC". Or give and advise how to disable them.
Thankks.

`Oct 05 18:02:37 vmunix TorrServer-linux-amd64[27864]: Preload: e1f9a2a7a5caa7268d0b99d45476300155ee0055 43.77MB / 40.00MB Speed: 35.56MB Peers:[ 3 ] 39 / 115
Oct 05 18:02:39 vmunix TorrServer-linux-amd64[27864]: Connect reader: 1
Oct 05 18:21:59 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 6155        18:02:39.470        b82312e92f22234f65945f6c63c80a9a95249271
Oct 05 18:22:43 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 6151        18:02:40.003        3fa3bfff61b6049b3514902054d3c3788814edde
Oct 05 18:22:59 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 6149        18:02:40.525        571d274b9e2ee7731ea603f3690a9cdc4ebe8844
Oct 05 18:23:44 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 6148        18:02:47.776        06724d95fdf9bb9275e5d3cb993cebe126ca6804
Oct 05 18:24:29 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5504        18:03:23.207        6f29ba76a2d2c8243f45e5c027772b3a965181a9
Oct 05 18:24:37 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5505        18:03:30.813        8d35b5be15a093b8cc9953ea80418df6244f3419
Oct 05 18:24:50 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5506        18:03:38.303        4560eb3da2bbaaa69c453675e1dccdc6264e5d68
Oct 05 18:24:52 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5507        18:03:45.657        ba16b56a41091ad6deca7ed562c2bb7c8abf35be
Oct 05 18:24:59 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5508        18:03:53.178        0d8d7ef89aae66f3709e68eb705dc15980cd5991
Oct 05 18:25:07 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5509        18:04:00.683        5dbb5126f1e920f90cdca68f406c972732f123fa
Oct 05 18:25:14 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5510        18:04:08.181        bb412d283c91c982c3bb9ae601dc841fd949bbe7
Oct 05 18:25:22 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5511        18:04:15.503        954cfeb5dde09ce884ccdbba3c85d15cf06a3174
Oct 05 18:25:30 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5512        18:04:23.211        e40230e60ea764eba1533fb388a8d90aec3bc0e3
Oct 05 18:25:36 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5513        18:04:30.578        5933cfefd14575025adc5fc66e50bf226a534c6c
Oct 05 18:25:44 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5514        18:04:38.120        06e75082970a7a6ea36f7494e0379ba98d4401bb
Oct 05 18:25:52 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5515        18:04:45.616        9a464a93408e8ef81b1c9ff7bf83699983c4ba0e
Oct 05 18:25:59 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5516        18:04:53.184        bb1ddb71c243872a8411d49222c91a1d28d4564c
Oct 05 18:26:13 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5517        18:05:00.698        84c24be8f64e035ea0cdebcaa8222c769f046412
Oct 05 18:26:14 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5518        18:05:07.852        0d4dbcf63f9842c41d8fd8769e681751a98bd9e7
Oct 05 18:26:22 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5519        18:05:15.332        b7c4e0a8fda7068b603e6ff0341191648a30c631
Oct 05 18:26:29 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5520        18:05:22.818        f6c37532034a0fd7fda5aaabe787d4f6e709f72d
Oct 05 18:26:37 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5521        18:05:30.259        87c0a397762e8d7cd5b135b33a1c6bd07f772a19
Oct 05 18:26:44 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5522        18:05:37.934        9b1062342b98d750d1f6e362a23ee3fd0b5cc53c
Oct 05 18:26:52 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5523        18:05:45.496        d711a33e56744af042ee6b156e51498bc073b329
Oct 05 18:26:59 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5524        18:05:53.224        e7bd7406a1b123a8ca12c12053868d852d6e9eb0
Oct 05 18:27:06 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5525        18:06:00.694        180c8b142b336568832aec358fd7a8e1d9494dfc
Oct 05 18:27:14 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5526        18:06:07.981        d526c9523837b14506e66af7cb492b6ed8b7fce1
Oct 05 18:27:28 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5527        18:06:15.298        4e4ac3829253149d1f0f8cc6318cc397978f255a
Oct 05 18:27:29 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5528        18:06:22.940        8e15e252202efce9fe5966557aecf96a1be598ce
Oct 05 18:27:42 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5529        18:06:30.220        0f35c6ea5f13702abac1f88a9f1fbd869cbe0291
Oct 05 18:27:44 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5530        18:06:38.068        24e9e3586fe74150508633fff2143e0a89b741c7
Oct 05 18:27:52 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5531        18:06:45.706        bc6fcd499a98b140882203d0edd6352d8d5177b5
Oct 05 18:27:58 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5532        18:06:52.979        3198d18a53c3a75dfce55dc2a4f482115c268874
Oct 05 18:28:06 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5533        18:07:00.378        173cb4b65e9f0f976c069c7f4964320f7c995a1f
Oct 05 18:28:13 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 6146        18:07:00.581        36c7b14c9f29ed8dec165d1996fc7bcd88b89589
Oct 05 18:28:27 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5534        18:07:07.972        3277395dbf662ae2dea93af1158f1d4e9b4e8794
Oct 05 18:28:29 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 6154        18:07:08.141        0771b8174a46724c287cbabcb577af901451ddff
Oct 05 18:28:36 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5535        18:07:22.874        97b40dd47298a30bf5270ab6a564c3b12c641a22
Oct 05 18:28:50 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5536        18:07:30.560        38240e7dab5be4393760e2b2da709babbcd2e33a
Oct 05 18:28:51 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5537        18:07:37.843        a2b224d5ea8bb52f0cdeaf1c21df512ff6ce27cd
Oct 05 18:28:59 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5538        18:07:45.366        0676ea1be426dea5756e78e69c4f1b350fde7078
Oct 05 18:29:12 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5539        18:07:52.880        804f7f02f971c524b51533806b437361ca345c2f
Oct 05 18:29:20 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5540        18:08:00.366        b0e67787f0d8dbb782e780e020c5639e80c8b2a3
Oct 05 18:29:21 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5541        18:08:07.831        56271ddf0ec0e31e26ba2dd340aa180c53394f9b
Oct 05 18:29:29 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5542        18:08:15.431        5a91850cee9fff125066d4081ceceb244a1bb8ad
Oct 05 18:29:36 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5543        18:08:22.646        35ab7c981950fda881f8897cfb4aa9b967c715d7
Oct 05 18:29:50 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5544        18:08:30.205        aeea08301d662551e632ea0403206c957750deb6
Oct 05 18:29:51 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5545        18:08:37.834        1386fd0a2c33a53634491c46c7c3c51daaed9a94
Oct 05 18:29:59 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5546        18:08:45.004        2cb5d98c0b6941a872173238a32159f77b9be816
Oct 05 18:30:06 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5547        18:08:52.593        010ff5d36333152dc4e214335fb0416c937274f4
Oct 05 18:30:13 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 99% 5548        18:09:00.122        9393bab08a19dee6749cf3a59914dc763a93c994
Oct 05 18:30:21 vmunix TorrServer-linux-amd64[27864]: Clean memory GC: 100% 5549        18:09:07.801        d863bb09eabebc646f05e8a4f634d3100053b578
`

**Comment by YouROK** [comment]
This is for debug log
Long removed in lasts version
