### ISSUE TITLE
External subtitles

### ISSUE THREAD

**Issue by PiRomant** [YouROK/TorrServer#40]
Due to the subtitles are located in the torrent next to in the same directory or subdirectory with the same video file name, but ends with *.srt or *.ass. Could you download them too?

For example, a VLC player will pick up subtitles if playlist looks like this:
```
#EXTM3U
#EXTINF:0,video.avi
#EXTVLCOPT:sub-file=video.srt
video.avi
```
If the torrent contains a file you can specify it in **#EXTVLCOPT:sub-file=** before the video file in playlist.

Some other video players support **Subtitle folder**: can automatically pick subtitles with a matching video file name from a pre-specified directory.

**Comment by YouROK** [comment]
Please give me hash with srt files for test

**Comment by PiRomant** [comment]
magnet:?xt=urn:btih:B0CCAE886AA49B106E47BA1B0F4F1415C84B8CBD&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&dn=%D0%9C%D1%8F%D1%82%D0%BD%D1%8B%D0%B9%20%D0%BB%D0%B8%D0%BA%D1%91%D1%80%20%2F%20Creme%20de%20Menthe%20(%D0%A4%D0%B8%D0%BB%D0%B8%D0%BF%D0%BF-%D0%94%D0%B0%D0%B2%D0%B8%D0%B4%20%D0%93%D0%B0%D0%BD%D1%8C%D0%B5%20%2F%20Philippe%20David%20Gagne%2C%20%D0%96%D0%B0%D0%BD-%D0%9C%D0%B0%D1%80%D0%BA%20%D0%A0%D1%83%D0%B0%20%2F%20Jean%20Marc%20E.%20Roy)%20%5B2017%2C%20%D0%9A%D0%B0%D0%BD%D0%B0%D0%B4%D0%B0%2C%20%D0%B4%D1%80%D0%B0%D0%BC%D0%B0%2C%20%D0%BA%D0%BE%D1%80%D0%BE%D1%82%D0%BA%D0%B8%D0%B9%20%D0%BC%D0%B5%D1%82%D1%80%2C%20HDTV%20

magnet:?xt=urn:btih:FBB7108E7026EEE7B1F70793027D9FDFED291CB5&tr=http%3A%2F%2Fbt2.t-ru.org%2Fann%3Fmagnet&dn=%D0%9F%D1%83%D1%82%D0%B5%D1%88%D0%B5%D1%81%D1%82%D0%B2%D0%B8%D0%B5%20%D0%9A%D0%B8%D0%BD%D0%BE%20-%20%D0%BF%D1%80%D0%B5%D0%BA%D1%80%D0%B0%D1%81%D0%BD%D1%8B%D0%B9%20%D0%BC%D0%B8%D1%80%20%2F%20Kino%20no%20Tabi%20-%20The%20Beautiful%20World%20%5BTV%2BSpecial%5D%20%5B13%2B1%20%D0%B8%D0%B7%2013%2B1%5D%20%5B%D0%91%D0%B5%D0%B7%20%D1%85%D0%B0%D1%80%D0%B4%D1%81%D0%B0%D0%B1%D0%B0%5D%20%5BRUS(int)%2C%20JAP%2C%20Sub%5D%20%5B2003%2C%20%D0%BF%D1%80%D0%B8%D0%BA%D0%BB%D1%8E%D1%87%D0%B5

magnet:?xt=urn:btih:3678F5F889A6DB1FAC6E0AF9E1B440B7B0D00EA6&tr=http%3A%2F%2Fbt4.t-ru.org%2Fann%3Fmagnet&dn=%D0%94%D0%BE%D0%BA%D1%82%D0%BE%D1%80%20%D0%A5%D0%B0%D1%83%D1%81%20%2F%20HOUSE%20M.D.%20%2F%20%D0%A1%D0%B5%D0%B7%D0%BE%D0%BD%201%20(01-07%20%D0%B8%D0%B7%2022)%20%5B2004%2C%20%D0%A1%D0%A8%D0%90%2C%20%D0%B4%D1%80%D0%B0%D0%BC%D0%B0%2C%20WEB-DLRip%5D%20(%D0%94%D0%BE%D0%BC%D0%B0%D1%88%D0%BD%D0%B8%D0%B9%7C%20%D0%A4%D0%B5%D0%B4%D0%BE%D1%81%D0%BE%D0%B2%20%7C%20LostFilm%20%7C%20Original%20%7C%20Sub)

Please dont ignore *.ass

**Comment by YouROK** [comment]
Complete

**Comment by PiRomant** [comment]
Is there a folder with cached subtitles that i can select in video player (MX Player) settings?
![MX Player subtitle setting](https://user-images.githubusercontent.com/29551044/110911079-cae5ba80-8344-11eb-8093-6e38c6ba2709.jpg)

**Comment by Aindar** [comment]
> Complete

В смысле TorrServer теперь должен подхватывать внешние субтитры? У меня не отображаются, ни в "Содержимое торрента" ни в плеере.

**Comment by jokereinherjar** [comment]
Подниму вопрос. Внешние субтитры также не подхватываются плеером.

**Comment by PiRomant** [comment]
Затык в том, что VLC из плейлиста даже не пытается открыть дополнительный файл. Эта проблема VLC. Поддержите тикет https://code.videolan.org/videolan/vlc/-/issues/25645

**Comment by alexeynl** [comment]
> Эта проблема VLC.

Проблема не в VLC. Это следствие того, что автор выбрал изначально неправильный путь ее решения, по сути был реализован костыль. 

Во первых, #EXTVLCOPT - это кастомный тег, который распознается только VLC медиаплеером, остальные медиаплееры о нем ничего не знают.
Во вторых, VLC отказалась от реализации воспроизведения внешних субтитров и видеодорожек M3U через #EXTVLCOPT input-slave из соображений безопасности.

Правильный путь - встраивать внешние субтитры и аудиодорожки в видеопоток (в медиаконтейнер), для этого придется делать ремультиплексирование (remux) оригинальных файлов. Зато изначально не будет проблем с совместимостью с различными медиаплеерами. С помощью ffmpeg это сделать достаточно просто https://stackoverflow.com/questions/8672809/use-ffmpeg-to-add-text-subtitles. Ну или если автор считает, что будет очень много проблем с поддержкой данной функции, добавить такую возможность как экспериментальную функцию, т.е. как есть без поддержки.

**Comment by tsynik** [comment]
> добавить такую возможность как экспериментальную функцию, т.е. как есть без поддержки.

займись - код открыт, pull requests принимаются
