### ISSUE TITLE
[BUG]Videos in mkv format will only be downloaded and cannot be played online

### ISSUE THREAD

**Issue by srcrs** [YouROK/TorrServer#403]
**Describe the bug**
Videos in mkv format will only be downloaded and cannot be played online

**To Reproduce**

in chrome visit：

```
https://video.lass.cc/stream/%E9%98%B3%E5%85%89%E7%94%B5%E5%BD%B1dygod.org.%E9%A3%9E%E9%A9%B0%E4%BA%BA%E7%94%9F2.2024.HD.1080P.%E5%9B%BD%E8%AF%AD%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97.mkv?link=67abf19e4ba428509ae42b798de1010028250993&index=1&play
```

**Expected behavior**
Can play mkv videos online

**Desktop (please complete the following information):**
 - OS: Macbook
 - TorrServer Version MatriX.132

**Comment by tsynik** [comment]
Example URL played fine with IINA.app on MacOS

<img width="951" alt="IINA" src="https://github.com/YouROK/TorrServer/assets/1551446/23e5cd19-c51c-4e91-af31-746568e9bc18">
