### ISSUE TITLE
[Feature] Bookmarks

### ISSUE THREAD

**Issue by n0oo0ne** [YouROK/TorrServer#408]
Just my own experience. Add bookmarks. A very useful feature. Select any torrent with a long press and show the option - "add to bookmarks" in the menu. Add a bookmarks item to the left menu. Personally, I have a server on Orange Pi 5 Plus with about 1000 (!) torrents in the history, and it’s extremely difficult to find the necessary one among them. But I don’t want to delete them all either, let them remain for the history :) Thank you in advance for your work.

**Comment by YouROK** [comment]
TorrServer is not a database for torrents. Adding torrents is made for the convenience of watching TV series
