### ISSUE TITLE
Тормозит 4К

### ISSUE THREAD

**Issue by allmoney** [YouROK/TorrServer#41]
Добрый день!

Видео 2 секунды идёт, 2 секунды тормозит. 

![2021-03-25_11-57-57](https://user-images.githubusercontent.com/939594/112446605-6faec180-8d61-11eb-9306-cbf51a62be57.png)
![2021-03-25_11-56-31](https://user-images.githubusercontent.com/939594/112446611-70475800-8d61-11eb-8aa3-e4f0042226b3.png)
![2021-03-25_11-56-19](https://user-images.githubusercontent.com/939594/112446612-70dfee80-8d61-11eb-827f-3d0a464349ae.png)
![2021-03-25_11-56-04](https://user-images.githubusercontent.com/939594/112446613-70dfee80-8d61-11eb-94c8-0edee03ea744.png)
![2021-03-25_12-00-49](https://user-images.githubusercontent.com/939594/112446924-c7e5c380-8d61-11eb-9387-f8a84baf329f.png)

Никак не могу понять почему так происходит? Сигнал сильный. ПК мощный, ОЗУ достаточно. Где узкое горлышко? Помогите разобраться!

**Comment by allmoney** [comment]
Увеличил Cache size до 5000 и включил "Preload buffer" - но проблема всё равно сохраняется...
![2021-03-25_12-06-28](https://user-images.githubusercontent.com/939594/112447625-96212c80-8d62-11eb-934e-9cc20f80a543.png)

**Comment by allmoney** [comment]
![image](https://user-images.githubusercontent.com/939594/112450380-69badf80-8d65-11eb-99d0-3bc5ff027e64.png)

**Comment by ziurim** [comment]
мало peers, нажмите паузу, потому что он играет быстрее, чем успевает скачать

**Comment by YouROK** [comment]
Мало пиров, WiFi не способствует закачке, может роутер не тянет много подключений черезwifi

**Comment by allmoney** [comment]
Так я на паузу поставил чтобы подкачалось (это видно на последнем скриншоте:
![image](https://user-images.githubusercontent.com/939594/112505911-4b250a80-8d9e-11eb-9cd4-6b8e954f4265.png)

Торренты на 30 ГБ проверял - не тормозит, а на 40 и 60 - тормозит. Дело не в роутере тоже... Что и как ещё проверить?

**Comment by epexa** [comment]
> Так я на паузу поставил чтобы подкачалось (это видно на последнем скриншоте:
> ![image](https://user-images.githubusercontent.com/939594/112505911-4b250a80-8d9e-11eb-9cd4-6b8e954f4265.png)
> 
> Торренты на 30 ГБ проверял - не тормозит, а на 40 и 60 - тормозит. Дело не в роутере тоже... Что и как ещё проверить?

такая же проблема...

например: 42 Гб всё ок, а вот уже 65 Гб тормозит.

![image](https://user-images.githubusercontent.com/2198826/128690254-d9cc0df3-b1f2-4e11-8358-c37d8a2c791d.png)

в обоих случаях 4К HEVC, в первом 38 мбит, во втором 58 мбит

42 Гб:
`magnet:?xt=urn:btih:c7d9d085edde50e09cbb1f81fbc7f9c9916c04b7&dn=Tenet.(2020).BDRip.2160p.SDR.mkv&tr=http%3a%2f%2ftracker.filetracker.pl%3a8089%2fannounce&tr=http%3a%2f%2ftracker2.wasabii.com.tw%3a6969%2fannounce&tr=http%3a%2f%2ftracker.grepler.com%3a6969%2fannounce&tr=http%3a%2f%2f125.227.35.196%3a6969%2fannounce&tr=http%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=http%3a%2f%2f87.248.186.252%3a8080%2fannounce&tr=http%3a%2f%2f210.244.71.25%3a6969%2fannounce&tr=http%3a%2f%2f46.4.109.148%3a6969%2fannounce&tr=udp%3a%2f%2f46.148.18.250%3a2710&tr=http%3a%2f%2ftracker.dler.org%3a6969%2fannounce&tr=udp%3a%2f%2f%5b2001%3a67c%3a28f8%3a92%3a%3a1111%3a1%5d%3a2710&tr=udp%3a%2f%2fipv6.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.cyberia.is%3a6969%2fannounce&tr=http%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=http%3a%2f%2ftracker3.itzmx.com%3a6961%2fannounce&tr=http%3a%2f%2ftracker.sloppyta.co%3a80%2fannounce&tr=http%3a%2f%2ftracker.gbitt.info%3a80%2fannounce`

65 Гб:
`magnet:?xt=urn:btih:6d9e336932e7d250bd72ce5e0e90729e1e80dd28&dn=Tenet.2020.BDREMUX.2160p.HDR.seleZen.mkv&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2f9.rarbg.to%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.uw0.xyz%3a6969%2fannounce&tr=udp%3a%2f%2fretracker.lanta-net.ru%3a2710%2fannounce&tr=http%3a%2f%2ftracker.filetracker.pl%3a8089%2fannounce&tr=http%3a%2f%2ftracker2.wasabii.com.tw%3a6969%2fannounce&tr=http%3a%2f%2ftracker.grepler.com%3a6969%2fannounce&tr=http%3a%2f%2f125.227.35.196%3a6969%2fannounce&tr=http%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=http%3a%2f%2f87.248.186.252%3a8080%2fannounce&tr=http%3a%2f%2f210.244.71.25%3a6969%2fannounce&tr=http%3a%2f%2f46.4.109.148%3a6969%2fannounce&tr=udp%3a%2f%2f46.148.18.250%3a2710&tr=http%3a%2f%2ftracker.dler.org%3a6969%2fannounce&tr=udp%3a%2f%2f%5b2001%3a67c%3a28f8%3a92%3a%3a1111%3a1%5d%3a2710&tr=udp%3a%2f%2fipv6.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.cyberia.is%3a6969%2fannounce&tr=http%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=http%3a%2f%2ftracker3.itzmx.com%3a6961%2fannounce&tr=http%3a%2f%2ftracker.sloppyta.co%3a80%2fannounce&tr=http%3a%2f%2ftracker.gbitt.info%3a80%2fannounce`

**Comment by epexa** [comment]
https://github.com/YouROK/TorrServer/issues/82
https://github.com/YouROK/TorrServer/issues/11

**Comment by epexa** [comment]
https://github.com/YouROK/TorrServer/issues/11

**Comment by epexa** [comment]
Видимо проблема (в моём случае) в VPS, а конкретнее с сетью между VPS и клиентом.
**Т.к. когда запускаю сервак в локальной сети на Windows или Ubuntu всё отлично работает!**

**Comment by epexa** [comment]
@allmoney попробуй ноут и телик по проводу подключить, видимо для таких больших файлов не хватает скорости сети.

**Comment by epexa** [comment]
> Видимо проблема (в моём случае) в VPS, а конкретнее с сетью между VPS и клиентом.
> **Т.к. когда запускаю сервак в локальной сети на Windows или Ubuntu всё отлично работает!**

Да, **после смены VPS всё отлично заработало!**

_На старом VPS не хватало скорости канала 100 Мбит/с (в реале он выдавал меньше)._
