### ISSUE TITLE
[BUG] TorrServer недоступен для сайтов, открытых в Chrome через http протокол.

### ISSUE THREAD

**Issue by Am1hai** [YouROK/TorrServer#416]
**Describe the bug**
Если в chrome (windows) при включенном флаге chrome://flags/#block-insecure-private-network-requests
(а это очень важный флаг для безопасности локальной  сети)
загрузить по http:// lampa.mx или prisma.ms и прописать там ip адрес запущенного на том же компьютере TorrServer-windows-amd64, то сервер будет недоступен. 

**To Reproduce**
0. Проверить, что флаг chrome://flags/#block-insecure-private-network-requests установлен в Default
1. Загрузить по http lampa.mx
если будет грузится по https то в настройках сайта Небезопасный контент - разрешить, дальше chrome://net-internals/#hsts - Delete domain security policies - вписать lampa.mx - delete.
потом явно указать http://lampa.mx
2. Запустить TorrServer-windows-amd64
3. В настройках лампы указать локальный адрес сервера, например http://192.168.0.110:8090
4. Появится сообщение "нет подключения к сети, сервер будет недоступен,
В Devtools/network будет ошибка
Access to XMLHttpRequest at 'http://192.168.0.110:8090/' from origin 'http://prisma.ws' has been blocked by CORS policy: The request client is not a secure context and the resource is in more-private address space `private`.

**Expected behavior**
В сервере должно быть реализовано RFC1918
Хорошо написано тут
https://developer.chrome.com/blog/cors-rfc1918-feedback?hl=ru
в сети есть много вариантов доработки.

Microsoft Windows [Version 10.0.19045.4412]
Google Chrome 125.0.6422.142 (Официальная сборка), (64 бит)
MatriX.133t

P.S. Я без претензий на высокую техническую грамотность, но уже несколько дней пытаюсь запустить
предназначенные для телевизоров кинотеатры с загрузкой торрентов на лету и ничего не получается.
Исправил проблему с генерируемым сертификатом (не подходит для windows, сгенерил свой для IP-адреса,
оказалось что далеко не все кинотеатры корректно работают через SSL.
Разобрался как их принудительно в хроме запустить через http - теперь вот это.
В файрфоксе работает, значит он небезопасен.

**Comment by tsynik** [comment]
это не баг а безопасность хромиума - все вопросы к ним

заголовки для хрома и разрешения частных адресов c RFC1918 были добавлены в MatriX.133+

<img width="1252" alt="cors-private-net" src="https://github.com/YouROK/TorrServer/assets/1551446/242b81b8-4184-4f73-94de-ed3cf04f8b49">

**Comment by Am1hai** [comment]
>>заголовки для хрома и разрешения частных адресов c RFC1918 были добавлены в MatriX.133+

наверное этого недостаточно, раз chrome пишет ошибку. 

собственно просмотр торрентов через chrome/firefox лично у меня не работает ни в лампе, ни в призме, ни по http, ни по https, "видео не найдено или повреждено", хотя m3u ссылка, которую отдает torrserv прекрасно работает, если ее скормить плееру (MPC-BC)
так что в общем-то без разницы, будет ли у torrserver улучшена совместимость с хромом или нет.

**Comment by deedoc** [comment]
Если открыть браузером локальный сайт TorrServer'а (у меня это http://192.168.100.124:8090/), то видно, что в заголовках ответа НЕ прилетают нужные заголовки: <img width="1243" height="556" alt="Image" src="https://github.com/user-attachments/assets/ebea61e2-6095-44a0-9400-42507a953143" />

<br>
Кроме того, в server/web/server.go включено AllowHeaders, которое судя по докам https://github.com/gin-contrib/cors всего-лишь разрешает эти заголовки в запросе, но никак не пишет их в ответ

<br><br>
<b>
UPD: К сожалению наличие заголовков не всегда поможет. Хром всё равно заблокирует запрос к локальному ресурсу (192.168.x.x, 10.x.x.x, 172.16.x.x-172.31.x.x, 127.x.x.x), если запрос идёт с незащищённого ресурса (http://lampa.mx как раз http, а не https)
</b>

<br><br>
<b>UPD2: В качестве решения подошло сделать наоборот: доступ к TorrServer'у оставить прямым локальным, а доступ к lampa.mx проксировать через тоже адрес (ip), на котором живёт TorrServer</b>
