### ISSUE TITLE
Обновление торрсервера в докере

### ISSUE THREAD

**Issue by ivanvpetrovich** [YouROK/TorrServer#420]
Доброго дня!
Подскажите, пожалуйста, не могу разобраться.
Запускаю докер контейнер следующей командой: docker run --rm -d --name torrserver -p 8090:8090 ghcr.io/yourok/torrserver:latest
Контейнер запускается, нормально работает, но он всегда запускается той версии, которую я изначально начал использовать - 129. Хотелось бы обновиться до последней версии торрсервера, но потушив контейнер и заного его запустив получаю ту же самую версию. Не могу понять, как обновить торрсервер в докер контейнере? Я использую Alma Linux. Он по всей видимости куда-то скачался и запускается всегда локально, вместо того чтобы стягивать последний релиз.

**Comment by TopperBG** [comment]
docker stop torrserver
docker rm torrsever
docker pull ghcr.io/yourok/torrserver:latest
docker run ....

**Comment by ivanvpetrovich** [comment]
Спасибо огромное, помогло!
Вместо pull пробовал build...
Теперь все шикарно)
