### ISSUE TITLE
[BUG] Launching with IPv6 enabled but not available takes a long time

### ISSUE THREAD

**Issue by nyakze** [YouROK/TorrServer#425]
**Describe the bug**
When IPv6 is enabled in TorrServer but not available on the machine, public IPv6 lookup takes a long time until the server is launched.

**To Reproduce**
1. Don't have a public IPv6 address
2. Activate IPv6
3. Restart TorrServer
4. TorrServer will take its time to launch

**Expected behavior**
TorrServer should start as fast as with IPv6 disabled.

**Desktop:**
 - OS: Windows 11 Pro 23H2
 - TorrServer Version MatriX.133.NE

**Additional context**
I know this can easily be resolved by switching off IPv6 entirely, but in my use-case I sometimes use the network which has better double-NAT and native IPv6. Constantly switching is not ideal. Does it have to get a public IP before launch? I think it's alright not to wait and just go ahead and start the server as usual while it's trying to get a public IP.

**Comment by tsynik** [comment]
it's not a bug, and timeout can be avoided with --pubipv6 startup option

**Comment by nyakze** [comment]
> it's not a bug, and timeout can be avoided with --pubipv6 startup option

That's not really helpful. as ipv6 address is always different. It would also require me to have the same static IPv6 all the time, which is not the case. I was hoping for a way to skip IP resolve at launch. I'm not entirely sure why this is feature is even needed, if this lookup is only done on startup and IP can change when the server is still running and the server has no problems figuring it out without running any extra lookup halting server.

I have opted to manually disable/enable IPv6 when needed for now.

**Comment by tsynik** [comment]
> I have opted to manually disable/enable IPv6 when needed for now.

So, you can disable ipv6 address check both with --pubipv6 option on startup if you know current address, or with ipv6 off. This feature needed to announce proper address to peers and for torrent communication. If u don't care u can define any local ipv6 address with --pubipv6 option.
