### ISSUE TITLE
[BUG] не выгружаются торренты из памяти

### ISSUE THREAD

**Issue by PutinVladimir** [YouROK/TorrServer#426]
После 129 версии через раз не выгружает торренты и не освобождает память. Переключении опции очистки при удалении\выключении не влияет таймают то же... Смотрим в виму видео, жмем кнопку домой на пульте(если выходить закрытием виму то вроде нормально)... и все торрент в большинстве случаев будет висеть и жрать память. Поставил 129 версию и все как часы, при тех же настройках, 5 секундный таймаут и память очищена.
Вcе это на arm64 версии на keenetic

**Comment by PutinVladimir** [comment]
Вероятно это связано с изменением в 130:
Закрыть и дропнуть торрент нельзя при используемых подключениях плеера

**Comment by tsynik** [comment]
Это не bug а feature.

**Comment by PutinVladimir** [comment]
а в чем фича и зачем тогда сделаны опции очищать при удалении/выключени ?

**Comment by tsynik** [comment]
фича в том, что торрент не должен удаляться при наличии активного клиента (плеера). опции очищать при удалении / отключении относятся только к дисковому кешу и определяют что с ним делать - хранить всегда пока торрент есть в БД торрсерва или удалять по окончанию воспроизведения по таймауту.
