### ISSUE TITLE
Request for Latest Update to Compile IPK File for webOS

### ISSUE THREAD

**Issue by 6ebeng** [YouROK/TorrServer#427]
**Is your feature request related to a problem? Please describe.**
I would like to use TorrServer on my webOS device. Currently, there is no compiled IPK file available for webOS, which makes it challenging to install and use TorrServer on this platform. This limitation prevents users like me from leveraging the benefits of TorrServer on webOS devices.

**Describe the solution you'd like**
I would like to request the addition of an IPK file for webOS in the latest TorrServer release. This would involve compiling TorrServer to an IPK format compatible with webOS, allowing seamless installation and usage on webOS devices.

**Describe alternatives you've considered**
As an alternative, I have considered manually compiling TorrServer for webOS, but this process is quite complex and not user-friendly. Additionally, it may require significant technical knowledge and effort, which could be a barrier for many users who are not familiar with the compilation process.

**Additional context**
Adding support for webOS by providing an IPK file would greatly enhance the accessibility and usability of TorrServer for a wider range of users. It would also expand the reach of TorrServer to more devices, providing more options for users to enjoy its features. Thank you for considering this feature request.

**Comment by YouROK** [comment]
We provide binaries for different processor architectures and wasps. You can build ipk files yourself and post them somewhere else
