### ISSUE TITLE
[Feature] Добавить возможность указать server address в настройках

### ISSUE THREAD

**Issue by sriverg2** [YouROK/TorrServer#428]
При использовании reverse proxy (nginx) Torrserver работает корректно, в тч через Torrserve, но при скачивании плейлиста через браузер в плейлисте получаю примерно следующее: `https://127.0.0.1:5665/stream/xxxxxx`

нужна возможность указать адрес сервера в настройках и использовать его при генерации плейлистов (куда я прописал бы например `https://mydomain.com:443` и получил бы в плейлисте `https://mydomain.com:443/stream/xxxxxx`)

**Comment by tsynik** [comment]
не нужна. это настраивается заголовками в nginx и работает корректно при правильной его настройке.
https://github.com/YouROK/TorrServer/issues/380

ещё пример:
```
server {
  listen 80;
  listen [::]:80;
  listen 443 ssl http2;
  listen [::]:443 ssl http2;

  server_name имя сервера;
  ssl_certificate /etc/nginx/ssl/ngnix.crt;
  ssl_certificate_key /etc/nginx/ssl/ngnix.key;
  include /etc/nginx/snippets/ssl-params.conf;

  location / {
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-NginX-Proxy true;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'upgrade';
  proxy_pass http://localhost:ПОРТ/;
  proxy_ssl_session_reuse off;
  proxy_set_header Host $http_host;
  proxy_pass_header Server;
  proxy_cache_bypass $http_upgrade;
  proxy_redirect off;
  proxy_http_version 1.1;
  }
  location /stream/ {
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-NginX-Proxy true;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection 'upgrade';
  proxy_pass http://localhost:ПОРТ/stream/;
  proxy_ssl_session_reuse off;
  proxy_set_header Host $http_host;
  proxy_pass_header Server;
  proxy_cache_bypass $http_upgrade;
  proxy_buffering off;
  proxy_redirect off;
  proxy_http_version 1.1;
  }
}
```

**Comment by equillibrium** [comment]
Добрый день!
Какие бы настройки не указывал в nginx, плейлисты все равно формируются с IP-адресом, а не доменным именем. При этом одиночные файлы проигрываются корректно, подскажите, пожалуйста, куда можно копнуть?
