### ISSUE TITLE
[Feature] Self server update option on Linux, Windows

### ISSUE THREAD

**Issue by filimonic** [YouROK/TorrServer#431]
**Is your feature request related to a problem? Please describe.**
Implement ability to run self-update on linux, windows. It's unclear how to follow updates in-app.

**Describe the solution you'd like**
Periodically check for updates (on start, and daily). If update is available, follow update logic: 
* If update is available, then
* * 1 show a button for manual update in web ui
* * 2 if auto update is enabled (new checkbox option, default false)
* * * If no active torrents, then
* * * * If update has no breaking changes (update server indicates)
* * * * * run update

**Describe alternatives you've considered**
May be make it separate application, not implemented to main TS binary

**Comment by tsynik** [comment]
Update check and routine already implemented in https://github.com/YouROK/TorrServer/blob/master/installTorrServerLinux.sh script for Linux. Just run it without any arguments and answer Y to Do you want to update? question. Also, you can always update torrserver just by replace binary to current version.

**Comment by tsynik** [comment]
For Windows it's implemented in https://github.com/Noperkot/TorrServerInstaller
