### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ZloyTim** [YouROK/TorrServer#434]
Использую торрсервер на виндус 11, смотрю на телевизоре лампу, заметил такая проблема если начинаешь смотреть фильм с середины то он очень плохо грузит, посмотрел в настройки торрсервера он приоритено загружает части с самого начала и игнорирует загрузку с середины фильма. Короче не совсем удобно тебе надо подождать пока полфильма погрузиться и тогда смотреть. Может админ заметит и сможет подправить приоритеты загрузки частей

**Comment by tsynik** [comment]
Не воспроизводится.
