### ISSUE TITLE
Быстрый автозапуск в ОС W-11 ProTorr Server-windows -amd 64 exe.[Feature]

### ISSUE THREAD

**Issue by pap19522** [YouROK/TorrServer#437]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pap19522** [comment]
При проекте новых исполнительных файлов  windows -amd 64 exe  если возможно сделайте  быстрый  автозапуск данного файла при старте ОС W-11 Pro .Спасибо.

**Comment by pap19522** [comment]
Просьба была встроить  автозапуск в файл исполнительный TorrServer -windows -amd 64 exe. .,  чтобы не было каждый раз танцев с  бубнами при каждой переустановке ,  пусть работает в фоновом режиме , кому не нравится, пусть закрывают его. После открытия рабобчего стола ОС W-11 PRO, автозапуск происходит только через 30,- 40 секунд, при соблюдении всех необходимых условий для автозапуска.

**Comment by tsynik** [comment]
Для автозапуска и управления используйте TSL - https://github.com/Noperkot/TSL

**Comment by pap19522** [comment]
Добрый день! Спасибо за поддержку, вся автозагрузка стала быстрее. Для
модернизации приложения прошу Вас сделать синхронизацию файлов торрент при
переустановках исполнительного  файлаTorrsever Windows amd 64 exe.
Переставляеш файл, все сохранённые файлы слетают.Если для этого будет
необходим дополнительный сервер для пользователей, значит пожелание
снимается. Спасибо.

пн, 12 авг. 2024 г. в 00:51, nikk ***@***.***>:
