### ISSUE TITLE
[BUG] Обрезаются названия в web-интерфейсе

### ISSUE THREAD

**Issue by and7ey** [YouROK/TorrServer#438]
**Describe the bug**
Если кликнуть по постеру торрента, то наименование полное, в примере на картинке ниже:
`Кролик Питер (2018), фэнтези, комедия, приключения...`
В самом списке же лишь 
`Кролик Питер (2018)`

**To Reproduce**
1. Добавить торрент через АПИ с длинным названием (как в примере выше)
2. Посмотреть отображение в web-интерфейсе 
(такое происходит со всеми фильмами, даже с коротким названием, например, вместо `Детки (1995), драма` отображается `Детки (1995)`)

**Screenshots**
<img width="722" alt="image" src="https://github.com/user-attachments/assets/0887b6e3-d821-40b4-b439-bc387fdc21bd">

**Additional context**
В идеале бы, конечно, отдельное поле под жанр и под описание.

**Comment by and7ey** [comment]
Upd. понял, что где-то тут - https://github.com/YouROK/TorrServer/blob/master/web/src/components/TorrentCard/index.jsx - специально все обрезается. Но как же тогда иметь быстрый доступ к жанру?

**Comment by tsynik** [comment]
Это не баг, а так задумано. Жанры в название не пишут. В катогории можно записывать что хочешь по api в том числе жанры

**Comment by and7ey** [comment]
> В катогории можно записывать что хочешь по api в том числе жанры

Разве список категорий не фиксированный? https://github.com/YouROK/TorrServer/blob/master/web/src/components/categories.jsx

**Comment by tsynik** [comment]
> Разве список категорий не фиксированный?

Нет, там может быть любая строка (список слов). Фиксированный он только в вебе при изменении, и выборке
