### ISSUE TITLE
[BUG] Не раздаются торренты после просмотра

### ISSUE THREAD

**Issue by vvzvlad** [YouROK/TorrServer#442]
У меня он запущен на NAS, есть и память, и канал, и место на диске, чтобы достаточно долго раздавать торренты после просмотра. Хочется не быть только личем, раз уж мне это ничего не стоит. 
Поставил максимальный размер кеша, место хранения — диск, подмонтировал папку в докере, прописал путь к ней. И ничего, после просмотра оттуда файлы пропадают, и ничего не раздается. Как сделать так, чтобы оно оставалось на раздаче достаточно долго? Скажем, месяц без проблем смогу держать.

**Comment by tsynik** [comment]
это не баг, и торрсервер не предназначен для раздачи торрентов. используйте для этого torrent-клиенты

**Comment by popovn** [comment]
Видимо надо на максимум поставить время "отключения" торрента
