### ISSUE TITLE
[BUG] Потребление памяти в 5 раза больше чем буфер в настройках

### ISSUE THREAD

**Issue by PutinVladimir** [YouROK/TorrServer#444]
Настройки по умолчанию:
/opt/etc/torrserver/settings.json
{
  "BitTorr": {
    "CacheSize": 67108864,
    "ConnectionsLimit": 25,
    "DisableDHT": false,
    "DisablePEX": false,
    "DisableTCP": false,
    "DisableUPNP": false,
    "DisableUTP": false,
    "DisableUpload": false,
    "DownloadRateLimit": 0,
    "EnableDLNA": false,
    "EnableDebug": false,
    "EnableIPv6": false,
    "EnableRutorSearch": false,
    "ForceEncrypt": false,
    "FriendlyName": "",
    "PeersListenPort": 0,
    "PreloadCache": 50,
    "ReaderReadAHead": 95,
    "RemoveCacheOnDrop": false,
    "ResponsiveMode": false,
    "RetrackersMode": 1,
    "SslCert": "",
    "SslKey": "",
    "SslPort": 0,
    "TorrentDisconnectTimeout": 30,
    "TorrentsSavePath": "",
    "UploadRateLimit": 0,
    "UseDisk": false
  }
}

в веб интерфейсе торресервера КЭШ 80Мб, вместо 64Мб
![изображение](https://github.com/user-attachments/assets/b8e9c80b-b8af-48bf-a6da-978691641664)

Размер блока торрента 8mb.
![изображение](https://github.com/user-attachments/assets/60c65145-0ae2-40bc-b313-40c524336bc4)
Если размер блока меньше, например 2-4мб, то проблема с потребление памяти гораздо менее заметна, если размер блока больше, например 16мб, то все становится еще хуже.

Пиров всего парочка...
Потребление torrserver при просмотре торрента ~250Mb
![изображение](https://github.com/user-attachments/assets/998b498e-a3ed-4501-80ce-d78272bf0efe)

Вопрос это нормально что буфер не соответсвует выставленому, и что общее потребление почти в 3-5 раз больше, чем в теории должно быть?

**Comment by PutinVladimir** [comment]
Если поставить на паузу то минут через 5 торресрвер отпустит часть памяти и станет так
![изображение](https://github.com/user-attachments/assets/7ac03acf-78a4-47fe-a703-84601cb1ab51)
но это все равно существенно больше установленного буфера(даже с учетом объема требуемого самому приложению)...

**Comment by tsynik** [comment]
Это ожидаемое поведение

**Comment by PutinVladimir** [comment]
то есть настройка размера буфера бесполезна ?
