### ISSUE TITLE
[Feature] Поддержка протокола BitTorrent v2

### ISSUE THREAD

**Issue by belomaxorka** [YouROK/TorrServer#445]
Подробнее про BitTorrent V2:
- https://blog.libtorrent.org/2020/09/bittorrent-v2/
- https://habr.com/ru/articles/717820/

**Comment by tsynik** [comment]
Поддержка BitTorrent V2 есть в сборках из ветки new-engine с библиотекой torrent v1.56+ https://github.com/anacrolix/torrent/tags
