### ISSUE TITLE
[Feature] Adding an icon to a Windows executable

### ISSUE THREAD

**Issue by nyakze** [YouROK/TorrServer#446]
**Is your feature request related to a problem? Please describe.**
Currently there's no icon for the Windows executable. It uses generic Windows application icon.

**Describe the solution you'd like**
Would be nice to have an icon bundled with the .exe just so it looks nicer.

**Describe alternatives you've considered**
I'm adding an icon to a shortcut manually, but some people are probably are not aware of this option or just too lazy to do it and leave it as is.

**Additional context**
Attaching an example icon that I'm using for myself.
[icon.zip](https://github.com/user-attachments/files/16721307/icon.zip)

**Comment by YouROK** [comment]
add in next version
