### ISSUE TITLE
[BUG] crash: fatal error: sync: Unlock of unlocked RWMutex

### ISSUE THREAD

**Issue by cyraxan** [YouROK/TorrServer#448]
TorrServer crash during streaming the video
installed on Synology
v 134

2024/08/27 19:48:29 UTC0 End preload: 22c70fe703ae3cb0b281cda6c35fe5c0b4f6c947 Peers: 8 / 13 [ Seeds: 6 ]
fatal error: sync: Unlock of unlocked RWMutex

goroutine 144194 [running]:
sync.fatal({0xd8bb86?, 0xc00b19a9c8?})
	runtime/panic.go:1061 +0x18
sync.(*RWMutex).Unlock(0xc0000cba10)
	sync/rwmutex.go:209 +0x45
github.com/anacrolix/sync.(*RWMutex).Unlock(0xc0125d9b78?)
	github.com/anacrolix/sync@v0.5.1/rwmutex.go:26 +0x2f
github.com/anacrolix/torrent.(*Client).unlock(0xaaaa9aaaa4aaaaaa?)
	github.com/anacrolix/torrent@v1.54.1/client.go:1371 +0x19
panic({0xc360e0?, 0xecbd50?})
	runtime/panic.go:914 +0x21f
github.com/anacrolix/torrent/storage.Piece.ReadAt({{0xed5f60?, 0xc001fd17c0?}, {0xc001ba6300?, 0x1010000ecfae0?}}, {0xc00ae14000, 0x55e4ed?, 0x8000}, 0x1e8000)
	github.com/anacrolix/torrent@v1.54.1/storage/wrappers.go:88 +0x346
io.(*SectionReader).Read(0xc007a52360, {0xc00ae14000?, 0x8000?, 0x7fd4b4a3b878?})
	io/io.go:516 +0x4f
io.copyBuffer({0x7fd4b4574cd8, 0xc011b8ca80}, {0xece3a0, 0xc007a52360}, {0x0, 0x0, 0x0})
	io/io.go:430 +0x1a6
io.Copy(...)
	io/io.go:389
github.com/anacrolix/torrent.(*Torrent).hashPiece(0xc0003a8000, 0x14a)
	github.com/anacrolix/torrent@v1.54.1/torrent.go:743 +0x229
github.com/anacrolix/torrent.(*Torrent).verifyPiece(0xc0003a8000, 0x14a)
	github.com/anacrolix/torrent@v1.54.1/torrent.go:1651 +0x25a
created by github.com/anacrolix/torrent.(*Torrent).queuePieceCheck in goroutine 2552
	github.com/anacrolix/torrent@v1.54.1/torrent.go:1687 +0x10a

[TorrServer.log](https://github.com/user-attachments/files/16768271/TorrServer.log)

**Comment by yarik2720** [comment]
have the same issue after change cache from ram to ssd

settings.json
```json
{
  "BitTorr": {
    "CacheSize": 134217728,
    "ConnectionsLimit": 50,
    "DisableDHT": false,
    "DisablePEX": false,
    "DisableTCP": false,
    "DisableUPNP": false,
    "DisableUTP": false,
    "DisableUpload": false,
    "DownloadRateLimit": 0,
    "EnableDLNA": false,
    "EnableDebug": false,
    "EnableIPv6": true,
    "EnableRutorSearch": false,
    "ForceEncrypt": false,
    "FriendlyName": "***",
    "PeersListenPort": 0,
    "PreloadCache": 50,
    "ReaderReadAHead": 95,
    "RemoveCacheOnDrop": false,
    "ResponsiveMode": false,
    "RetrackersMode": 1,
    "SslCert": "",
    "SslKey": "",
    "SslPort": 0,
    "TorrentDisconnectTimeout": 120,
    "TorrentsSavePath": "/tmp/torrserver",
    "UploadRateLimit": 25000,
    "UseDisk": true
  }
}
```

**Comment by tsynik** [comment]
torrent@v1.54.1 is not an actual release
