### ISSUE TITLE
Инструкции по сборке

### ISSUE THREAD

**Issue by qarkai** [YouROK/TorrServer#45]
В `README.md` нужны инструкции для сборки дистрибутива.
Вижу, что есть скрипты `build-all.sh`, `compile_init.sh`, `make_release.sh`, но какой из них использовать неизвестно.
Какие есть зависимости сборки?

**Comment by YouROK** [comment]
Все делается в линукс, у меня убунта
Требуется go 1.16+
Запускаешь build_all.sh он подтянет все зависимости и сделает вебку 
Соберет для всех прописанных платформ
Либо в консоле ввести две команды
go mod tidy #подтянет все зависимости
go build cmd -o TorrServer

**Comment by qarkai** [comment]
В арче:
```
$ go mod tidy
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
$ go build cmd -o TorrServer
malformed import path "-o": leading dash
package TorrServer is not in GOROOT (/usr/lib/go/src/TorrServer)
```

**Comment by YouROK** [comment]
Запускай build-all.sh для сборки
Чтобы собирать все в ручную ищи в интернете как происходит сборка в go или посмотри в build-all.sh

**Comment by qarkai** [comment]
```
$ ./build-all.sh 
./build-all.sh: строка 15: /usr/local/go/bin/go: Нет такого файла или каталога
```
```
$ pacman -Qi go
Название             : go
Версия               : 2:1.16.3-1
Причина установки    : Явно установлен
```

**Comment by PiRomant** [comment]
Косячная строка
https://github.com/YouROK/TorrServer/blob/e4a90ef2d27b4a682c28401cb146b7e4239ffdad/build-all.sh#L12

**Comment by qarkai** [comment]
Полагаю, что @YouROK знает и уже исправляет.

**Comment by YouROK** [comment]
Ребят править не буду так как по офф документации го устанавливается в ту папку. Под каждый дистрибутив не буду подстраиваться.
https://golang.org/doc/install

**Comment by PiRomant** [comment]
Так а смысл указывать место установки, если его установка подразумевает указание в PATH?
@qarkai, поменяй на `GOBIN="go"`

**Comment by qarkai** [comment]
Всё приходится самому делать.

**Comment by PiRomant** [comment]
А Вам удалось для Android собрать? А то после установки golang-go, libc++-dev и
```
wget -O toolchain.zip https://dl.google.com/android/repository/android-ndk-r22b-linux-x86_64.zip
unzip -j -o -q toolchain.zip "*/toolchains/llvm/prebuilt/linux-x86_64/*" -d ./toolchain/bin/
```
все еще ошибки `неизвестный параметр «-pagezero_size»` и т.д.

**Comment by qarkai** [comment]
Я и не пробовал. Если раньше под андроид не работало, то и сейчас не заработает. Остальное собирается.

**Comment by PiRomant** [comment]
Так я и говорю, что оно и раньше с ошибками собиралось

**Comment by qarkai** [comment]
Я понял.

**Comment by qarkai** [comment]
> Так я и говорю, что оно и раньше с ошибками собиралось

Уточню: ты имеешь в виду только андроид? Под остальные платформы нет ошибок? Я бы на твоём месте issue на сборку под андроид завёл, если ещё не было.
