### ISSUE TITLE
[BUG] DLNA server only working with VLC on Android and Linux

### ISSUE THREAD

**Issue by ddonindia** [YouROK/TorrServer#451]
**Describe the bug**
The DLNA server works only with VLC on Android and Linux. Other players can detect TorrServer’s DLNA server and browse the torrent list, but attempting to play any video file results in a “file not found” error. This issue occurs on both Linux and Android, with no errors appearing in the server logs.

**To Reproduce**
1.  Open the torrent browser screen in any video player that supports UPnP.
2.  Click on any video file.
3.  Observe the error message “file not found” or a similar error.

**Expected behavior**
Able to play video.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 22.04 
 - TorrServer Version: Latest

**Smartphone or tvbox on Android (please complete the following information):**
 - Device: Android TV
 - OS: Android Latest
 - TorrServer Version: Latest

**Comment by tsynik** [comment]
DLNA support provided by external library and working "as is"
