### ISSUE TITLE
"Docker & Docker Compose" не обновлены.

### ISSUE THREAD

**Issue by psavld** [YouROK/TorrServer#456]
Здравствуйте! Пожалуйста обновите ghcr.io/yourok/torrserver:latest до последней версии. Сейчас создается контейнер с версией 133t.
Спасибо.

**Comment by Fannangir** [comment]
Same as issue 450 :)

**Comment by psavld** [comment]
> Same as issue 450 :)

I think I understood your comment - it was sarcasm.

10/03/2024 19:42 Just completed the installation:
      :~ # docker run --rm -d --name torrserver -p 8090:8090 ghcr.io/yourok/torrserver:latest
The result is in the picture. 
![1](https://github.com/user-attachments/assets/176e3dc0-371b-4ebb-8633-3dd5dbafdbf3)

**Comment by psavld** [comment]
> Same as issue 450 :)

I think I understood your comment - it was sarcasm.
