### ISSUE TITLE
[Feature] Добавьте ключ запуска bind address 

### ISSUE THREAD

**Issue by Pro100x3mal** [YouROK/TorrServer#460]
Просьба рассмотреть возможность добавления ключа запуска bind address, который позволит запускать torrserver не только на 0.0.0.0:port, но и на конкретном интерфейсе или локальном хосте (например 127.0.0.1:port).
Да, для ограничения внешнего доступа можно использовать файрволл, но в некоторых сценариях необходимо ограничить доступ таким способом

**Comment by tsynik** [comment]
> Просьба рассмотреть возможность добавления ключа запуска bind address, который позволит запускать torrserver не только на 0.0.0.0:port, но и на конкретном интерфейсе или локальном хосте (например 127.0.0.1:port).
> Да, для ограничения внешнего доступа можно использовать файрволл, но в некоторых сценариях необходимо ограничить доступ таким способом

если вы посмотрите в ключи запуска torrserver, то увидите, что это уже реализовано

**Comment by Pro100x3mal** [comment]
> > Просьба рассмотреть возможность добавления ключа запуска bind address, который позволит запускать torrserver не только на 0.0.0.0:port, но и на конкретном интерфейсе или локальном хосте (например 127.0.0.1:port).
> > Да, для ограничения внешнего доступа можно использовать файрволл, но в некоторых сценариях необходимо ограничить доступ таким способом
> 
> если вы посмотрите в ключи запуска torrserver, то увидите, что это уже реализовано

Если вы о ключе --torrentaddr, то это не то, о чем я писал выше. Возможно, я некорректно описал свою просьбу.
Ключ --torrentaddr не меняет ip:port веб интерфейса торрсервера. Например, если добавляю ключ --torrentaddr 127.0.0.1:8091, то в логе запуска сервиса вижу «listen addr 127.0.0.1:8091», но при этом web port все по умолчанию 8090 (не менял коюч -p), а также «Start http server at port 8090»:

```
2024/10/06 01:50:33 XPathDBRouter: Registered new route "torrents" for DB "TDB", total 4 routes
2024/10/06 01:50:33 Check web port 8090
2024/10/06 01:50:33 Start TorrServer MatriX.134 torrent v1.2.22
2024/10/06 01:50:33 Local IPs: [10.10.10.0 xxx.xxx.xxx.xxx]
2024/10/06 01:50:33 Set listen addr 127.0.0.1:8091
2024/10/06 01:50:33 Client config: {"CacheSize":209715200,"ReaderReadAHead":96,"PreloadCache":32,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":35,"PeersListenPort":0,"SslPort":0,"SslCert":"","SslKey":"","ResponsiveMode":false}
2024/10/06 01:50:33 PublicIp4: xxx.xxx.xxx.xxx 
2024/10/06 01:50:33 Start http server at port 8090
[2024-10-06 01:50:33 +0300 NIL github.com/anacrolix/torrent client.go:321]
dht server on 127.0.0.1:8091 (node id xxxxxxxxxxxxxxxxxxxxxx) completed bootstrap ({9 0})
```

Проверяю:
```
netstat -anltp | grep "LISTEN" | grep TorrServer
tcp        0      0 127.0.0.1:8091          0.0.0.0:*               LISTEN      1080848/TorrServer- 
tcp6       0      0 :::8090                 :::*                    LISTEN      1080848/TorrServer- 
```
А хотелось бы во втором случае вместо :::8090 видеть 127.0.0.1:8090
PS. Torrserver работает за nginx, поэтому необходимо, что он был доступен только по 127.0.0.1:8090

**Comment by tsynik** [comment]
Торрент обмен при такой конфигурации осуществляется только на 127.0.0.1:8091. Веб торрсервера к торрентам отношения не имеет и его можно ограничить правилами firewall оставив доступ только на локалхосте

**Comment by Pro100x3mal** [comment]
> Торрент обмен при такой конфигурации осуществляется только на 127.0.0.1:8091. Веб торрсервера к торрентам отношения не имеет и его можно ограничить правилами firewall оставив доступ только на локалхосте

Вот пример, когда этого недостаточно.
Если на впс установлен торрсервер и xray (vless reality), то клиенты vless получают доступ к вебу торрсервера в обход фаервола, так как у них ip сервера. Если принудительно бы веб работал на 127.0.0.1:8090 - доступа бы не было.
Пример реализации - веб морда AdGuard Home, можно заставить слушать на 127.0.0.1:3000, тогда клиенты vless не получают доступ к нему.
