### ISSUE TITLE
[BUG]Пропадают Торренты

### ISSUE THREAD

**Issue by wwsilin** [YouROK/TorrServer#467]
Raspberry Pi 3 model B
Ось Linux osmc 5.15.92-1-osmc #1 SMP PREEMPT Tue Jul 25 00:26:57 UTC 2023 armv7l GNU/Linux
После добавления менее чем через минуту иногда чуть дольше список торрентов становится пустым(

**Comment by Bora2k3** [comment]
TS_RDB=false
но 
```
2024/11/10 21:17:56 UTC0 save to db: d1a652494fb4170484b319c25f487d382e681130
2024/11/10 21:17:56 UTC0 DB.Set: Read-only DB mode! d1a652494fb4170484b319c25f487d382e681130
2024/11/10 21:18:26 UTC0 Torrent close by timeout d1a652494fb4170484b319c25f487d382e681130
2024/11/10 21:18:26 UTC0 Close cache for: d1a652494fb4170484b319c25f487d382e681130
```

**Comment by tsynik** [comment]
> TS_RDB=false

не является параметром запуска торрсервера. Разбирайтесь с образом Докера
