### ISSUE TITLE
Вопрос про https

### ISSUE THREAD

**Issue by mshakurov** [YouROK/TorrServer#469]
Проигрыватели типы video.js проигрывают и отлично переходят на любую позицию, и возобновляют давно поставленное на паузу видео по ссылкам из плейлиста типа http://host:8090/stream/filename?link=hash&index=1&play

Не подскажете, можно ли как-то получать ссылки в плейлисте для https ?
Пробовал в ссылках схему заменять на https и порт на 8091 (указан в настройках), не помогает.

TorrServer MatriX.134 запущен в docker. Docker работает на VPS виртуалке ubuntu 20.04.
Конфиг и лог, вообще вся папка /opt контейнера замаплена за папку на хосте.
docker run -d --rm  --name torrserver -v /path/to/opt:/opt -p 0.0.0.0:8090:8090 -p 0.0.0.0:8091:8091 torrserver
Активно пользуюсь - сервер отлично работает из lampa.mx на Android.TV.
Но вот пытаюсь в браузере на своей странице задействовать https, пока не понял как.
В настройках для https явно указан порт, 8091, ни кем не занятый.
Указал сертификат и ключ, сгенеренный openssl.
При запуске torrserver в логе про порты вижу только порт 8090
netstat показывает что ни кто не слушает на 8091
Вот лог при запуске:
```
=========== START ===========
TorrServer MatriX.134, go1.21.2, CPU Num: 2
Check dns OK [xxx.xxx.xxx.xxx xxxx:xxxx:xxxx:xxxx::xxxx] <nil>
XPathDBRouter: Registered new DB "JsonDB", total 1 DBs registered
XPathDBRouter: Registered new route "" for DB "JsonDB", total 1 routes
XPathDBRouter: Registered new route "settings" for DB "JsonDB", total 2 routes
XPathDBRouter: Registered new route "viewed" for DB "JsonDB", total 3 routes
XPathDBRouter: Registered new DB "TDB", total 2 DBs registered
XPathDBRouter: Registered new route "torrents" for DB "TDB", total 4 routes
Check web port 8090
Start TorrServer MatriX.134 torrent v1.2.22
Local IPs: [xxx.xxx.xxx.xxx]
Set listen port to random autoselect (0)
Client config: {"CacheSize":268435456,"ReaderReadAHead":95,"PreloadCache":78,"UseDisk":false,...,"SslPort":8091,"SslCert":"/cert.pem","SslKey":"/key.pem","ResponsiveMode":false}
PublicIp4: xxx.xxx.xxx.xxx
Update rutor db
Start http server at port 8090
Load rutor db
MRS: Create rutor json db file
MRS: Rutor json db file created. Records: 179772
Index rutor db
Torrents count: 179772
Indexed words: 68011
```
Ни каких ошибок.
web интерфейс по https тоже не работает.

**Comment by AJIgAH4uK** [comment]
поддерживаю, развернут в докере, указаываю путь через вебморду, менял порты не помогает. Условно развернутый тотже 3x-ui сразу подцепил ssl.

**Comment by tsynik** [comment]
Без докера ссылки в плейлисте имеют правильных формат

**Comment by popovn** [comment]
Не совсем понял вопроса,но https  у меня заработал с  **ключем --ssl**
