### ISSUE TITLE
[BUG] TorrServer-darwin-amd64 is still blocked after adding to a list of allowed apps is MacOS Firewall

### ISSUE THREAD

**Issue by VKondakoff** [YouROK/TorrServer#471]
Could not add TorrServer-darwin-amd64 to a list of allowed apps is MacOS Firewall. Here is what I see, when MacOS Firewall is disabled (everything works as expected):
<img width="999" alt="Снимок экрана 2024-11-27 в 14 04 26" src="https://github.com/user-attachments/assets/39aeb7c5-b8a1-4aef-9444-cb269a3aacb5">
And here is what I see when MacOS Firewall is enabled (Safari could not open this page):
<img width="998" alt="Снимок экрана 2024-11-27 в 14 06 15" src="https://github.com/user-attachments/assets/0b41c9b4-29f0-4316-b4e7-f8a8f283b34b">

Now I'm trying to add TorrServer-darwin-amd64 to the list of allowed apps in macOS Firewall:
<img width="831" alt="Снимок экрана 2024-11-27 в 14 08 41" src="https://github.com/user-attachments/assets/2259a95a-366a-42d6-8cf2-873473e1065a">
And it appears in the list:
<img width="831" alt="Снимок экрана 2024-11-27 в 14 09 35" src="https://github.com/user-attachments/assets/6c7c006e-d9d5-46ab-a549-f5f6c4c09f71">
But unfortunately after clicking 'OK' and reopening the list there is no TorrServer-darwin-amd64:
<img width="831" alt="Снимок экрана 2024-11-27 в 14 10 51" src="https://github.com/user-attachments/assets/26f5c8d3-2f91-4d40-8f50-6b8b476ee4b8">

What is wrong here? How can I allow incoming connections to TorrServer-darwin-amd64?

Thank you!

**Desktop (please complete the following information):**
 - OS: MacOS Sequoia 15.1.1
 - TorrServer Version MatriX.134

**Comment by Budspok77** [comment]
I have added the app to the list on macos 15.1.1. And it doesn't disappear. But the firewall is blocked torrserver anyway. Only after I turn firewall off, torrserver starts working on ATV.

**Comment by VKondakoff** [comment]
Yes, I was able to add the app to the list using command line: `/usr/libexec/ApplicationFirewall/socketfilterfw --add /Users/Shared/TorrServer/TorrServer-darwin-amd64`. And yes, it is still blocked. 
Just edited the bug-report subject.

**Comment by tsynik** [comment]
I's not a bug of TorrServer and this behavior can't be changed on torrserver side, so closed

**Comment by Budspok77** [comment]
Very nice way to solve the problem 👏 I guess there are a lot of Mac users who would like to use this app. But turn off firewall is not good solution. May be it's good way some how to simulate this problem on macos and try to find the solution rather than say that it is not our business.

**Comment by VKondakoff** [comment]
👆This!

**Comment by tsynik** [comment]
> May be it's good way some how to simulate this problem on macos and try to find the solution rather than say that it is not our business.

You can send me a MacBookPro with M4 and I'll simulate this and the issue will be reopened :D There is no such problem on My MacBookPro Retina 15 on Monterey - TorrServer works and firewall is ON.

**Comment by VKondakoff** [comment]
Are you connecting to the TorrServer using `localhost:8090` or `127.0.0.1:8090`? The issue is reproducible only when you are connecting to TorrServer using your machine local network IP-address (`10.0.1.5:8090` in my case).

**Comment by tsynik** [comment]
> Are you connecting to the TorrServer using `localhost:8090` or `127.0.0.1:8090`? The issue is reproducible only when you are connecting to TorrServer using your machine local network IP-address (`10.0.1.5:8090` in my case).

No, I'm using it other my lan on all mediaboxes and TVs. Also, it can matter if you've installed TorrServer via it's macos install script for current or ALL users. In second case it runs as root user before login and there can be permissions issues. Try reinstall it for current user autoastart only.

And it's not disappears from firewall rules list on previous macos:
<img width="893" alt="ts-fw" src="https://github.com/user-attachments/assets/77d4d7c1-153a-4cb8-b6ba-f0c842cb52a2">

**Comment by VKondakoff** [comment]
Hey, thanks for your suggestions. I have reinstalled TorrServer making sure it is started for current user only. Unfortunately this does not solves the issue: I can reach the server using `127.0.0.1:8090` and can not reach the server using `10.0.1.5:8090` if system firewall is enabled. When I disable the system firewall, I can reach the server using both `127.0.0.1:8090` and `10.0.1.5:8090`.

<img width="1383" alt="Снимок экрана 2024-12-05 в 16 19 14" src="https://github.com/user-attachments/assets/3f3b86c2-91ee-48d1-a376-2bb6b652b2c5">


<img width="1381" alt="Снимок экрана 2024-12-05 в 16 19 24" src="https://github.com/user-attachments/assets/771ba471-560c-4090-9ad5-4af2e0a9c3eb">


```
=========== START ===========
TorrServer MatriX.134, go1.22.5, CPU Num: 8
2024/12/05 16:06:22 Check dns OK [142.250.150.99 142.250.150.104 142.250.150.147 142.250.150.106 142.250.150.105 142.250.150.103 2a00:1450:4010:c0f::93 2a00:1450:4010:c0f::69 2a00:1450:4010:c0f::6a 2a00:1450:4010:c0f::68] <nil>
2024/12/05 16:06:22 XPathDBRouter: Registered new DB "JsonDB", total 1 DBs registered
2024/12/05 16:06:22 XPathDBRouter: Registered new route "" for DB "JsonDB", total 1 routes
2024/12/05 16:06:22 XPathDBRouter: Registered new route "settings" for DB "JsonDB", total 2 routes
2024/12/05 16:06:22 XPathDBRouter: Registered new route "viewed" for DB "JsonDB", total 3 routes
2024/12/05 16:06:22 XPathDBRouter: Registered new DB "TDB", total 2 DBs registered
2024/12/05 16:06:22 XPathDBRouter: Registered new route "torrents" for DB "TDB", total 4 routes
2024/12/05 16:06:22 Check web port 8090
2024/12/05 16:06:22 Start TorrServer MatriX.134 torrent v1.2.22
2024/12/05 16:06:22 Local IPs: [10.0.1.4 10.0.1.5]
2024/12/05 16:06:22 Set listen port to random autoselect (0)
2024/12/05 16:06:22 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0,"SslPort":0,"SslCert":"","SslKey":"","ResponsiveMode":false}
2024/12/05 16:06:22 PublicIp4: 95.24.82.25
2024/12/05 16:06:22 Start http server at port 8090
[2024-12-05 16:06:53 +0300 NIL github.com/anacrolix/torrent client.go:321]
  dht server on 0.0.0.0:62840 (node id 9b7eb617d2acf0772db99871d6f7239f28eac346) completed bootstrap ({69 26})
```

**Comment by VKondakoff** [comment]
Updating Macos to 15.2 does not solves the issue.
