### ISSUE TITLE
Сервер не видно за пределами localhost:8090

### ISSUE THREAD

**Issue by ChildInside** [YouROK/TorrServer#472]
Пожалуйста, прошу, помогите с проблемой.
Установил TorrServer на Windows 11 (24H2). Система чистая, переустановка была чуть больше недели назад. Сервер практически не работает. Настройки доступны по localhost:8090 и все, дальше ничего. Я могу вписать этот адрес и использовать его только на том устройстве, на котором стоит сервер. Иногда бывает доступ по 127.0.0.1:8090, иногда даже включается по локальном IP внутри сети, но это как будто рандом..я не понимаю от чего зависит его работа. Через браузер сервер не открывается по адресам 127.0.0.1:8090 и 192.168.х.х:8090

Соответственно, нормальном им пользоваться в локальной сети невозможно. Удалил все сторонние обходы и тому подобное - не помогает. Что-то мешает программе нормально работать. 

Стоит штатный антивирус и брандмауэр. Настройка есть на порты и на программу отдельно, пытался даже все выключить до чего дотянулся - не помогло.

На всякий случай вот то, что выдает при подключении.

![Снимок экрана 2024-12-03 224435](https://github.com/user-attachments/assets/8334cddb-a264-48a7-a774-f3e913722d4a)

**Comment by tsynik** [comment]
Это не проблема TorrServer а проблема настройки сети в вашей Windows 11 и ее брандмауэре
