### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vectorserver** [YouROK/TorrServer#477]
Ubuntu 20.4 перестал стартовать

2024/12/10 12:47:23 Set listen port to random autoselect (0)
2024/12/10 12:47:23 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0,"SslPort":0,"SslCert":"","SslKey":"","ResponsiveMode":false}
2024/12/10 12:47:23 PublicIp4: xx.35.92.xx
2024/12/10 12:47:23 Start http server at port 8090
[2024-12-10 12:47:44 +0000 NIL github.com/anacrolix/torrent client.go:321]
  dht server on 0.0.0.0:34167 (node id c4e5e539977c6fba51b492493691150dd77577ec) completed bootstrap ({51 23})

**Comment by alexkomzal** [comment]
На Windows 11 у меня также, на тв не вижу IP сервера

2024/12/13 19:05:16 ffprobe and avprobe not found in $PATH
=========== START ===========
TorrServer MatriX.134, go1.22.5, CPU Num: 12
2024/12/13 19:05:16 Check dns OK [142.250.186.164] <nil>
2024/12/13 19:05:16 XPathDBRouter: Registered new DB "JsonDB", total 1 DBs registered
2024/12/13 19:05:16 XPathDBRouter: Registered new route "" for DB "JsonDB", total 1 routes
2024/12/13 19:05:16 XPathDBRouter: Registered new route "settings" for DB "JsonDB", total 2 routes
2024/12/13 19:05:16 XPathDBRouter: Registered new route "viewed" for DB "JsonDB", total 3 routes
2024/12/13 19:05:16 XPathDBRouter: Registered new DB "TDB", total 2 DBs registered
2024/12/13 19:05:16 XPathDBRouter: Registered new route "torrents" for DB "TDB", total 4 routes
2024/12/13 19:05:16 Check web port 8090
2024/12/13 19:05:16 Start TorrServer MatriX.134 torrent v1.2.22
2024/12/13 19:05:16 Local IPs: [192.168.0.120]
2024/12/13 19:05:16 Set listen port to random autoselect (0)
2024/12/13 19:05:16 Client config: {"CacheSize":67108864,"ReaderReadAHead":95,"PreloadCache":50,"UseDisk":false,"TorrentsSavePath":"","RemoveCacheOnDrop":false,"ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableDLNA":false,"FriendlyName":"","EnableRutorSearch":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":false,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":25,"PeersListenPort":0,"SslPort":0,"SslCert":"","SslKey":"","ResponsiveMode":false}
2024/12/13 19:05:16 PublicIp4: 46.191.176.242
2024/12/13 19:05:16 Start http server at port 8090
[2024-12-13 19:05:27 +0500 NIL github.com/anacrolix/torrent client.go:321]
  dht server on 0.0.0.0:56774 (node id 421c66bf99af082d0eebc9f6f118054fe9beca7a) completed bootstrap ({38 25})

**Comment by tsynik** [comment]
no bugs here
