### ISSUE TITLE
Как настроить аутентификацию в TorrServer для Docker?

### ISSUE THREAD

**Issue by neohdx** [YouROK/TorrServer#480]
Надо чтобы при входе в вебморду запрашивался логин и пароль. Документацию почитал и ничего не понял, в Docker новичок совсем. Помогите пожалуйста!

**Comment by leporel** [comment]
https://github.com/YouROK/TorrServer?tab=readme-ov-file#environments

> `TS_HTTPAUTH` - 1, and place auth file into `~/ts/config` folder for enabling basic auth

файл выглядит так 
`accs.db`
```
{
    "user1": "password"
}
```

передать env параметр в докер флагом при запуске `-e TS_HTTPAUTH=1`
