### ISSUE TITLE
OpenAPI для HTTP API

### ISSUE THREAD

**Issue by qarkai** [YouROK/TorrServer#49]
Предлагаю описать HTTP API на [OpenAPI/Swagger](https://swagger.io/docs/specification/about/).
В `README.md` можно будет вместо всего раздела сделать ссылку на [Swagger Editor](https://editor.swagger.io/) вида `https://editor.swagger.io/?url=https://raw.githubusercontent.com/YouROK/TorrServer/master/swagger.yml`.

**Comment by qarkai** [comment]
Выглядит примерно так: https://editor.swagger.io/?url=https://raw.githubusercontent.com/qarkai/TorrServer/openapi/swagger.yaml

**Comment by PiRomant** [comment]
Что ж Вы стесняетесь pull request https://github.com/YouROK/TorrServer/compare/master...qarkai:openapi сделать, раз так далеко зашли?

**Comment by qarkai** [comment]
Во-первых, там не весь API. Во-вторых, может, владельцу это не понравится или не нужно, а в гитхабе он не силён. Но как сейчас есть в ридми - это ужас. Надеюсь, Вам понятно.

**Comment by PiRomant** [comment]
В `/stream` `link` и `index` вроде всегда обязательные
`/playlistall/all.m3u` и `/playlist` возвращают `m3u`, а значит там должно быть `application/x-mpegURL`

**Comment by qarkai** [comment]
Спасибо. Вот поэтому это всё должен писать или посмотреть автор. В идеале, конечно, файл должен генериться из исходников, но gin вроде бы не поддерживает.

**Comment by PiRomant** [comment]
Почему он https предлагает? 
![image](https://user-images.githubusercontent.com/29551044/117546003-6e580080-b052-11eb-9989-ed984ca2004c.png)

**Comment by YouROK** [comment]
Идея хорошая, но сейчас времени нет описывать. Если кто опишет добавлю ссылку или что там предлагается

**Comment by qarkai** [comment]
@PiRomant, например, надо добавить
```yaml
schemes:
  - http
```
`If schemes are not specified, the scheme used to serve the API specification will be used for API calls.`

**Comment by PiRomant** [comment]
Если в `/stream` есть `play`, то Response  `application/vnd.apple.mpegurl`
`poster` это url на `image/jpeg` `image/png`

**Comment by YouROK** [comment]
Если кто захочет сделать там описание api открою заново
