### ISSUE TITLE
Улучшения в "web"

### ISSUE THREAD

**Issue by dancheskus** [YouROK/TorrServer#50]
Я бы хотел внести некоторые изменения в web дизайне. Там есть некоторые проблемы с адаптивностью на меленьких  экранах.

Могу принять участие?

**Comment by YouROK** [comment]
Почему бы и нет, делай реквесты, а там посмотрим

**Comment by dancheskus** [comment]
Хотел бы уточнить. 

1. Как мне получить доступ к запущенному серверу запущенного на тв с React приложения запущенного на компе?
2. Правильно ли я понимаю, что в web версии настройки не полностью синхронизируются с сервером? Например, настройки буфера работают, а вот, например, UTP, TCP и пр. тогглы не синхронизируются.

**Comment by YouROK** [comment]
1 не понял о чем ты, что за доступ? В настройках есть адрес там можно подключаться к серверу
2 все должно передаваться и сохраняться

**Comment by dancheskus** [comment]
1. В настройках менял. Не получилось. Решил временной заменой в `Hosts.js`
2. Не работает, как мне кажется. Посмотрю подробнее позже.
3. Могу порефакторить код или лучше не лезть? Отступы в 4 таба, это специально, или не принципиально?

**Comment by dancheskus** [comment]
Какой-то конфликт с твоей и моей веткой. Дизайн по другому себя ведет

**Comment by dancheskus** [comment]
Поправил https://github.com/YouROK/TorrServer/pull/52
