### ISSUE TITLE
94 версия

### ISSUE THREAD

**Issue by finik77** [YouROK/TorrServer#53]
TorrServer-linux-amd64[3938]: /opt/torrserver/TorrServer-linux-amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/torrserver/TorrServer-linux-amd64)

**Comment by YouROK** [comment]
В чем проблема?

**Comment by finik77** [comment]
Вывод списка… Готово
libc6/testing 2.31-12 amd64 [может быть обновлён с: 2.28-10]
libc6/stable,now 2.28-10 amd64 [установлен, может быть обновлён до: 2.31-12]



Требуется 2.32

**Comment by MrKsey** [comment]
> В чем проблема?

Проблема с версией Glibc6. У вас используется 2.32, а в стабильной ветке debian, например, максимально доступная - 2.28

**Comment by YouROK** [comment]
Проверь 95 версию, сделал компиляцию без зависимости либс

**Comment by finik77** [comment]
Все нормально на 95, закрываю
