### ISSUE TITLE
Предзагрузка редких раздач на диск

### ISSUE THREAD

**Issue by Kolovatoff** [YouROK/TorrServer#56]
Предложение следующее:
Оставить кэш в ОЗУ, но дать возможность предзагружать редкие раздачи которые не дают нормальной скорости для живого просмотра на диск.
Сейчас же если включить функцию "Use disk", то все торренты начинают кешироваться на диск.
Т.е. добавить функцию которая скачивает торрент полностью на диск и уже потом чтобы можно было запустить m3u на плеере и смотреть торрент.

Сейчас же делаю так:
1. Скачиваю торрент сторонним клиентом на диск
2. Добавляю этот торрент в TorrServer
3. Запускаю m3u на плеере и на стороннем торрент клиенте добавляю в пиры 127.0.0.1:32000

Можно добавить рядом с кнопкой "Preload" которая загружает 32Мб торрента, кнопку "Preload Full on disk" которая скачивала бы полностью раздачу на диск.

**Comment by IhorSyerkov** [comment]
Поддерживаю фичу. Есть файлы с 1, 2 сидами, смотреть нереально.

**Comment by YouROK** [comment]
Чтобы реализовать закачку торрентов в виде файлов, это нужно сделать заново обычную закачку. Сейчас сервер сделан на работу с кэшем, а не файлами.
То что вы просите, это уже не кэш, а закачка торрента и потом проигрывание его через хттп.
Чтобы сделать кэш на каждый торрент по-разному, тоже не так просто реализовать
