### ISSUE TITLE
wrong version number in web interface

### ISSUE THREAD

**Issue by sharicov** [YouROK/TorrServer#57]
Web interface shows TorrServer MatriX.94 instead of TorrServer MatriX.95

**Comment by YouROK** [comment]
Show the server output on startup

**Comment by sharicov** [comment]
Seems to be fixed after reboot, output below, however still not showing images
<img width="854" alt="Screenshot 2021-05-26 203000" src="https://user-images.githubusercontent.com/1933626/119705376-58737980-be61-11eb-89a8-9865f4165ad4.png">


2021/05/26 20:28:41 Start TorrServer MatriX.95
2021/05/26 20:28:41 IP: [192.168.3.70 2a06:5580:5:f400:30aa:e434:46d0:2 2a06:5580:5:f400:d1a8:8e18:2e51:3459 2a06:5580:5:f400:a21d:13cb:2211:9e37 fe80::5d89:1ce7:f0e2:7c67 100.97.86.41 fd7a:115c:a1e0:ab12:4843:cd96:6261:5629 fe80::728f:6425:bd24:6fc5 172.18.0.1 172.17.0.1 fe80::42:4dff:fe2a:c77c fe80::209e:4eff:fee4:c9ae fe80::b04c:15ff:febf:aa35 fe80::3420:1eff:fe3b:f9a7 fe80::9cec:7ff:fefc:cfaf 10.122.31.1 fd42:5941:26a4:636e::1 fe80::216:3eff:fe68:c20f]
2021/05/26 20:28:41 Find upnp port
2021/05/26 20:28:41 Set upnp port 32000
2021/05/26 20:28:41 Configure client: {"CacheSize":100663296,"PreloadBuffer":false,"ReaderReadAHead":95,"UseDisk":false,"TorrentsSavePath":"","ForceEncrypt":false,"RetrackersMode":1,"TorrentDisconnectTimeout":30,"EnableDebug":false,"EnableIPv6":false,"DisableTCP":false,"DisableUTP":true,"DisableUPNP":false,"DisableDHT":false,"DisablePEX":false,"DisableUpload":false,"DownloadRateLimit":0,"UploadRateLimit":0,"ConnectionsLimit":23,"DhtConnectionLimit":500,"PeersListenPort":0,"Strategy":0}
2021/05/26 20:28:41 Start web 8090
2021/05/26 20:28:41 UPnP discovery result f7a0686c-1e1d-7cdc-63fb-9f43eea0c3f5/WANDevice/urn:upnp-org:serviceId:WANIPConn1/urn:schemas-upnp-org:service:WANIPConnection:1/http://192.168.3.1:37215/ctrlu/92ec32dc-2073-de36-b90d-a411c1e8add8/WANIPConn_1
2021-05-26 20:28:43 portfwd.go:31: discovered 1 upnp devices

**Comment by YouROK** [comment]
If you have not added any picture links, then no pictures will be shown

**Comment by sharicov** [comment]
How do I add the links?

**Comment by YouROK** [comment]
![ts](https://user-images.githubusercontent.com/4067300/120153049-edc29500-c1f6-11eb-9f1f-7cccf5af32d2.png)

**Comment by sharicov** [comment]
Thanks!
How can I add the poster link after added a magnet link?
