### ISSUE TITLE
Поддержка ipv6

### ISSUE THREAD

**Issue by avengermsoft** [YouROK/TorrServer#6]
Прошу добавить поддержку ipv6 для BTServer в TorrServer.

**Comment by avengermsoft** [comment]
Спасибо, все работает, только нужно сделать замену в Torrents.go
с `udp://46.148.18.250:2710` на `udp4://46.148.18.250:2710`

**Comment by avengermsoft** [comment]
Провел анализ ретрекеров, многие не работают.
<details>
<summary>Здесь мой лог коннекта с ретрекерами</summary>
<pre>    "http://acg.rip:6699/announce"                        2m20s          error announcing: Get http://[2605:6400:20:c::beef]:6699/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: dial tcp [2605:6400:20:c::beef]:6699: connect: connection refused
    "http://bt-tracker.gamexp.ru:2710/announce"           2m24s          error getting ip: lookup bt-tracker.gamexp.ru on 192.168.97.97:53: read udp 192.168.97.98:39948->192.168.97.97:53: i/o timeout
    "http://bt.svao-ix.ru/announce"                       2m24s          error getting ip: lookup bt.svao-ix.ru on 192.168.97.97:53: read udp 192.168.97.98:45582->192.168.97.97:53: i/o timeout
    "http://bt2.54new.com:8080/announce"                  2m15s          error announcing: tracker gave failure reason: "unregistered torrent"
    "http://bt2.t-ru.org/ann"                             47m28s         30 peers
    "http://bt4.t-ru.org/ann?magnet"                      2m24s          error getting ip: lookup bt4.t-ru.org on 192.168.97.97:53: read udp 192.168.97.98:49335->192.168.97.97:53: i/o timeout
    "http://explodie.org:6969/announce"                   32m21s         15 peers
    "http://h4.trakx.nibba.trade:80/announce"             47m21s         1 peers
    "http://mail2.zelenaya.net:80/announce"               7m19s          3 peers
    "http://newtoncity.org:6969/announce"                 25m7s          1 peers
    "http://open.acgnxtracker.com:80/announce"            27m24s         1 peers
    "http://open.acgtracker.com:1096/announce"            2m34s          error announcing: Get http://62.210.177.88:1096/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    "http://opentracker.acgnx.se:80/announce"             2m20s          error announcing: tracker gave failure reason: "unregistered torrent"
    "http://pow7.com:80/announce"                         2m34s          error announcing: Get http://51.79.71.167:80/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    "http://retracker.local/announce"                     2m24s          error getting ip: lookup retracker.local on 192.168.97.97:53: read udp 192.168.97.98:45653->192.168.97.97:53: i/o timeout
    "http://retracker.mgts.by:80/announce"                2m24s          error getting ip: lookup retracker.mgts.by on 192.168.97.97:53: read udp 192.168.97.98:42278->192.168.97.97:53: i/o timeout
    "http://retracker.sevstar.net:2710/announce"          2m29s          error announcing: Get http://78.30.254.12:2710/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=18446744073709551615&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    "http://sukebei.tracker.wf:8888/announce"             2m19s          error announcing: response from tracker: 401 Unauthorized: d14:failure reason45:info hash is not authorized with this trackere
    "http://tracker.bt4g.com:2095/announce"               17m20s         1 peers
    "http://tracker.bz:80/announce"                       2m20s          error announcing: tracker gave failure reason: "1226 - User 'tt' has exceeded the 'max_user_connections' resource (current value: 50)"
    "http://tracker.city9x.com:2710/announce"             2m24s          error getting ip: lookup tracker.city9x.com on 192.168.97.97:53: read udp 192.168.97.98:38249->192.168.97.97:53: i/o timeout
    "http://tracker.darli.net:6611/announce"              2m35s          error announcing: Get http://152.67.68.11:6611/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    "http://tracker.electro-torrent.pl:80/announce"       2m36s          error announcing: Get http://62.210.202.61:80/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: dial tcp 62.210.202.61:80: i/o timeout
    "http://tracker.frozen-layer.net:6969/announce"       2m20s          error announcing: tracker gave failure reason: "unregistered torrent"
    "http://tracker.gbitt.info:80/announce"               26m30s         1 peers
    "http://tracker.internetwarriors.net:1337/announce"   2m24s          error getting ip: lookup tracker.internetwarriors.net on 192.168.97.97:53: read udp 192.168.97.98:47550->192.168.97.97:53: i/o timeout
    "http://tracker.kamigami.org:2710/announce"           27m21s         1 peers
    "http://tracker.lelux.fi:80/announce"                 27m26s         1 peers
    "http://tracker.opentrackr.org:1337/announce"         2m20s          error announcing: Get http://0.0.0.0:1337/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: dial tcp 0.0.0.0:1337: connect: connection refused
    "http://tracker.torrentyorg.pl:80/announce"           2m30s          error announcing: Get http://62.210.202.61:80/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=18446744073709551615&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    "http://tracker.tvunderground.org.ru:3218/announce"   27m26s         2 peers
    "http://tracker.yoshi210.com:6969/announce"           2m36s          error announcing: Get http://95.216.171.255:6969/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    "http://tracker01.loveapp.com:6789/announce"          26m40s         1 peers
    "http://tracker1.itzmx.com:8080/announce"             2m24s          error getting ip: lookup tracker1.itzmx.com on 192.168.97.97:53: read udp 192.168.97.98:59734->192.168.97.97:53: i/o timeout
    "http://tracker2.itzmx.com:6961/announce"             14m2s          2 peers
    "http://tracker3.itzmx.com:6961/announce"             11m20s         1 peers
    "http://tracker4.itzmx.com:2710/announce"             2m35s          error announcing: Get http://[2a04:ac00:1:3dd8::1:2710]:2710/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    "http://vps02.net.orel.ru:80/announce"                28m23s         13 peers
    "http://www.proxmox.com:6969/announce"                2m34s          error announcing: Get http://[2a01:7e0:0:424::6]:6969/announce?compact=1&downloaded=0&info_hash=%E0%F7%2A%C1%24%AFi%9E%F5J%3Bd%EB%3E%E9%BE%BE%8A%E8%86&left=1565890560&peer_id=-UT3550-F7L5IC4KVSNY&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    "https://1337.abcvg.info:443/announce"                2h28m14s       1 peers
    "https://opentracker.acgnx.se:443/announce"           2m20s          error announcing: tracker gave failure reason: "unregistered torrent"
    "https://tracker.gbitt.info:443/announce"             24m35s         1 peers
    "https://tracker.nanoha.org:443/announce"             26m52s         1 peers
    "https://zqzx.xyz:443/announce"                       27m21s         1 peers
    "udp4://46.148.18.250:2710"                           29m46s         4 peers
    "udp4://9.rarbg.me:2710/announce"                     27m20s         6 peers
    "udp4://9.rarbg.to:2710/announce"                     2m35s          error announcing: reading from socket: read udp4 192.168.97.98:41354->151.80.120.113:2710: i/o timeout
    "udp4://bt1.archive.org:6969/announce"                2m24s          error getting ip: lookup bt1.archive.org on 192.168.97.97:53: read udp 192.168.97.98:38353->192.168.97.97:53: i/o timeout
    "udp4://bt2.54new.com:8080/announce"                  2m15s          error announcing: unregistered torrent
    "udp4://bt2.archive.org:6969/announce"                24m43s         1 peers
    "udp4://chihaya.toss.li:9696/announce"                27m19s         1 peers
    "udp4://denis.stalker.upeer.me:6969/announce"         24m51s         3 peers
    "udp4://exodus.desync.com:6969/announce"              2m24s          error getting ip: no acceptable ips
    "udp4://explodie.org:6969/announce"                   32m21s         100 peers
    "udp4://ipv4.tracker.harry.lu:80/announce"            27m21s         1 peers
    "udp4://open.demonii.si:1337/announce"                25m33s         2 peers
    "udp4://open.stealth.si:80/announce"                  2m24s          error getting ip: lookup open.stealth.si on 192.168.97.97:53: read udp 192.168.97.98:52464->192.168.97.97:53: i/o timeout
    "udp4://opentor.org:2710"                             2m24s          error getting ip: lookup opentor.org on 192.168.97.97:53: read udp 192.168.97.98:45135->192.168.97.97:53: i/o timeout
    "udp4://opentor.org:2710/announce"                    2m24s          error getting ip: lookup opentor.org on 192.168.97.97:53: read udp 192.168.97.98:45135->192.168.97.97:53: i/o timeout
    "udp4://p4p.arenabg.com:1337/announce"                25m38s         3 peers
    "udp4://public.popcorn-tracker.org:6969/announce"     2m24s          error getting ip: lookup public.popcorn-tracker.org on 192.168.97.97:53: read udp 192.168.97.98:48373->192.168.97.97:53: i/o timeout
    "udp4://qg.lorzl.gq:2710/announce"                    27m15s         1 peers
    "udp4://retracker.akado-ural.ru:80/announce"          30m15s         1 peers
    "udp4://retracker.lanta-net.ru:2710/announce"         28m52s         7 peers
    "udp4://retracker.netbynet.ru:2710/announce"          27m8s          15 peers
    "udp4://retracker.sevstar.net:2710/announce"          2m29s          error announcing: reading from socket: read udp4 192.168.97.98:51187->78.30.254.12:2710: i/o timeout
    "udp4://tr.bangumi.moe:6969/announce"                 2m21s          error announcing: error parsing announce response: unexpected EOF
    "udp4://tracker-udp.gbitt.info:80/announce"           24m48s         1 peers
    "udp4://tracker.coppersurfer.tk:6969/announce"        29m11s         10 peers
    "udp4://tracker.cyberia.is:6969/announce"             28m49s         2 peers
    "udp4://tracker.dler.org:6969/announce"               2m36s          error announcing: reading from socket: read udp4 192.168.97.98:43400->223.16.205.65:6969: i/o timeout
    "udp4://tracker.ds.is:6969/announce"                  24m41s         1 peers
    "udp4://tracker.filemail.com:6969/announce"           2m24s          error getting ip: lookup tracker.filemail.com on 192.168.97.97:53: read udp 192.168.97.98:52839->192.168.97.97:53: i/o timeout
    "udp4://tracker.kamigami.org:2710/announce"           27m21s         1 peers
    "udp4://tracker.leechers-paradise.org:6969/announce"  24m20s         200 peers
    "udp4://tracker.lelux.fi:6969/announce"               2m31s          error announcing: reading from socket: read udp4 192.168.97.98:58421->104.244.79.229:6969: i/o timeout
    "udp4://tracker.moeking.me:6969/announce"             24m36s         2 peers
    "udp4://tracker.nextrp.ru:6969/announce"              28m49s         1 peers
    "udp4://tracker.nyaa.uk:6969/announce"                29m22s         1 peers
    "udp4://tracker.openbittorrent.com:80/announce"       2m24s          error getting ip: lookup tracker.openbittorrent.com on 192.168.97.97:53: read udp 192.168.97.98:33533->192.168.97.97:53: i/o timeout
    "udp4://tracker.opentrackr.org:1337/announce"         2m20s          error announcing: reading from socket: read udp4 127.0.0.1:40174->127.0.0.1:1337: read: connection refused
    "udp4://tracker.pomf.se:80/announce"                  2m34s          error announcing: reading from socket: read udp4 192.168.97.98:37722->165.231.0.116:80: i/o timeout
    "udp4://tracker.swateam.org.uk:2710/announce"         2m24s          error getting ip: lookup tracker.swateam.org.uk on 192.168.97.97:53: read udp 192.168.97.98:38550->192.168.97.97:53: i/o timeout
    "udp4://tracker.tiny-vps.com:6969/announce"           25m50s         4 peers
    "udp4://tracker.torrent.eu.org:451/announce"          29m37s         1 peers
    "udp4://tracker.trackton.ga:7070/announce"            1m24s          1 peers
    "udp4://tracker.tvunderground.org.ru:3218/announce"   2m34s          error announcing: reading from socket: read udp4 192.168.97.98:46809->91.217.91.21:3218: i/o timeout
    "udp4://tracker.uw0.xyz:6969/announce"                29m46s         1 peers
    "udp4://tracker.yoshi210.com:6969/announce"           28m37s         1 peers
    "udp4://tracker2.itzmx.com:6961/announce"             9m55s          2 peers
    "udp4://tracker3.itzmx.com:6961/announce"             10m3s          1 peers
    "udp4://tracker4.itzmx.com:2710/announce"             24m58s         15 peers
    "udp4://valakas.rollo.dnsabr.com:2710/announce"       29m45s         4 peers
    "udp4://xxxtor.com:2710/announce"                     27m28s         1 peers
    "udp4://zephir.monocul.us:6969/announce"              27m2s          2 peers
    "udp6://9.rarbg.me:2710/announce"                     2m20s          error getting ip: no acceptable ips
    "udp6://9.rarbg.to:2710/announce"                     2m20s          error getting ip: no acceptable ips
    "udp6://bt1.archive.org:6969/announce"                2m24s          error getting ip: lookup bt1.archive.org on 192.168.97.97:53: read udp 192.168.97.98:38353->192.168.97.97:53: i/o timeout
    "udp6://bt2.54new.com:8080/announce"                  2m15s          error getting ip: no acceptable ips
    "udp6://bt2.archive.org:6969/announce"                2m20s          error getting ip: no acceptable ips
    "udp6://chihaya.toss.li:9696/announce"                2m19s          error getting ip: no acceptable ips
    "udp6://denis.stalker.upeer.me:6969/announce"         2m19s          error getting ip: no acceptable ips
    "udp6://exodus.desync.com:6969/announce"              24m30s         1 peers
    "udp6://explodie.org:6969/announce"                   32m21s         14 peers
    "udp6://ipv4.tracker.harry.lu:80/announce"            2m20s          error getting ip: no acceptable ips
    "udp6://open.demonii.si:1337/announce"                2m15s          error getting ip: no acceptable ips
    "udp6://open.stealth.si:80/announce"                  2m24s          error getting ip: lookup open.stealth.si on 192.168.97.97:53: read udp 192.168.97.98:52464->192.168.97.97:53: i/o timeout
    "udp6://opentor.org:2710"                             2m24s          error getting ip: lookup opentor.org on 192.168.97.97:53: read udp 192.168.97.98:45135->192.168.97.97:53: i/o timeout
    "udp6://opentor.org:2710/announce"                    2m24s          error getting ip: lookup opentor.org on 192.168.97.97:53: read udp 192.168.97.98:45135->192.168.97.97:53: i/o timeout
    "udp6://p4p.arenabg.com:1337/announce"                2m21s          error getting ip: no acceptable ips
    "udp6://public.popcorn-tracker.org:6969/announce"     2m24s          error getting ip: lookup public.popcorn-tracker.org on 192.168.97.97:53: read udp 192.168.97.98:48373->192.168.97.97:53: i/o timeout
    "udp6://qg.lorzl.gq:2710/announce"                    2m14s          error getting ip: no acceptable ips
    "udp6://retracker.akado-ural.ru:80/announce"          2m19s          error getting ip: no acceptable ips
    "udp6://retracker.lanta-net.ru:2710/announce"         2m14s          error getting ip: no acceptable ips
    "udp6://retracker.netbynet.ru:2710/announce"          2m21s          error getting ip: no acceptable ips
    "udp6://retracker.sevstar.net:2710/announce"          2m14s          error getting ip: no acceptable ips
    "udp6://tr.bangumi.moe:6969/announce"                 2m21s          error announcing: reading from socket: read udp6 [2a05:3580:d900:1be2::98]:45519->[2001:bc8:3f5e:103::]:6969: read: connection refused
    "udp6://tracker-udp.gbitt.info:80/announce"           2m20s          error getting ip: no acceptable ips
    "udp6://tracker.coppersurfer.tk:6969/announce"        2m21s          error getting ip: no acceptable ips
    "udp6://tracker.cyberia.is:6969/announce"             28m48s         7 peers
    "udp6://tracker.dler.org:6969/announce"               2m21s          error getting ip: no acceptable ips
    "udp6://tracker.ds.is:6969/announce"                  2m20s          error getting ip: no acceptable ips
    "udp6://tracker.filemail.com:6969/announce"           2m24s          error getting ip: lookup tracker.filemail.com on 192.168.97.97:53: read udp 192.168.97.98:52839->192.168.97.97:53: i/o timeout
    "udp6://tracker.kamigami.org:2710/announce"           2m20s          error getting ip: no acceptable ips
    "udp6://tracker.leechers-paradise.org:6969/announce"  2m19s          error getting ip: no acceptable ips
    "udp6://tracker.lelux.fi:6969/announce"               2m16s          error getting ip: no acceptable ips
    "udp6://tracker.moeking.me:6969/announce"             2m19s          error getting ip: no acceptable ips
    "udp6://tracker.nextrp.ru:6969/announce"              2m20s          error getting ip: no acceptable ips
    "udp6://tracker.nyaa.uk:6969/announce"                2m21s          error getting ip: no acceptable ips
    "udp6://tracker.openbittorrent.com:80/announce"       2m24s          error getting ip: lookup tracker.openbittorrent.com on 192.168.97.97:53: read udp 192.168.97.98:33533->192.168.97.97:53: i/o timeout
    "udp6://tracker.opentrackr.org:1337/announce"         2m20s          error getting ip: no acceptable ips
    "udp6://tracker.pomf.se:80/announce"                  2m19s          error getting ip: no acceptable ips
    "udp6://tracker.swateam.org.uk:2710/announce"         2m24s          error getting ip: lookup tracker.swateam.org.uk on 192.168.97.97:53: read udp 192.168.97.98:38550->192.168.97.97:53: i/o timeout
    "udp6://tracker.tiny-vps.com:6969/announce"           2m21s          error getting ip: no acceptable ips
    "udp6://tracker.torrent.eu.org:451/announce"          29m48s         1 peers
    "udp6://tracker.trackton.ga:7070/announce"            2m20s          error getting ip: no acceptable ips
    "udp6://tracker.tvunderground.org.ru:3218/announce"   2m19s          error getting ip: no acceptable ips
    "udp6://tracker.uw0.xyz:6969/announce"                2m20s          error getting ip: no acceptable ips
    "udp6://tracker.yoshi210.com:6969/announce"           2m21s          error getting ip: no acceptable ips
    "udp6://tracker2.itzmx.com:6961/announce"             2m20s          error getting ip: no acceptable ips
    "udp6://tracker3.itzmx.com:6961/announce"             2m21s          error getting ip: no acceptable ips
    "udp6://tracker4.itzmx.com:2710/announce"             2m20s          error announcing: reading from socket: read udp6 [2a05:3580:d900:1be2::98]:44288->[2a04:ac00:1:3dd8::1:2710]:2710: read: connection refused
    "udp6://valakas.rollo.dnsabr.com:2710/announce"       3m14s          error getting ip: no acceptable ips
    "udp6://xxxtor.com:2710/announce"                     2m20s          error getting ip: no acceptable ips
    "udp6://zephir.monocul.us:6969/announce"              2m21s          error getting ip: no acceptable ips
</pre>
</details>
Предлагаю добавить ретрекер `udp://explodie.org:6969/announce`.  @YouROK добавите?

**Comment by Nemiroff** [comment]
Или использовать [эти](https://github.com/ngosang/trackerslist/blob/master/trackers_best_ip.txt)

**Comment by YouROK** [comment]
> Или использовать [эти](https://github.com/ngosang/trackerslist/blob/master/trackers_best_ip.txt)

Не в курсе наши там сидят? А то если англоязычные то и раздачи не будет находить

**Comment by avengermsoft** [comment]
Я 

> Или использовать [эти](https://github.com/ngosang/trackerslist/blob/master/trackers_best_ip.txt)

Эти трекеры, вообще не понятно кто такие.

**Comment by Nemiroff** [comment]
> > Или использовать [эти](https://github.com/ngosang/trackerslist/blob/master/trackers_best_ip.txt)
> 
> Не в курсе наши там сидят? А то если англоязычные то и раздачи не будет находить

Эти трекеры используются в торрент плагинах в movian. Он у них DHT не умеет

**Comment by YouROK** [comment]
Добавил все трекеры, пока не тестил

**Comment by avengermsoft** [comment]
Новые все рабочие.
<details>
<summary>Здесь мой лог коннекта с ретрекерами</summary>
<pre>Enabled trackers:
    URL                                                  Next announce  Last announce
    "http://bt.svao-ix.ru/announce"                      4m30s          error announcing: error decoding "You are not a member SVAO-IX!\n": bencode: syntax error (offset: 0): unknown value type 'Y'
    "http://bt4.t-ru.org/ann?magnet"                     4m30s          error announcing: tracker gave failure reason: "Wrong tracker id"
    "http://retracker.local/announce"                    29s            error getting ip: lookup retracker.local on 192.168.97.97:53: no such host
    "http://retracker.mgts.by:80/announce"               29s            error announcing: Get http://82.209.230.66:80/announce?compact=1&downloaded=1284718592&info_hash=%A8%8B%A7%5C%CB%C3%94%5B%C7u%93%FF%0A%E6m-%86%5E%86%3E&left=12431080633&peer_id=-UT3550-RWO4IXXAXSWF&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    "http://tracker.city9x.com:2710/announce"            29s            error announcing: Get http://198.54.117.198:2710/announce?compact=1&downloaded=1284718592&info_hash=%A8%8B%A7%5C%CB%C3%94%5B%C7u%93%FF%0A%E6m-%86%5E%86%3E&left=12431080633&peer_id=-UT3550-RWO4IXXAXSWF&port=22491&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    "http://tracker.electro-torrent.pl:80/announce"      11m30s         4 peers
    "http://tracker.internetwarriors.net:1337/announce"  4m29s          error getting ip: lookup tracker.internetwarriors.net on 192.168.97.97:53: no such host
    "http://tracker2.itzmx.com:6961/announce"            4m35s          6 peers
    "udp4://142.44.243.4:1337/announce"                  11m12s         1 peers
    "udp4://151.80.120.113:2710/announce"                28s            error announcing: reading from socket: read udp4 192.168.97.98:58550->151.80.120.113:2710: i/o timeout
    "udp4://151.80.120.115:2710/announce"                15m44s         4 peers
    "udp4://159.100.245.181:6969/announce"               7m38s          1 peers
    "udp4://165.231.0.116:80/announce"                   13m51s         23 peers
    "udp4://176.113.71.19:6961/announce"                 1m24s          error announcing: reading from socket: read udp4 192.168.97.98:46340->176.113.71.19:6961: i/o timeout
    "udp4://185.181.60.67:80/announce"                   8m39s          2 peers
    "udp4://188.241.58.209:6969/announce"                22m8s          23 peers
    "udp4://208.83.20.20:6969/announce"                  7m44s          1 peers
    "udp4://212.47.227.58:6969/announce"                 9m10s          1 peers
    "udp4://35.156.19.129:6969/announce"                 12m0s          1 peers
    "udp4://37.235.174.46:2710/announce"                 8m32s          1 peers
    "udp4://46.148.18.250:2710"                          7m56s          20 peers
    "udp4://5.206.54.49:6969/announce"                   8m39s          4 peers
    "udp4://51.15.40.114:80/announce"                    10m28s         1 peers
    "udp4://54.37.235.149:6969/announce"                 9m25s          1 peers
    "udp4://62.138.0.158:6969/announce"                  9m2s           18 peers
    "udp4://62.210.97.59:1337/announce"                  11m56s         1 peers
    "udp4://89.234.156.205:451/announce"                 12m31s         3 peers
    "udp4://93.158.213.92:1337/announce"                 12m19s         27 peers
    "udp4://explodie.org:6969/announce"                  14m29s         4 peers
    "udp4://opentor.org:2710"                            13m23s         20 peers
    "udp4://public.popcorn-tracker.org:6969/announce"    4m29s          error getting ip: lookup public.popcorn-tracker.org on 192.168.97.97:53: no such host
    "udp4://tracker.opentrackr.org:1337/announce"        4m29s          error announcing: reading from socket: read udp4 127.0.0.1:44460->127.0.0.1:1337: read: connection refused
    "udp6://explodie.org:6969/announce"                  14m29s         1 peers
    "udp6://opentor.org:2710"                            29s            error getting ip: no acceptable ips
    "udp6://public.popcorn-tracker.org:6969/announce"    4m29s          error getting ip: lookup public.popcorn-tracker.org on 192.168.97.97:53: no such host
    "udp6://tracker.opentrackr.org:1337/announce"        4m29s          error announcing: reading from socket: read udp6 [::1]:45154->[::1]:1337: read: connection refused</pre>
</details>
Вот на этих у меня всегда ошибки:
<pre>
http://bt.svao-ix.ru/announce
http://retracker.mgts.by:80/announce
http://tracker.city9x.com:2710/announce
</pre>
Эти возможно не рабочие. У меня всегда ошибка - host not found
<pre>
udp://public.popcorn-tracker.org:6969/announce
http://tracker.internetwarriors.net
</pre>

**Comment by avengermsoft** [comment]
Есть пиры, которые следят за сетью dht и пишут в бд ип адреса, с которых есть обмен. Тут можно посмотреть список раздач https://iknowwhatyoudownload.com/ru/peer/
Понятно, что они фиксируют лишь часть торрентов, но оценить контент по пиру можно. Например, по нашему `udp4://54.37.235.149:6969/announce` - 
https://iknowwhatyoudownload.com/ru/peer/?ip=54.37.235.149

**Comment by YouROK** [comment]
Видимо у каждого свое или хз как это работает, но вот

```
"http://bt.svao-ix.ru/announce"                      31m35s         2 peers
"http://bt4.t-ru.org/ann?magnet"                     8m59s          1 peers
"http://retracker.local/announce"                    4m18s          error getting ip: lookup retracker.local on 8.8.8.8:53: no such host
"http://retracker.mgts.by:80/announce"               4m33s          error announcing: Get http://82.209.230.66:80/announce?compact=1&downloaded=0&info_hash=a%13%8Ff%F9%DF%96~%09%0D%23%AE%27%1C%D59%2F%C9%E5L&left=18446744073709551615&peer_id=-UT3550-QVAJQ77B5TX3&port=36881&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
"http://tracker.city9x.com:2710/announce"            4m33s          error announcing: Get http://198.54.117.197:2710/announce?compact=1&downloaded=0&info_hash=a%13%8Ff%F9%DF%96~%09%0D%23%AE%27%1C%D59%2F%C9%E5L&left=18446744073709551615&peer_id=-UT3550-QVAJQ77B5TX3&port=36881&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
"http://tracker.electro-torrent.pl:80/announce"      28m1s          1 peers
"http://tracker.internetwarriors.net:1337/announce"  4m18s          error getting ip: lookup tracker.internetwarriors.net on 8.8.8.8:53: no such host
"http://tracker2.itzmx.com:6961/announce"            4m33s          error announcing: Get http://176.113.68.66:6961/announce?compact=1&downloaded=0&info_hash=a%13%8Ff%F9%DF%96~%09%0D%23%AE%27%1C%D59%2F%C9%E5L&left=18446744073709551615&peer_id=-UT3550-QVAJQ77B5TX3&port=36881&supportcrypto=1&uploaded=0: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
"udp4://46.148.18.250:2710"                          31m14s         2 peers
"udp4://opentor.org:2710"                            30m42s         2 peers
"udp4://public.popcorn-tracker.org:6969/announce"    4m18s          error getting ip: lookup public.popcorn-tracker.org on 8.8.8.8:53: no such host
"udp4://tracker.opentrackr.org:1337/announce"        31m28s         9 peers
```

**Comment by avengermsoft** [comment]
Эти ни у меня, ни у тебя не работают. Можно смело удалять:
udp://public.popcorn-tracker.org:6969/announce
http://tracker.internetwarriors.net

Проверка
`curl -k -f -s -S http://192.168.97.98:9999/btstat |grep 'no such'`
