### ISSUE TITLE
Use disk: too many open files

### ISSUE THREAD

**Issue by asxtray** [YouROK/TorrServer#61]
client.go:430: error accepting connection: accept tcp4 0.0.0.0:32000: accept4: too many open files

**Comment by YouROK** [comment]
This error is because there is a limit on opening files. Each connection counts as an open file. This is a problem in the engine.
To fix it, need to update the engine, but there is a problem with low speed.
Or disable dht so the engine does not make a lot of connections

**Comment by tsynik** [comment]
i also saw that error after enabling disk cache. looks like problem not in connections but in number of pieces torrent have and it happen on files creation in cache catalog. here is server log with bad torrent: https://pastebin.com/raw/rpxmjYV2
server goes offline just after preload torrent, and works fine with torrents which have for example ~500 pieces total in their cache dir. in my case open files limit probably ~1024 on test device.

**Comment by YouROK** [comment]
fixed in 789cb8f072f257577e9559da725ebc6a6c8e41ab
