### ISSUE TITLE
NUM — No UI Movies - 1.0.70

### ISSUE THREAD

**Issue by ghost** [YouROK/TorrServer#62]
ВЕРНИТЕ возможность выхода из приложения по кнопке Back/Назад.
Зачем открывать поиск по кнопке назад !!!
Зачем вообще убирать возможность выхода из приложения по кнопке назад, везде оно есть и раньше было в предыдущей версии.
Зачем убирать?

**Comment by YouROK** [comment]
Это не относится к этому приложению, будешь спамить во все репы, подам жалобу на тебя
