### ISSUE TITLE
Libtorrent

### ISSUE THREAD

**Issue by VuzzyM** [YouROK/TorrServer#66]
@YouROK 
Привет, нашел libtorrent для большинства платформ и на языке GO. Он не взят из elementum, он уникален, его можно использовать везде, и там все объясняется. Движок для стриминга.

Может быть в будущем вам поможет.

https://github.com/i96751414/torrest

**Comment by YouROK** [comment]
Видел этот репо, там тот же метод, как и у всех. Либу мне получилось скомпилировать, но там дальше были какие-то трудности, уже не помню. В любом случае пока нет времени заниматься переходом на libtorrent

**Comment by VuzzyM** [comment]
> Видел этот репо, там тот же метод, как и у всех. Либу мне получилось скомпилировать, но там дальше были какие-то трудности, уже не помню. В любом случае пока нет времени заниматься переходом на libtorrent

Как я уже сказал выше, в будущем

**Comment by Lontron** [comment]
@i96751414

**Comment by VuzzyM** [comment]
@proninyaroslav пометил, надеюсь не против
