### ISSUE TITLE
Тех проблема 

### ISSUE THREAD

**Issue by Gregar1911** [YouROK/TorrServer#68]
Спустя нескольких минут отключается сервер, помогите что это может быть?

**Comment by Kolovatoff** [comment]
Такая же проблема, бывает выключается сервер.

А еще часто в версии 98 сыпется ошибка в Windows:

> client.go:430: error accepting connection: read udp4 0.0.0.0:32000: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

**Comment by YouROK** [comment]
> Такая же проблема, бывает выключается сервер.
> 
> А еще часто в версии 98 сыпется ошибка в Windows:
> 
> > client.go:430: error accepting connection: read udp4 0.0.0.0:32000: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.

Бывает такая ошибка, проблема в движке. Может попробовать запуск от администратора

**Comment by YouROK** [comment]
> Спустя нескольких минут отключается сервер, помогите что это может быть?

Нужны подробности. Где запущен? Что выдает в логе?

**Comment by Kolovatoff** [comment]
> > Такая же проблема, бывает выключается сервер.
> > А еще часто в версии 98 сыпется ошибка в Windows:
> > > client.go:430: error accepting connection: read udp4 0.0.0.0:32000: wsarecvfrom: A message sent on a datagram socket was larger than the internal message buffer or some other network limit, or the buffer used to receive a datagram into was smaller than the datagram itself.
> 
> Бывает такая ошибка, проблема в движке. Может попробовать запуск от администратора

Не помогло. А также вывалилась следующая ошибка:
```
2021-06-14 23:25:07 torrent.go:1519: piece failed hash: 3 connections contributed, [{*torrent.Client [0xc000390000]} {*torrent.Piece [b0e96ed949b70c010d670292d12bed73f5dcad63/7408]} {*torrent.Torrent ["ИМЯ_ТОРРЕНТА"]}]
2021-06-14 23:25:19 torrent.go:1519: piece failed hash: 2 connections contributed, [{*torrent.Client [0xc000390000]} {*torrent.Piece [b0e96ed949b70c010d670292d12bed73f5dcad63/7412]} {*torrent.Torrent ["ИМЯ_ТОРРЕНТА"]}]
2021/06/14 23:26:33 error reading torrent b0e96ed949b70c010d670292d12bed73f5dcad63 piece 7407 offset 0, 5263 bytes: unexpected EOF
2021/06/14 23:28:54 Disconnect client
2021/06/14 23:28:54 Connect client
2021-06-14 23:32:17 torrent.go:1519: piece failed hash: 4 connections contributed, [{*torrent.Client [0xc000390000]} {*torrent.Piece [b0e96ed949b70c010d670292d12bed73f5dcad63/7519]} {*torrent.Torrent ["ИМЯ_ТОРРЕНТА"]}]
2021/06/14 23:32:55 Disconnect client


←[31m2021/06/14 23:32:55 [Recovery] 2021/06/14 - 23:32:55 panic recovered:
json: unsupported value: NaN
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/render/json.go:59 (0x52c989)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:841 (0x52ec50)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:884 (0x64e586)
/usr/src/torr/server/web/api/cache.go:46 (0x64e53c)
/usr/src/torr/server/web/api/cache.go:29 (0x64e3ec)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x539457)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/recovery.go:83 (0x53943e)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x6577a1)
/usr/src/torr/server/web/blocker/blocker.go:21 (0x657784)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x53abae)
/usr/src/torr/server/log/log.go:76 (0x53ab8b)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 (0x530de8)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 (0x530dcf)
/go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 (0x5309f4)
/usr/local/go/src/net/http/server.go:2887 (0x3fd369)
/usr/local/go/src/net/http/server.go:1952 (0x3f8ecc)
/usr/local/go/src/runtime/asm_amd64.s:1371 (0x1b00e0)
←[0m
```
P.S. Имя торрента убрал, но hash оставил.
Замечал такие проблемы на торрентах размер блока которых равен 8Мб, если размер меньше, то все хорошо в основном.

**Comment by YouROK** [comment]
Как будут подробности, открою тикет

**Comment by Gregar1911** [comment]
Запускаю я на смарт ТВ андроид 9

**Comment by Gregar1911** [comment]
Начинается просмотра все хорошо и через некоторое время бах зависания и торсервер не отвечает пишет

**Comment by YouROK** [comment]
На смарт тв мало памяти и слабый процессор, нужно ставить меньше кэш чтоб система не убивала программы.
Этот вопрос не относится к серверу, так как он не сам падает, а система закрывает
