### ISSUE TITLE
Редактирование трекеров

### ISSUE THREAD

**Issue by zomoleg** [YouROK/TorrServer#76]
Возможно ли добавить возможность редактирования (удаления/добавления) трекеров ?

**Comment by YouROK** [comment]
Это уже есть
https://github.com/YouROK/TorrServer/blob/4654c1d7fab5fdae0fcbe1b51236d09a8d259cb6/server/torr/utils/torrent.go#L33
Трекеры из файла добавляются к текущим. Если не нужны текущие, то делаем настройку удалить ретрекеры, тогда будут только из файла браться

**Comment by zomoleg** [comment]
А чтобы только по DHT смотреть, без участия трекера, включая приватные раздачи, такое возможно?

**Comment by YouROK** [comment]
Настройки же несложно открыть и посмотреть, там все есть
