### ISSUE TITLE
Зависает на linux arm7

### ISSUE THREAD

**Issue by atomoc** [YouROK/TorrServer#8]
Пробую на малинке 3 через kodi плагины, виснет. При чём как то странно устанавливается, через !! all stream install !! (как то так) не находя в репозиториях запрашивает установить с git, после чего скачивается и устанавливается.

Указываю последнюю версию скачивать (1.1.72 кажется) в настройках torrserver, скачивается, устанавливается, но так же глючит, некоторые торренты вообще не запускает.

Глючит так, что даже по ssh не подключится к малинке, может через несколько минут отвиснуть на пару секунд, потом опять, просто картинка зависает и всё, ничего не работает, только хард ресет.

**Comment by Nemiroff** [comment]
> (1.1.72 кажется)

1.1.76

**Comment by atomoc** [comment]
> > (1.1.72 кажется)
> 
> 1.1.76

Да, спасибо. Есть идеи с чем это может быть связано? С acestream проблем нет.

**Comment by YouROK** [comment]
Процессор слишком слабый, не будет нормально работать на нем либо сеть всю забивает.
Можно попробовать отключить utp и dht

**Comment by atomoc** [comment]
> Можно попробовать отключить utp и dht

Подскажи, пожалуйста, как? Скорей всего процессор, так как выключаю во время зависона кабель Ethernet и бестолку, всё равно висит.
