### ISSUE TITLE
Fix text on black theme 

### ISSUE THREAD

**Issue by VuzzyM** [YouROK/TorrServer#80]
![IMG_20210623_180344](https://user-images.githubusercontent.com/66425682/123124532-6e6c5e00-d450-11eb-8651-5f9dcdff972b.jpg)
![IMG_20210624_121629](https://user-images.githubusercontent.com/66425682/123237249-2bf56080-d4e6-11eb-92d6-bf2b20c971fd.jpg)
![IMG_20210624_121653](https://user-images.githubusercontent.com/66425682/123237253-2d268d80-d4e6-11eb-9f07-e015d0c1a94d.jpg)

**Comment by VuzzyM** [comment]
@dancheskus @tsynik

**Comment by YouROK** [comment]
Fixed
