### ISSUE TITLE
Запрос: обновление magnet ссылки без удаления предыдущей записи

### ISSUE THREAD

**Issue by mrdimfox** [YouROK/TorrServer#81]
Иногда сериалы выходят постепенно, серия за серией. Каждый раз приходиться удалять и добавлять заново по magnet ссылке сериал. Хотелось бы просто модифицировать старую. И чтобы не надо было постер заново ставить и название.

**Comment by YouROK** [comment]
Пока в планах нет такой функциональности. Много переделывать нужно. Так как вся зависимость идет от хэша торрента
