### ISSUE TITLE
Тормозит 

### ISSUE THREAD

**Issue by Dnnio** [YouROK/TorrServer#82]
Здравствуйте, на телеке в lazy media deluxe пытаюсь посмотреть фильм в обычном 1080р , но регулярно тормозит и прогружается, про 4к вообще молчу. В ютубе 4к видео спокойно грузит без напряга. Телевизор mi tv 4s , скорость инета 100 мб/с

**Comment by YouROK** [comment]
Здравствуйте, можно поставить сервер на другое устройство или менять тв на более мощный

**Comment by alexunderboots** [comment]
Поставил сервер на windows, а все клиенты на дешевом S905W - и 3D смотрю и 4К - никаких тормозов нет

**Comment by Dnnio** [comment]
Так у друга такой же телек, такой же инет и все спокойно грузит. Настройки вроде точно такие же как у него

**Comment by alexunderboots** [comment]
Всегда есть волшебное слово "вроде". Сброс на заводские настройки, подключение по кабелю, плеер ViMu или VLC. Проблема в вашем железе или инфраструктуре

**Comment by YouROK** [comment]
Попробуйте сервер с новым движком, выкладывали в телеграм

**Comment by YouROK** [comment]
Теперь в релизе с новым движком

**Comment by epexa** [comment]
https://github.com/YouROK/TorrServer/issues/11
