### ISSUE TITLE
Kodi + torrserve 101

### ISSUE THREAD

**Issue by vic1234** [YouROK/TorrServer#86]
При использовании kodi на последнем релизе
При перемотки в коди вперёд назад не важно
Стало не сбрасывать предыдущей кеш а кочать его по кругу 

Текушею позицию не качает на беред даже на паузе

https://user-images.githubusercontent.com/2455975/126296940-7bbcaa67-9d4c-4db9-b4dd-3dd7e4825c03.mp4

**Comment by Mutronics** [comment]
Проблема с перемоткой в коди, это помоему всегда было и никогда не исправлялось, никогда не мотаю.

**Comment by vic1234** [comment]
> Проблема с перемоткой в коди, это помоему всегда было и никогда не исправлялось, никогда не мотаю.

Нет
В какой то из matrix YouROK исправил старый кеш выгружало
А сейчас качает его по кругу даже если видео на паузе

**Comment by YouROK** [comment]
Проверь на версии 104

**Comment by vic1234** [comment]
@YouROK на 104 все ок
списибо
