### ISSUE TITLE
[Help] Matrix 102.OE - возобновить фильм назад

### ISSUE THREAD

**Issue by VuzzyM** [YouROK/TorrServer#89]
Привет

https://github.com/VuzzyM/TorrServer/releases

@YouROK можешь ли сделать возобновить фильм назад в matrix 102.oe , как в matrix 102?

**Comment by YouROK** [comment]
Что за возобновить фильм назад?

**Comment by VuzzyM** [comment]
> Что за возобновить фильм назад?

@YouROK .OE при пермотке назад имеет проблемы

**Comment by YouROK** [comment]
Да старый движок имеет эти проблемы

**Comment by VuzzyM** [comment]
> Да старый движок имеет эти проблемы

Если такой возможности нет, закрою эту тему

**Comment by YouROK** [comment]
Была бы возможность, давно бы исправил в старом движке
