### ISSUE TITLE
[bug] Пустая белая страница в веб-интерфейсе на старых устройствах

### ISSUE THREAD

**Issue by virserg** [YouROK/TorrServer#90]
Добрый день! 

На MatriX.102 наблюдаю пустую белую страницу в веб-интерфейсе на android 4.1.2, 4.2.2 в любом браузере.  Такое поведение не только у меня. 
В MatriX.98 веб работает нормально. 
Почитать можно http://xbmc.ru/forum/showthread.php?p=164224#post164224

**Comment by tsynik** [comment]
На андроидах 4.2 можно пользоваться клиентом TorrServe MatriX для управления торрентами и изменения настроек сервера. Так же вероятно там доступны альтернативные браузеры типа firefox или opera и поведение может отличаться.

**Comment by virserg** [comment]
А как быть с 4.1.2 ? До 98 все работало, а потом что-то сломали...
Да человек пишет об 4.2.2 http://xbmc.ru/forum/showpost.php?p=164232&postcount=417

**Comment by tsynik** [comment]
А 4.1.2 поддерживаться клиентом не будет да и в принципе. Хотя можно конечно еще понизить апи клиента, но я смысла не вижу.

**Comment by YouROK** [comment]
До 4.1?

**Comment by tsynik** [comment]
Да. Посмотрел поведение клиента на 4.1 и 4.2 в эмуляторе - все работает, но форматирование настроек и диалогов (например добавления торрента) в 4.2 нормальное а в 4.1 - кривое (без отступов вообще). Не стоит понижать.

**Comment by tsynik** [comment]
И вот веб 102-го матрикса в Firefox на Android 4.2. Используйте Firefox для доступа к серверу.

![4 2-M102-Web](https://user-images.githubusercontent.com/1551446/127689561-3925cb10-817e-43ab-86a9-676f6be68e45.png)
![4 2-M 102-Details](https://user-images.githubusercontent.com/1551446/127689568-d15b1e75-71c5-40bd-86d3-4cb2b409868f.png)
