### ISSUE TITLE
Конфигурация IP / интерфейса, на котором слушает сервер

### ISSUE THREAD

**Issue by ikarsokolov** [YouROK/TorrServer#96]
Сейчас сервер биндится на все доступные сетевые интерфейсы.  Включая публичные если работает IPv6. С открытым доступом для всех по-умолчанию.

Думаю это не то, что нужно среднему пользователю в локальной сети.

Предлагаю добавить возможность вместе с веб-портом задавать IP для биндинга.
Или ключ **--ipv4-only**.

**Comment by YouROK** [comment]
В вебе можно отключить ipv6

**Comment by ikarsokolov** [comment]
> В вебе можно отключить ipv6

Только для торрента. 
Веб-сервер биндится ко всем интерфейсам https://github.com/YouROK/TorrServer/blob/8d6976d1552b186470d48fbc6f332767ab87ee27/server/server.go#L20

**Comment by tsynik** [comment]
> Только для торрента.
> Веб-сервер биндится ко всем интерфейсам

Так про торрент и речь же? В сервере можно включить авторизацию. Приведенная строка - просто проверка порта, двумя строками далее это соединение закрывается.

**Comment by avengermsoft** [comment]
На keeneric доступ к ipv6 закрыт по умолчанию. Порты нужно открывать руками. Настройте свой роутер правильно.
